### ISSUE TITLE
Curriculum draft: peer review

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#10]
https://github.com/foundersandcoders/master-reference/blob/master/curriculum.md

The above is an initial draft of the 10-week curriculum based upon FAC9 feedback so far and a summation of FAC7-9's gitbooks. We want to incorporate people's feedback on it prior to curriculum planning with FAC9 on the 12th December (next Monday) so it can be used as a template for discussion with them. 

If you have a strong view on the curriculum or the ordering of the weeks, now is the opportune moment to share it. Please do so here asap to give me and @des-des time to incorporate your feedback in advance of the 12th. 🐱

**Comment by des-des** [comment]
@iteles @nelsonic @sohilpandya

**Comment by eliascodes** [comment]
Thanks for your work guys, really good. I have couple of questions:

* Morning challenges
We’ll need at least 20 morning challenges, ideally well thought out and oriented to the learning objectives of each week, or exploring things we won’t cover in the curriculum. Is the plan for each cohort to ad-hoc them, or to develop some kind of library of challenges that we can add to or modify as appropriate?

* Fridays
Fridays look to be set up the same as always. FAC9 (and FACs before them) have said Fridays can be a little unstructured and it feels like better use could be made of the time. Is this still likely to be the case?

* ES6 in week 1
I’m also in favour of introducing ES6 syntax earlier as long as the distinction is made clear and issues like browser compatibility are highlighted.

* Debugger
Chrome inspector/dev tools are README topics, but from what I’ve seen, because of the fact that they are ‘just’ tooling, it's often overlooked and left under-utilised in subsequent weeks. Maybe make it part of the whiteboard walkthrough that week as well? Making good use of the debugger will improve your productivity immensely.

* Auth week
It’d be good for them to understand the pros and cons of a stateful (i.e. cookies with server managing sessions) session management vs a stateless (i.e. JWT) session management, and what each should and shouldn’t be used for. On our cohort the impression I got was that JWT was just the new way to do sessions and you could forget about stateful sessions, which was no doubt not the intent, but anyway.

* DB Week
What is the rationale behind delaying the introduction of databases to week 8? Without a DB layer, the Auth apps are going to be using in-memory caches? This means they don’t get as much practise writing and structuring lots of async code on the backend. SQL is essentially a new language for them to learn, so I guess I can understand delaying until everyone is super comfortable with node, but on the other hand, an extra week of having to practise SQL might also be helpful.

* Week 9
Seems a bit light on content. Good idea trying to sneak web sockets back in, I’m down with that. Since week 9 might end up being a mongrel week, what about introducing SASS (or some UX stuff) too, since weeks 7 and 8 will have been super back-end heavy?

* Week 10
Is the project the whole week long? 

* Weeks 11+
If weeks 1-10 are meant to be stable, what is the point of having FAC N+1 planning in week 11? FAC N’s feedback will be most useful when structuring the weeks after the curriculum ends, but by week 11, they’d have barely begun that time.

What proportion of the post-curriculum weeks are we planning to spend on time for learning new stuff, and what proportion will be spent on doing things like the design sprints for charities that FAC8 did (or the hackathons that we did)?

Are DWYL still meant to be doing some teaching in weeks 11/12?

Who is responsible for ensuring that the post-curriculum weeks are filled with something?

Thanks again for starting this 👍

**Comment by Jbarget** [comment]
**Morning Challenges** (just seen @eliascodes makes a similar point)

I'd like to suggest having a more structured 'library' of morning challenges for mentors to be able to choose from. Each with its own:
- title
- description
- solution
- learning points for the mentor to focus on

**Week Seven:** HAPI Part Two Authentication

I'd like to vote for doing JWT sessions without using a module as otherwise only people who write the JWT README will have written the full JWT flow

**Week Nine:** Testing & Deploying your Database Layer (w postgres)

Is there a thread for discussions around what this week, I may be missing something but my first impressions is that time may be better spent elsewhere considering they would have deployed their app with databases on heroku the week before and potentially been introduced to testing in that first week of DBs.

**Visualisations: D3, Chart.js, Leaflet**

I'd like to put visualisations into the discussion, whether theres a week for them with a fun project or if they're dotted around the projects as stretch goals...
@des-des and I have put chart.js as a stretch goal for one of the *suggested projects* this week (to visualise issue tracking from github API) - will be interesting to see if its viable or not.

**In response to @eliascodes**:

- I agree with integrating debugger and learning how to use it early on would be beneficial
- I think ES6 in week 1 might not be a good idea as there may still be people who are getting to grips with Javascript in general. Also if I didnt know about ES6 and there were people who already knew it on the cohort I would find it a bit daunting (particularly in week 1)

**Comment by bradreeder** [comment]
@eliascodes Thanks for getting the discussion started. 🎉 

* Morning challenges: The aim is for the master-reference to eventually become such a library of resources, yes. The advantage of stabilising the core curriculum is that the overall emphasis of mentor's time can become improving existing resources rather than reinventing from scratch. Over time, this will mean our curriculum will become replicable, accessible to people who don't make it on the course, and far easier for each new set of mentors to manage.

* Friday's: Could you clarify what's unstructured about them? Code reviewing, responding to issues, stop-go-continue, and presentations, fills the day generally.

* DB weeks: These are the most incompletely thought out in honesty. 1 week isn't enough for databases, so it's a question of what progression makes sense over 2 weeks, and when. If you have a good idea about this it'd be appreciated. We want to keep regular monday-friday weeks, without weeks spilling over.

* Week 10: Yes, though I think we spoke about making it into a UX week instead as well.

* Weeks 11-16: My understanding is that these weeks are open to variation atm. But we've discussed something like: week 11 -- curriculum planning (in which case me and @des-des will run it), week 12 -- dwyl, or something fun/ experimental (D3, AR, etc.), weeks 13+ client work (which @sofer  is responsible for).

* Planning week: FAC-N are generally assigned to weeks 1-10, so why not plan immediately after while it's fresh on their minds? I proposed this week, as I feel mentors should be given adequate, structured office hours to get their week's/planning organised in advance of their client work so it's off their minds, and done in the event someone has to take over for them.

One thing we discussed is setting a project for this week, identifying a gap in our resources and creating a new resource they can use as a workshop/ readme/ morning challenge when they deliver. This way, we can balance mentors having the freedom to create new resources (of a focused quality) with improving existing resources.

Keep em' coming. 👍

**Comment by sohilpandya** [comment]
Awesome work @\all

I’ve gathered some thoughts on the above and would like to get some conversations going around each of the points. :smile: (although I’m sure some of it is probably an overlap of what Elias/Justen have brought up)

Agree with @eliascodes & @jbarget on quite a few of the things
- We need a list of morning challenges. 
- ES6 in week 1 is great :+1: as long as they are aware of compatibility issues. 
- D3/websockets for the win! 

## **Whiteboard Walkthrough**

- Have you thought about moving the Whiteboard walkthrough to the Wednesday just before they are starting the project so that we can iron out any concerns they may have? 

- Another thought is to have this walkthrough take place on a Monday morning so that they’ve had a weekend to let the whole week simmer and potentially boil down to a few questions. 

Just some options. 

## **Readmes**

- Just a little concern over this particular point, we may need to build a guide on how/what is required of a readme. 
    - Tutorials?
    - Screencasts
    - Brief descriptions 
- Because what's happens with readme is that it becomes quite a bit of a copy and paste job. As @nelsonic describes this very well, if it’s taken someone a whole day to understand a concept, then they should make sure that it takes the next person learning it half that time to understand the same concepts. 
- Also, have we thought of an alternative to Readmes? We’ve had tons of readmes being built every cohort and then they just get lost. I think there should be some sort of continuity with readmes just like what we are trying to achieve with this master-reference. 💭 
- We should also consider having just 4 readme topics every week, rather than having 5/6 like we’ve done in the past. 
	

## **Node Weeks** + **Database**

**Node**
- Have we thought about condensing the material for week 4 and 5 into just week 4? 
- I think it is possible at a push, I personally don’t see the value of adding a core node for week 5 when we will cover Istanbul/ci/debugger none of those are technically core node things and they can be plugged in with workshops. (Just what I’m thinking, as we don’t have a lot of time to work with)
**Database**
- Following on from above, it would be good to introduce DB after CoreNode, so that they get to practice a lot of the core node things with a DB, rather than waiting till week 8, Hapi can then follow the DB week. 


## **More Database**

- Does Database require 2 weeks? 
- Can we not create a 1 full day workshop which will guide them on how to go about creating -> testing -> deploying a database 
    - I think that would be possible
- And that way again we can condense databases from 2 to 1 week. Leaving 1 week entirely for web sockets potentially???

- Now if we stick with having 2 weeks for DB, we need to go deeper, I.e. pub/sub should be introduced and optimisation of query for SQL should also be looked into or building complex queries.


## **Curriculum planning for future cohorts**

- If we are to set out this Master curriculum, do you reckon we will still need a whole week for planning for the future cohorts?
    - My thoughts are that it will only require tweaking and not build from the ground up again, hence less time will need to be spent on it. Free up some from the curriculum that way? 

## **Frontend Frameworks**

- Do we need to introduce a frontend framework? 
    - They can pretty much build everything with just handlebars, but a lot of people join the course in the hope that they will be going out into the market and getting a job, and most if not all of the people who go straight out to get a job are likely to end up with a frontend role, does this mean it’s our duty to introduce it to them? So that they are better prepared?
        - Elm/React/Angular/Vue (or the next big thing which companies are looking to hire in?)

## **Misc**

- Over the last few cohorts, there has been less of an emphasis on the students to go out for evening meetups to tap up work/socialise with entrepreneurs. Mainly because weeks 12-16 have revolved around working with charities. 
    - I think this is quite a crucial piece of skill that people should be learning
    - Ability to talk to potential clients/talk about yourselves and your journey and to build a network is a good challenge to have. (If any of them wish to stick around as freelancers, this would be of benefit)

Again, sorry for the long list, would love to hear back from you all!

**Comment by sohilpandya** [comment]
so for anyone who is interested, can we have lunch tomorrow to discuss this further? 

@des-des @bradreeder @eliascodes @Jbarget @iteles @nelsonic @minaorangina @heron2014

**Comment by RachBLondon** [comment]
as someone who joined FAC with rather limited JS knowledge, I also agree with @Jbarget  that ES6 in week one might be overwhelming. It will also would limit students ability to code review each others work. Particularly might be tricky for students who fall behind to deal with.

**Comment by Jbarget** [comment]
@sohilpandya in the update to your original post who are the 'few people'?

**Comment by sohilpandya** [comment]
Oops @Jbarget, updated that now. 👍

**Comment by RachBLondon** [comment]
@des-des @sohilpandya @bradreeder Re: Front-end frame works. I have a talk I prepared for Leeds JS. called "learning React & Redux as a junior developer" which could be a quick overview of react /redux. Happy to come in and do this if its of use.

**Comment by sohilpandya** [comment]
If we go down the _react_ route for the **frontend** then that might be a great addition! 👍

**Comment by bradreeder** [comment]
@sohilpandya I'm working for a client in their office at the moment so unfortunately I can't make it for lunch. If anyone wanted to go out for beers after FAC tomorrow I'd be happy to come down and talk about it then. Happy for @des-des to cover alternatively, but if you do make sure to record the main notes as I'm meant to be running next Monday and it'd be good to be in the loop.

**Comment by bradreeder** [comment]
Alternatively, I could join in remotely (?)

**Comment by eliascodes** [comment]
@sohilpandya 

definitely agree that front-end frameworks and tooling (i.e. webpack, babel, gulp, etc) is the biggest hole in the plan as it stands. I think if the concept is to make weeks 1-10 about fundamentals though, it makes more sense to move that stuff to weeks 11-12.

Also think that while making TDD an ever-present thing is a nice idea, I don't quite understand how it would work in practice. I reckon we'll end up spending a week on it anyway. Many people coming into the course wont understand the concept of _testing_, let alone _test driven development_. Every FAC people say that they struggle to understand the what, why and how of testing, particularly when writing code they're not too familiar with. They need time to get comfortable with that. We'll still need a testing/TDD workshop, we'll still need to give them time to understand the APIs of whatever test framework we're using, to understand how to write testable code. Is the suggestion to then do all of that plus XHR requests at the same time? I think that's asking a lot.

**Comment by sohilpandya** [comment]
@/all 1pm tomorrow for lunch and coming to some sort of a conclusion 
**options**
- [ ] Thai
- [ ] Recharge 
- [ ] Chesterfield 

# Agenda 
- [ ] finalise structure for week 0 - 12 
- [ ] TDD week? Or restructure workshops for every week so that they are in a TDD format + weekly emphasis on it. 
- [ ] Node -> DB -> Hapi **OR** Node -> Hapi -> DB
- [ ] Frontend Framework 


Please do add to the agenda as you see fit.

**Comment by bradreeder** [comment]
Awesome, thanks for arranging this @sohilpandya 👍 . If you're eating out I probably won't be able to join you sadly. Could someone please take minutes and post-meeting write up into this issue a report of the consensus that you all reach? I think it's important to have a record of the rationale.

The only thing I want to emphasise is that we get the overall structure of weeks 1-10 nailed down. My experience with these meetings is that they easily diverge where all we need to decide with FAC9 on Monday is what the broad themes of weeks 1-10 will be so we can assign them to weeks -- there's plenty more time to discuss the minute details and weeks 11+ after that.

**Comment by Jbarget** [comment]
added es6 to your comment @sohilpandya as there was a bit of chat with no conclusion

**Comment by des-des** [comment]
@/all @sohilpandya I was thinking, It would be nice to start by going through everyone, and asking for 2 things that they would change in the current syllabus. Since not everyone has contributed to the agenda, it will be a way of making sure, whatever we get out of the meeting, we get everyones option.

**Comment by sohilpandya** [comment]
Hey all. I'm running late (chores have over run) please let me know where you end up and I'll come and join in slightly later than expected. 😔 Stuck on picadilly line (by far the worst line of all)

**Comment by des-des** [comment]
Okay, I have no idea if chesterfield does good food, and recharge is too small. So I guess we'll do Thai (again)

**Comment by des-des** [comment]
Okay everyone. Thai at 1.05 try to read the current proposal, and if you can bring 2 ideas for improvements that would be awesome!

**Comment by iteles** [comment]
**TDD**
I really love the idea of building TDD into the workshops every week, but similarly to @eliascodes, I'm not sure that doing away with the TDD week completely will work. People come in with zero testing knowledge and find it pretty difficult to understand the concept, so learning it in tandem with something else *every time* (without any dedicated time to testing alone) might be a struggle.

**ES6**
I'm wary of introducing anything in week 1 (or mostly at all) that we're then going to say 'you shouldn't really use this all the time because it causes major IE issues. The idea is that this is a course of fundamentals (which is why we teach pure CSS and not SASS or Javascript and not jQuery for example) which they can later enhance. In the 'real world' most clients will still need to support IE as their major browser, so just being *aware* of the compatibility problems and still using it everywhere isn't very realistic.

**Databases**
Historically we have done 1.5 weeks on this and the mileage has varied. Some cohorts feel it's not enough, others feel it's too much. If it's done after hapi, it tends to be a good amount of time because they're still figuring out node and hapi.
If we're introducing testing of databases in a robust way (which we without a doubt should), 2 weeks may be just about right but I'm happy to take the students' lead on timing.

**Comment by des-des** [comment]
Minutes: 

9/12/16

## 2 improvement from everyone

### Jack Rans
 1. Week 9. Websockets? We should use redis + pubsub.
 2. week 5: Error handling: After node. readmes error handling debugger

### Anita
 1. Front end framework in the first 10 weeks. Also lots of dom maniputaltionm in client so you see you front end framework gives you
 2. Week 2: TDD, is this too soon for tdd, maybe to early.

### Sam
 1. Linting is in week 4, would put it in two
 2. There should be some instruction on how to architect the back-end. Maybe in db week. How to connect the queries on client to queries on server.

### Sohil
 1. Structure: Get rid of tdd week: Do we want tdd in one week, or every week
 2. Hapi week after databases
 3. front end framework tbd?

### Mina
 1. Only 2/3 weeks front end, the rest is node. We need more front end + css, etc.
 2. Introduce es6 in some way, we need to do it in such a way as to not confuse people. Clear differences use case etc. diff between es6 / 5

## Jack C
 1. Redis pub/sub in week 9. We might want to do redix week 8.
 2. Preping for the real world. job applications, tech interviews, how to do it effectivily

## Justin
 1. Double data base week. Week 9 sounds very vague
 2. visualisations week!

## Elias
 1. Move database week earlier. Prob before hapi.
 2. Web sockets.

## Nelson
 1. +1 visualisations, ux, ui <- more ui and ux stuff at the start of the course
 2. Security! How you you secure your backend. Workshop / talk p
 3. User testing. Leaving the classroom and doing real user testing ie tech hub.

## Eoin
 1. More time doing dbs, maybe in node week
 2. + visualisations, d3, pub/sub, redis

# What I wished I had learned
## Jc
 1. Hardware. IOT.
## Anite
 1. sockets pub/sub. real time
## Sohil
 1. JS in detail. JS the good parts.
## Mina
 1. Testing!! What??
 2. Programming paradimns. What is OO??
## JR
 1. Learning OO properly
## Justin
 1. Real world? How are things done? More talks from node in production in indistory. How it changes. (nelson) be careful of who you trust.
## Sam
 1. Functional programming! How to do it in real life.
## Elias
 1. Patterns and architecture
## nelson
 1. PWA's.
 2. FAC camping trip
 3. Inheriting, extending and improving someone else's code
## Eoin
 1. Posgresql


Key points
 1. Database weeks! Redis pub sub. Where does this come in fac
 2. tdd week
 3. front end framework.
 4. es6
 4. visualisations

1. DB
For FAC9 took 1.5 weeks to teach SQL and they ended up writing no tests
Are we doing 2 weeks of node and then 2 weeks of DB?
Can just have 2 Node + 1 PG then have sockets/redis in week 9 for some fun
What about switching the order of PG and redis? Because redis is simpler? PG first because structured is more fundamental and important and pub/sub goes well with sockets
Agreement that there should be one DB before HAPI, but after 2 node weeks. (Redis - PSQL - Abstain) = 2 - 6 - 2
Projects should be conceived around the technologies that are emphasised in that week (structured v unstructured data)

2. TDD
JR thought QUnit was a layer of abstraction too far, and thought that tape was much easier to get started with.
Can do front-end testing with tape, and it might be similar

AN: Replace week 2 with a more fundamental, deep understanding of patterns etc with vanilla JS
MO: Build something without testing then see where testing is useful, instead of introducing it cold
SP: FAC7 had TDD week for first time. They tested more than most other FACs, so not an issue introducing early. Should introduce it in week 1!
OD: More testing, needs to be a focus of QA, focus on how teams do QA, don't merge without tests, etc.
SG: Clear, simple workshop explaining how to test what the new tech in each week ++++
JR: I was a mess everyday! Trying to reduce the number of new things at once is the key. Testing shapes my code nowadays, so actually it's good to have it early to reinforce that.
OD: In the master-reference, we want testing to be significant part of every week
NE: Thought QUnit was the simplest way to introduce a testing framework
SG: Why do you need modules for tape?
NE: Browser-based testing w. visual feedback might be easier to get head around for beginners.
NE: Writing codewars Kata, you have to write tests, good way to introduce?
JR: Pure JS allows you to focus on testing instead of DOM stuff.
JR: Week 2 should be pure JS w/ testing, without DOM stuff
SP: QUnit can be used for pure JS as a basis, then built up with DOM, async, etc. over subsequent days. Restructure week 2 around that idea.

3. Front-end frameworks
Front-end frameworks
NE: Possible consensus of trying to build without a framework to feel the pain
NE: Alternative, picking a specific way of maintaining state on the client
AN: Doing vanilla JS on a complex front-end gives you a more fundamental understanding of JS and requires learning design patterns and understanding ways to manage state and such.
MO: There are a lot of jobs asking for React skills
JR: Liked React bc it manages state and props really well. But can do that with redux by itself, without React.
NE: State management is the hard thing, rendering to the DOM can be done all sorts of ways. Abramovs tutorials are good, because they don’t mention React at the beginning
MO: Even did a tutorial using Redux on server-side.
AN: What about pure vanilla JS with Redux
SP: Consensus that learning Redux is key
MO: What about finding jobs after FAC then?
NE: Once you give ppl a tool they think they need to use it for everything
NE: If we’re introducing something, think of project that exercises that something. Let them feel the pain first, then notice how the something solves the pain.
MO: Emphasise that frameworks come and go.
EM: When is all this happening?
NE: I’m going to introduce FP with elm in weeks 12-13
MO: Prefer functional, but again jobs require knowledge of other paradigms (OO), esp in interviews
SP: should the previous weeks introduce functional stuff?
NE: Should have morning challenges that show the differences between OO/FP/imperative ++
AN: Small project that can be done in both OO/imperative and FP
NE: Testing could be a good place to understand the difference between OO and FP
SP: If universities teach OO, who’s doing FP?
NE: Funding and historical thing that uni’s teach OO. Interviews will ask for OO, and we need to do a better job preparing them for that.
SP: Need to find space in the course for this, don’t think node needs 2 weeks. Could cut some slack here in order to allow time later on in the course to do introduce a front-end framework (before the week 10 project?)

**Comment by iteles** [comment]
Particularly enjoyed reading through the 2 improvements from everyone (going into it cold rather than primed by a conversation) 👍

**Comment by des-des** [comment]
I have build an issue to capture the weeks 11+ conversation #14

**Comment by des-des** [comment]
I think we want to get visualisations back into the course. Issue #15

**Comment by des-des** [comment]
Issue for tdd week #16

**Comment by des-des** [comment]
@jrans @heron2014 @sohilpandya @minaorangina @jrans @Jbarget @g-sam @eliascodes @nelsonic.

Hi everyone I have put some of this into this pull #13. I am aware that I may not have perfectly reflected everyone's views, and possibly missed something. This will be evolving over the coming months before fac10/facn0.

If you feel I have missed something, sorry, and feel free to raise an issue, there we can have a properly documented discussion. Hopefully we can get any changes people want into the curriculum. I'll have another pass over the minutes in the coming week so i'll try to make sure everything is in the syllabus or captured in it's own issue.

**Comment by bradreeder** [comment]
I'm very happy with this overall, nice work everyone. <3

I have a few notes but I'll merge this now and flag them tomorrow:

* I think if ES6 is introduced it should be in weeks 4 or 5 alongside node to make it clear that they should be discouraged from using it in client-side code. Especially given that we're not teaching webpack, babel, etc.
* Linting for week 2 sounds good so we don't introduce too many new technologies in weeks 4/5.
* Talks on jobs and networking should probably be later in the course than week 1 when it's more timely to the students.
* Making weeks 9 & 10 'fun' wind-down weeks rather than foundational seems a solid plan to me as people get exhausted by this stage in the course. Could always alternate redis and d3 in week 9, as we don't have time for both?
* If we're going to make weeks 11/12 about doing a big project, there's no need for week 10 to be 8 man projects. Making it into a UX week that also prepares them for working with clients and gets them thinking about jobs, cv, etc prior to the break sounds ideal. I think introducing new technologies in week 10 isn't a good idea as people are too tired to take on new information then.

**Comment by des-des** [comment]
@bradreeder can we close this?
