### ISSUE TITLE
Proposed structure of each FAC's github organisation

### ISSUE THREAD

**Issue by Jbarget** [foundersandcoders/master-reference#12]
Each cohort that runs through the course seems to have a different structure of how they use github. In terms of someone being able to actually find and use the resources between FACs i'd like to propose adding a uniform structure to each cohorts work within Github (READMEs, morning challenge solutions, projects, workshops, SGC minutes)

**Comment by Jbarget** [comment]
To describe my pain point with an example:
Out of the teams that have made up the last 3 weeks, 2 of the teams have held their projects under the FAC9 organisation and 2 have created separate organisations specifically for their projects. With no reference to the separate organisations within the FAC9 organisation. How would anyone know?

The teams have changed this week so not sure where they are now storing their projects.

**Comment by des-des** [comment]
@Jbarget I think sgc minutes should go in this repo. Workshops and morning challenges should also have a list of links I think in this repo. Am easy about other points.

**Comment by jsms90** [comment]
@Jbarget I think this is a really good plan. Our notes repo has been a real pain! Most things are in there, including links to our projects, but not remotely in the most sensible way possible.

FAC9 could encourage use of the appropriate repos by leading by example
e.g.
The morning challenge gets added to the FAC10 repo (on the morning itself, not in advance)
A link is provided in the gitter channel (rather than pasting the morning challenge itself into gitter)
The student who chromecasts the solution is responsible for adding the solution to the repo - prompted by the mentor. This would also give FAC10 slightly more git practice, little-by-little.

The same would be good for workshops - put a forked version in their workshops repo. This would also solve the version issue that @bradreeder mentioned in issue #28 

When FAC9 started, I remember someone asking what the convention was re-projects but the answer was sort of whatever you want. I'm sure that whatever the mentors suggested would end up happening & if there was a Projects repo, people would know to use that :+1:

**Comment by jsms90** [comment]
See [this discussion](https://github.com/foundersandcoders/master-reference/issues/24#issuecomment-280699826) from the week 1 planning issue.

1. Create a GitHub organisation called `FACN`
2. Create three repositories, and initialise them with a README.md file and a CONTRIBUTING.md file (except for prerequisites-gh-pages):
  + `prerequisites-gh-pages`:
    + [README.md](https://github.com/FAC10/prerequisites-gh-pages/commit/a8d90543f7115bc9593ef1747ceec7c2a8eb4c3f)
  + `research`:
    + [README.md](https://github.com/FAC10/research/blob/09ac49dde8edd9eab09bfd94f4e064de32fccd99/README.md)
    + [CONTRIBUTING.md](https://github.com/FAC10/research/blob/6ba3a7baf0ea0996d77fac549ced3c4c016c8a2a/CONTRIBUTING.md)
  + `morning-challenge-solutions`:
    + [README.md](https://github.com/FAC10/morning-challenge-solutions/blob/bb24a3ac80f0b1334ea0e2725d02d1e059bd6c57/README.md)
    + [CONTRIBUTING.md](https://github.com/FAC10/morning-challenge-solutions/blob/bb24a3ac80f0b1334ea0e2725d02d1e059bd6c57/CONTRIBUTING.md)

**Comment by bradreeder** [comment]
I'd suggest we also add a `retrospectives` repo to the github organisation structure in which the core decisions of team retrospectives are captured for each group. 

Say they're run in a stop-go-continue format and at the end we ask the groups to vote on the most important items they'd like to work on next week, we can capture this decision in this repo for teams/ mentors to refer to in the next week.

**Comment by iteles** [comment]
Sorry I didn't see this earlier (I was following up until last week) - could someone please explain why we want to create multiple *organisations* (one for each cohort) instead of multiple *repos*? I'm not following.

**Comment by des-des** [comment]
@iteles one benefit is that each cohort can have complete control over their org (it like there own special space).

**Comment by Jbarget** [comment]
i get the impression that having each cohort as an org gives us the flexibility that a repo does not. Since with a repo the only child 'assets' is an `issue` with which we end up with 100+ issues that are quite hard to search through and distinguish.

If we have `master-reference`, `nazareth-programme`, `london-programme` under `foundersandcoders` to hold location specific info then i think this could be a better solution of structuring cohorts (as this solves the first comment of the issue)

**Comment by bradreeder** [comment]
@iteles the main immediate benefits I see are that organisations can have repos as child assets as @Jbarget said. Things like morning-challenge solutions, READMEs, etc, could all be stored in one repo, however their team-projects for each week, which require their own repo, are typically all stored in the github organisation.

Cohorts develop in their own ways and sometimes want to create their own repos (like FAC9's [notes](https://github.com/FAC9/notes) repo). Having their own organisation, they have ownership over, is also convenient as a location to store these cohort-specific repos, rather than cluttering the F&C organisation.

**Comment by jsms90** [comment]
@nelsonic @iteles 
I responded to this issue in PR #169. For the sake of recording this conversation in one place, I will re-post here:
> It's tough. I did think about this before creating everything in FAC10's organisation.
>
> I guess it's a toss up between seeing the work of all the cohorts who came before you, and being able to navigate easily through the repos that are most relevant to you.
>
> 1. I had a really fun and interesting time trawling through all the repos that existed when I arrived (before @rebeccaradding's useful clear out). But it is really nice to be able to find what you want faster. Imagine if you want to find any of the work that you did after you've finished the course, and there are tonnes of new repos to search through. Especially when there was no naming convention for each cohort's project repos.
> 
> 2. What I _would_ prefer to exist inside `foundersandcoders` are all the workshops that we use, for easy access. But not necessarily 50 stopwatches.
>
> 3. One other thing that tipped the scales for me is that we ask every cohort to repeat the readmes / research day that the last cohort did (no comment). Being a curious little bunny, I'm sure I would have happened across previous cohorts' research repos if there were stored in `foundersandcoders`.

**Comment by jsms90** [comment]
In response to @iteles 
> Its own github organisation? Not repo?

and @nelsonic 
> this has been the cause of the fragmentation and loss of knowledge from one "cohort" to another ... why not simply create a team in this Org?

`FAC9 's `notes` repo was, among other things, my first attempt to solve that exact problem. The repo contains links to all our projects, for future reference. Because in my cohort, we created our own organisations whenever we formed a new team, and stored our projects in there. Or, sometimes people created them under their own profile. 

Creating a naming convention and reminding FAC10 to put everything into their `FAC10` organisation has been a dramatic improvement. `FAC9` contains 29 repos, after 16 weeks. `FAC10` already contains 30, after 5 weeks. Over the next 3 weeks, there will be at least 12 more. Over the second half of the course, many more!

Do we really want 40+ repos being added to `foundersandcoders` every 4 months? Will keeping them all in one place, really help us to pass knowledge from one cohort to another?
