### ISSUE TITLE
Description of course facilitator role

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#133]
Files detailing the various tasks & processes of the course facilitator should be recorded as me and @des-des go along so that the knowledge of this can be easily passed down to others who take on this role in future.

Stuff like:

* How to run a weekly check-in / check-out session with mentors
* How to run team retrospectives (or restorative practices, if this ever gets implemented in future: https://github.com/foundersandcoders/london-programme/issues/186#issuecomment-277465741)
* Process of contacting alumni network and updating the calendar

etc.

**Comment by bradreeder** [comment]
It might be more immediately useful for me to come up with a list of things I need to do on a weekly basis, to streamline how I approach doing things next time, and so I can more effectively organise my time...

**Comment by bradreeder** [comment]
There's the possibility that in time this will be a paid role. I want to use this issue and get enough processes in order that others could take up this job if provided a job profile. I'll use this issue to draft a job profile.

Only requirement I'd suggest currently is that the person should be an alumni, and be FACN-1 (or have had experience mentoring.) If this were a part-time role I think someone could continue developing while doing it.

**Comment by des-des** [comment]
@bradreeder @sofer cool, I think it would also be good to link this convo together with dans thoughts about what kind of team will go out to set up a new FAC (fac international)

**Comment by rebeccaradding** [comment]
@bradreeder @des-des any progress on this? Would be curious to get your reflections on the scope/responsibilities/time commitment of this role as first eight weeks come to a close soon.

**Comment by bradreeder** [comment]
@des-des I've added to this the scope of what me & @jsms90 have done in London. Please do add to this as it's important to know how this role has differed for you in a new campus.

@jsms90 Feel free to do so as well.

### Course Coordinator

As London is established, it may only need (or can afford) a part-time role. 

**Part-time role:** Suggested start of 2 days a week, £100-150 per day 

(alumni with prior experience of mentoring preferably.)

Would be good to have @des-des 's feedback on whether this role in a new school should be considered full-time.

#### Description

Essentially a course scrum-master (or facilitator). See following comments.

#### Pre-reading break (first 8 weeks)

* Co-ordinate mentor schedules & provide support where needed.
* Co-ordinate external speaker schedules.
* Collaborate with other course coordinators.
* Involvement with local pastoral care + curriculum committee.
* Facilitate / be present for weekly retrospectives (s-g-c, project demo, etc.)
* Ensure action points of student retrospectives are followed through & communicated to mentors of following weeks.
* Review upcoming week plans in light of student feedback. User-test new workshops & raise issues (if there's time lol).
* Document & maintain documentation (master-reference, school-curriculum, etc.)

#### Post-reading break (last 8 weeks)

* Involvement in planning & running of second half of curriculum. (Unsure to what extent this needs to be repeated.)
* Organise curriculum-planning (inc. involving feedback of broader community).
* Prepare for start of next Curriculum. See #167

**Comment by bradreeder** [comment]
#### Organisational needs

What value does this provide the organisation?

* Iterative improvement -- students can't iteratively improve the curriculum based on their experience alone. Iteration is important to expansion and new opportunities like #65 .
* Identification of gaps -- by being immersed in the student experience from beginning to end, this person has a unique advantage in identifying common patterns, problems, and gaps in our processes.
* Greater Consistency / communication / organisation -- having a coordinator should ensure that everyone involved is in communication, allowing greater focus on the needs of the students.

I basically see this person as responsible for trying to ensure that as an organisation our core service experiences more

**Comment by jsms90** [comment]
*3 days per week**
I would say that, on average, this has taken me a bit more than 2 days per week. And even then, I sometimes had to leave things half finished, purely due to time constraints and needing to get back to my job.

And that's without considering this as "part of the role":
> Involvement with local pastoral care + curriculum committee

(as opposed to attendance being voluntary / a personal choice). But I do agree, that the course coordinator definitely _should_ be expected to attend.

That's also without having done any of this:
> Co-ordinate external speaker schedules

which could easily be quire time consuming. Especially when it's done well.

So I would strongly suggest that the role should start at 3 days per week, instead of 2.

**Other tasks**
+ Co-ordinate code reviews from alumni - _this is easier for someone who is consistently in the space across the week, rather than the rotating cast of weekly mentors_
+ Facilitate weekly mentor stop go continues (as a separate point to the students' weekly retrospectives) - _sometimes this can't be done in person, as mentors aren't always all present on Fridays_
+ Provide feedback to the selection committee, reflecting on how anything about the selection process has had an effect on the cohort and/or the delivery of the curriculum
+ Ensure that decisions from the wider organisation are fed back to the students  
e.g. Requesting that those responsible for weeks 10-12 should present the second half of the curriculum to FAC10 after their week 8 stop go continue  
Decisions made at business meetings that may impact students (particularly necessary for those students who don't attend business meetings)

**Curriculum planning**
I would also change:
> Review upcoming week plans in light of student feedback. User-test new workshops & raise issues (if there's time lol)

and expand on 
> Organise curriculum-planning (inc. involving feedback of broader community)

to become:
**Post-reading break (last 8 weeks)**
+ Review plans for each week via PRs to the master reference
+ User-test new & altered workshops during week 15 (the curriculum planning week that will now exist)
+ Raise issues during weeks 15-16
+ Repeat after students have responded to issues, during the break between week 16 & week 1 (so that material is _ready_ before the next cohort arrives)

Note: week 15 might need to be full-time

then in **Pre-reading break (first 8 weeks)**
+ Review upcoming week plans, in light of student feedback and the cohort's progress to date. Raise issues if/when necessary.

**Comment by jsms90** [comment]
On a slightly separate point, we don't ever seem to have addressed this: https://github.com/foundersandcoders/london-programme/issues/148#issuecomment-273551113.

The course coordinator role was defined as:
> Coordinate mentor schedule, arrange talks, provide pastoral care to current students, update master-reference, collaborate with other course coordinators

and @bradreeder was saying that he considered the description of his role to be more along the lines of
> "provides curriculum oversight and strategic direction"

This was left as:
> Basically I'm unsure if what me and @des-des are doing behind the scenes is within the scope of this description. Which makes me feel that either a) the description should be updated...

But, to my knowledge, the description of the role wasn't updated (?). Neither were the roles "curriculum developer" and "course coordinator" separated, as per https://github.com/foundersandcoders/london-programme/issues/148#issuecomment-274300842

Me and @bradreeder have never had a formal conversation about how these tasks were going to get split, so please tell me if I've got any of this wrong, or missed anything @bradreeder. But I would say this has been the split:

Bradley has largely been focusing on the second half of the course, as the largest part of the "curriculum" that is still under development. He's been researching how to run this process effectively (scrum mastering), whilst continuing to oversee changes to the master reference and merging updates. He's also been present for some of the Friday retrospectives, been running the London curriculum committee meetings & handling the backlog of tasks in that repo. Have you been co-coordinating external speaker schedules, or has that mostly been the FAC10 task group? I haven't done any of it.

My involvement sort of just came about naturally, because there was a gap that needed filling. So I have largely facilitated the day-to-day, organisational side of things i.e. the "pre-reading break" tasks.

Despite how we left things in that issue, nothing was ever formally decided about splitting these two roles. But it seems to have happened organically anyway, due mine and Bradley's different interests and skillsets. And it seems to have happened very much along the lines of what Bradley was talking about here: https://github.com/foundersandcoders/london-programme/issues/148#issuecomment-274300842. 

Should we be making a distinction between "course coordinator" and "curriculum developer"? Perhaps they need to be the same person? But I think that course coordination by itself is a 2/3 day per week job. But perhaps you would have more time for the course coordination tasks during the next cohort, once the second half of the course has been more well-defined? I would be happy for this to be considered one person's role, but only if the course coordination part doesn't fall by the wayside.

**Comment by bradreeder** [comment]
@jsms90 Agreed on 3 days a week. I said 2 as I was anticipating that funds would be low for this and I would rather someone was getting paid to do some of the role than it not exist.

A large part of why me and @jsms90 ended up splitting this work is that I think doing it well is demanding, and I found balancing this with free-lancing to be an unsustainable pattern.

**Comment by bradreeder** [comment]
@jsms90 @sofer  Agreed on 3 days a week. I said 2 as I was anticipating that funds would be low for this and I would rather someone was getting paid to do some of the role than it not exist.

A large part of why me and @jsms90 ended up splitting this work is that I think doing it well is demanding, and I found balancing this with free-lancing to be an unsustainable pattern. I think whether this becomes paid needs to be discussed in advance of the next curriculum.

**Comment by markwilliamfirth** [comment]
The time commitment necessary for the role should be decided prior to remuneration - for the 3 days a week are these 7/8-hour working days or is it a certain amount of hours across the whole week? Are there fixed time periods at which the person in the role must work?

https://github.com/foundersandcoders/london-money/issues/25#issuecomment-294935990

**Comment by bradreeder** [comment]
@markwilliamfirth I think it would be easier to remunerate this by number of hours rather than days just as the periods they'd need to be available are interspersed across the week. I'd estimate 20-24 hrs based upon mine and @jsms90 's involvement with FAC10.

The primary question to me is the amount of budget the finance committee would consider giving to the role. If there's only budget for 16 hours then the role would need to be scoped to the available time.

**Comment by markwilliamfirth** [comment]
Would these 20h be every week during the year? What about weeks between cohorts joining? Is work needed to be done in between cohorts? When the cohort is in, how many of those 20h are required to be with the cohort? e.g. Monday 10-11 every week (kicking off the week?), Friday 5-6 (code reviews?) i.e. is it possible to create a timetable of hours for the role?

**Comment by jsms90** [comment]
@bradreeder
> The primary question to me is the amount of budget the finance committee would consider giving to the role. If there's only budget for 16 hours then the role would need to be scoped to the available time.

I completely agree. It's important that we don't define the role as encompasses all of the responsibilities above, if it's not possible for one person to do in the number of hours/days they are paid.

As you said
> A large part of why me and @jsms90 ended up splitting this work is that I think doing it well is demanding

If 20-24 hours is enough to do everything outlined above, then we're on the right track. If you think there's any chance you can't manage everything on that list, we should reduce the list.

I think the committee is waiting to hear a proposal for the role, rather than defining an amount of money and getting us to work from there.

**Comment by jsms90** [comment]
@markwilliamfirth 
DISCLAIMER: It's somewhat impossible to talk about the days/hours required of this role, without discussing _what_ this role is & how we're going to run things, going forward. I'm aware that some of this should be discussed....elsewhere, like by a "staff committee" if we had one...sorry about that.

I would suggest 20 hours per week during all 16 weeks. If the interim is going to be 2 weeks long, I would suggest one week of work, one week for rest.

**Weeks 1-8**
If we're going to continue the pattern that has emerged from FAC9's mentorship, I would say these were my fixed times:
+ Monday 9:30 - 10am Meeting with the mentors of the week
+ Monday 10am - 10:15/10:30 Observe overview of the week (useful)
+ Tuesday 4:30pm - 6pm Observe research day presentations (start time varies week-to-week) & mentors outlining the project
+ Friday - Facilitation / observation all day  
10 - 11 Code review
11 - 1 (anywhere in this slot, while students are responding to issues) mentor retrospective  
Afternoon: Student retrospectives
+ Saturday - reviewing week's content & merging into the `master-reference` (how much of the day depended on the prep of the mentors & the students' situation in the previous week)  
Note: I would expect that Saturday shouldn't happen / should require much less work for any future coordinators. But it's very likely that changes from mentors will still be happening as they learn more post-FAC.  
But in order for Saturdays not to happen, we would have to have much clearer expectations set for FAC10 (as mentors) about deadlines for their week's prep to be finished. I suggest that the _final_ deadline be Friday of the week before.

Other tasks to be spread throughout the week:
+ Coordination of the next week's mentor schedule & provide support where needed
+ Important: respond to the needs of these 16 people. Make sure we're not just delivering what the curriuculum says, because it says so  
Review upcoming week plans in light of student feedback. Communicate with next week's mentors about the students current progress as/when it is likely to have an effect on mentors' material.
+ Communicate the points raised in students' retrospectives with the whole FAC community & ensure these points are actioned
+ Involvement with local pastoral care + curriculum committee
+ Document & maintain documentation (master-reference, school-curriculum, etc.)
+ Coordination of alumni availability for code review

I'm undecided on whether this should be the course coordinator's responsibility, or that of the weekly mentors and/or other alumni (?)
+ Co-ordinate external speaker schedules

**Week 9**
+ Make any necessary proposals for the Curriculum Committee based on observations over weeks 1-8, stop go continues, issues & other documentation raised during the first 8 weeks
+ Convene a curriculum committee meeting at the end of the week / during week 10 

I'm sure @bradreeder can flesh out more about weeks 9+ based on what he's been doing. For starters:
**Week 9**
+ Coordinate week 10-12 mentors

**Week 12**
+ Facilitate a retrospective at the end of the 3 weeks (separate student & mentor ones again?)

**Week 14**
+ Get in touch with the mentors who created the material in the master reference, to find out how much ownership/input they want during iterative improvements. Do they want to be reviewing PRs for changes to their workshop? If the planned changes are drastic, would they prefer a new repo to be created to replace their own? etc.

**Week 15** - Facilitate curriculum planning
+ 1 full day on reviewing the overarching structure of the course together & assignment of students to each week
+ Ensure that feedback for the wider organisation is actioned e.g. issues for the Curriculum Committee
+ Provide students with guidelines on how to make iterative improvements:  
  + Ettiquette with the creator / prior collaborators on `master-reference` material
  + Gitter channel(s) for curriculum planning
  + CONTRIBUTING.md for the `master-reference` e.g. use of issues, branches, PRs, labels
  + Deadlines for their week's material to be finished
+ Point students to their own retrospectives and inform them which (if any) have been actioned by the Curriculum Committee so far, and how
+ Be present throughout the week to answer questions (?)
+ Half day on Friday for presenting the overview of the week

**Week between cohorts?**
+ Reviewing, user testing & raising issues on `master-reference` material  
NOTE: If the deadline is going to be the start of the next cohort, then mentors are highly likely to be doing plenty of work during this break. I don't think it's possible to complete _everything_ during week 15. This is likely to be an extremely time consuming week for the course coordinator.

**Comment by eliascodes** [comment]
Closing in light of https://github.com/foundersandcoders/international/issues/57#issuecomment-317686646

Also see:
* https://github.com/foundersandcoders/london-programme/blob/master/jobs/course-facilitator.md
* https://github.com/foundersandcoders/nazareth-programme/blob/master/jobs/course-facilitator.md
* Gaza written up but still TBD
