### ISSUE TITLE
15 Open Pull Requests ... Can we review/discuss/improve -> approve them before opening any more new ones?

### ISSUE THREAD

**Issue by nelsonic** [foundersandcoders/master-reference#137]
It's _fantastic_ that people are taking the time to _contribute_ improvements to this repo! 😍 
_However_ we seem to be _accumulating_ an "_inventory_" of Open/Pending Pull Requests:

![image](https://cloud.githubusercontent.com/assets/194400/23116365/1d057726-f742-11e6-8a6d-458d3e497449.png)

# Please Help Review/Merge the (_existing_) Open PRs `before` Creating `new` ones

_Also_, is there a reason why _most_ people submitting PRs are not following the Contributing Guide?
 specifically regarding their PR titles, description and/or referencing an issue where the _contents_ of the PR was discussed? as per [CONTRIBUTING.md#pull-requests > 3](https://github.com/foundersandcoders/master-reference/blob/d799a804f2a2dd3561a62de1b1becee0d1601475/CONTRIBUTING.md#pull-requests)

Keep up the great work, please clear the PR Backlog to avoid wasting effort on _Merge Conflicts_. 👍

**Comment by sohilpandya** [comment]
Agree with what's being said above @nelsonic, it's going to get overwhelming for those reviewing the PRs.

We also **need** to have a process for PRs. We should always follow the _git_ protocol. 👍

**Comment by bradreeder** [comment]
A process exists in the [contributing guidelines](https://github.com/foundersandcoders/master-reference/blob/master/CONTRIBUTING.md). I think FAC9 are just a bit flustered with the impending deadlines and are forgetting about it but I'll continue to remind them of it.

**Comment by mantagen** [comment]
Agree that it would be good to deal with open issues. I will **up my game** on this.
However I feel that the solution is to _encourage_ people to deal with open issues rather than _discourage_ or, worse, _forbid_ people from opening new issues as and when they come up.

**Comment by nelsonic** [comment]
@mantagen also good to clear out issues. so if you can start with the oldest first, go for it. 👍

**Comment by jsms90** [comment]
It was my understanding that only the people mentioned in the contributing file could merge PRs?
> The following people are available to review pull requests: @bradreeder, @des-des, @sofer, @iteles or @nelsonic.

I wouldn't suggest that you stop mentors from submitting PRs. Isn't that basically like stopping them from working on their weeks. I think it is only natural that you will get all of these PRs at once, with the current amount of curriculum planning time that has existed within the course.

I suggest that, instead of restricting people from submitting PRs, we sort out some sort of method by which PRs are prioritised?

1. For example, you could prioritise based on which week it is, if you want to prioritise week 1 > week 2 > week 3 etc (in terms of prioritising for time, _not_ for importance). In that case, reviewers/mergers could filter PRs based on the `week1-toolkit`, `week2-testing` etc labels.

2. Or you could prioritise based on files e.g. learning outcomes > resources > reserach-afternoon > project (so that FAC10 & FACN1 at least have all of the learning outcomes of each week, even if they don't have the rest of the details). In which case, it might be an idea to add these as labels for PRs? Or just get people to use `priority-2`, `priority-3` etc - but people need to know _what_ needs to be given what priority

Either way the CONTRIBUTING.md file would need to be updated accordingly, and use of these labels would need to become mandatory, in order to help reviewers.

@nelsonic @mantagen @sohilpandya  Thoughts?

**Comment by des-des** [comment]
@nelsonic Right now we have 9 pull requests with probably over 20 collaborators. To me this is very exciting.
@jsms90 can you raise an issue specifically for changes needed to the contibuting file and assign it to me!

**Comment by nelsonic** [comment]
@jsms90 ***very few*** PRs have been _assigned_ to me. (_for whatever reason..._)
Of the 9 currently open PRs zero are assigned to any of the reviewers you have listed. 😕 
![image](https://cloud.githubusercontent.com/assets/194400/23205636/8540323a-f8e2-11e6-810c-30998b0b6bf6.png)
and of the 63 merged PRs ***zero*** have been assigned to me:
https://github.com/foundersandcoders/master-reference/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anelsonic

> I typically review/comment and/or merge a PR with a couple of _hours_
(_to avoid people losing momentum/focus_)

There are PRs that are over a _month_ "old":
![image](https://cloud.githubusercontent.com/assets/194400/23204952/38b0957e-f8e0-11e6-91c2-5410029ab3ed.png)
Which can _easily_ be concluded and assigned for review. What's the hold up?

The main thing people need to realise is that their PRs won't be (_and don't need to be_) "_perfect_" `before` they can be assigned for review, the beauty of GitHub is that we can give feedback `while` people are writing, so the process can be _collaborative_.

Everything in Version Control can be _iterated_ on and improved _both_ by the previous cohorts _and_ the _current_ cohort. we should encourage people to merge PRs as soon as they've been reviewed and then get the _current_ cohort to **raise issues** when they `require` any clarification. 

@des-des I _started_ my issue description by stating that it's _fantastic_ that people are (_finally_) contributing ... it's excellent that we will _finally_ have an ***iterative*** curriculum definition (_instead of one-GitBook-per-cohort where learning is systematically lost..._) ❤️ 
I merely want to _highlight_ that there is a lot of "Work-in-Progress" that can _easily_ be concluded, and if people are short on time they should _request_ help with finishing their PRs. :shipit: 
Hope you're having a great day in Nazareth! ☀️  (_pass on our love to all!_)

**Comment by des-des** [comment]
@nelsonic I'll run through all the prs today, and give people a poke.

**Comment by jsms90** [comment]
@nelsonic Given that @bradreeder and @des-des were the ones creating the master reference, and @bradreeder was the one leading our curriculum development sessions, I think it's unsurprising that people have predominantly assigned those two. But how about we assign _everyone_ from that list from now on? That would probably ensure that PRs were merged asap :)

> The main thing people need to realise is that their PRs won't be (and don't need to be) "perfect" before they can be assigned for review, the beauty of GitHub is that we can give feedback while people are writing, so the process can be collaborative.

I know this is DWYL's workflow, but since our adherence to the contributing guidelines is already pretty lax and we're not using the labels to notify reviewers about when PRs are complete, reviewers are currently left to assume that a PR is ready for review as soon as they have been assigned. I think we would need stricter processes if we were going to raise PRs before they were ready to be merged.

To me, this just seems like a product of FAC9 only hearing about certain aspects of git & GitHub flow in the second half of the course, sometimes only during our client sprints. I don't really consider it FAC9's fault that this isn't totally natural yet. That's exactly why I'm trying to bake it into week 1 for FAC10 :+1:

**Comment by jsms90** [comment]
@des-des
> @jsms90 can you raise an issue specifically for changes needed to the contibuting file and assign it to me!

What changes would you like made? I just made suggestions. Which do you think is most likely to actually be used and therefore to be of most of help to you guys?

**Comment by des-des** [comment]
@jsms90 ok I have opened #155 for discussion.

I am generally confused by what problem this issue is trying to solve, but have created an issue to log any confusion / problems with the contribution process.

**Comment by jsms90** [comment]
@nelsonic 

There are issues open to deal with
+ what labels we use #316 
+ maintainer responsibilities #370 (including how to deal with PRs)

Happy to close this?
