### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#14]
So right now we do not have any plan in place for weeks 11-12 and beyond. Ideas:

### Front end frameworks

Many FAC graduates will start their careers as front-end developers. Teaching node allows our graduates greater breadth of knowledge and future career opportunities. Right now, there are lots of jobs asking for react+redux experience, however we do not think this is the most effective technology to build MVPs with. Students need some kind of exposure to a front-end framework and an understanding of what problems they solve.

### Bigger project
@nelsonic mentioned lack of user testing in the course. We could do a big project that involves building something _real_ and testing it with real people. I think this is the direction we should go in for week 11-12. It ties in to the idea of the students having a proper final project.

**Comment by bradreeder** [comment]
If we are going to ensure a 10% quota on student time being allocated to business development (5%) and community engagement (5%) #38 then we need to discuss how that would relate to weeks 11+. 

I don't think we can fit more than 2 hours per week into weeks 1-10, so the remainder would need to fit into weeks 11+ in the form of either more regular hours, or a week specifically set aside for community engagement.

**Comment by nelsonic** [comment]
@des-des / @bradreeder are we discussing week 11+ for the _current_ cohort or `#future` ...? (_thanks_!)

**Comment by bradreeder** [comment]
@nelsonic `#future`, no worries. 👍

**Comment by bradreeder** [comment]
F&C9 were divided over UX week, with essentially an even split in favour of keeping it and removing it. If we were to make it into week 10 it would need to be re-thought a lot, especially given it would be a 1 week slot instead of 1 and a half.

The consensus appeared to be that it's better to gradually introduce project management skills throughout the course, and then run a few preparatory workshops shortly before they begin on their client-work.

We need to think about what we will do in weeks 10+ for the next curriculum.

**Comment by bradreeder** [comment]
## Proposal

I think next year we'll be able to tighten weeks 1-10 (what’s currently 1-9) into a well-structured 8 week foundation course.

My current thought would be then to agree with @des-des that weeks 9-10 should be a final project. I’d opt that it should be on an area of the student's choosing that they'd have a chance to think about over the course/ break. We could even run our own hackathon at the start of week 9, in which students pitch their ideas, they vote on the four MVPs they want to build, and then organise into groups of four to build the prototype.

The project would be a culmination and means of integrating both the coding & project-management skills that comprise the foundation. We could incorporate the UX workshops #36 into this to give it context around being the client to their own MVP, and perhaps even get them to organise and run user-testing sessions for it. I.e. week 9 they build the prototype, week 10 they test it and re-iterate. 

That way the 8-week foundation culminates in them building their final project MVP, and the experience of them building their own MVPs organically progresses into the next part of the course where they work with clients realising their ideas.

———————————

## Rationale

We could make it a part of the application criteria that people state specific problems they want to solve using technology. Something specific, to show they’re genuinely engaged and have thought about why they’re going into technology, that could become the seed of the idea behind the final project they choose to build. 

I personally think it should be a part of our mission statement & criteria that we’re providing a free education to people with a motivation to go into technology to work on or solve real world problems, so they’re empowered to do so by our training and we have the greatest social impact as an organisation.

I want to re-think the curriculum to make sure there is from the beginning continual integration of agile, lean & project-management methodologies #21 alongside coding skills (and more in the way of getting them networking, finding their own work, involved in the business as @sofer says). Not to make the focus of the curriculum entrepreneurial, but so that the student is provided with a tool-set that applies cross-contexts whatever they choose to do — find a job, free-lance, entrepreneurial — and gives them the greatest independence.

**Comment by iteles** [comment]
Are we proposing that we drop UX altogether though? I'd suggest that that would be doing our students a disservice. UX is the kind of thing you don't realise the importance of until a little later in your career, but when you do, it's *monumental*.

**Comment by bradreeder** [comment]
@iteles Not at all, my post is in favour of keeping UX and not against. I think a large part of the complaint from the students on UX week was that they felt it was out of context being applied to a scenario with fake clients, where I wonder if it was being applied to a scenario in which they're clients making decisions on their own MVPs, that it might make more sense. More workshops could then precede them working with clients.

My feeling is that workshops on things like agile, ux, project-management need to be interspersed throughout the course rather than concentrated so that they are a continual thing being practiced & integrated into project-work, a part of their developing mindset, rather than the subject of one week at the end.

**Comment by bradreeder** [comment]
@des-des @iteles @nelsonic @sofer 

It's possible there will be a week long Easter break after week 8 https://github.com/foundersandcoders/business/issues/135. Currently this means they would come back from the break to do redis & sockets with mentors. Week 10 is still undecided.

My vote is for either:

1) Keeping redis as week 9, and doing a few days of UX workshops as a part of a 2 week final project as proposed above for weeks 10-11.
2) Dropping redis week, redistributing mentors across the other 8 weeks, and doing UX/final project as weeks 9-10.

But other suggestions her would be good. I think ideally we should pin down week 10 before curriculum planning next week, as we can't make any more structural changes once mentors have started, and we'll need to work out who among us will be mentoring week 10 to give them time to prepare.

**Comment by des-des** [comment]
@bradreeder I think this sounds good. This leaves space for some other content / optional workshops in week 10/11.

**Comment by bradreeder** [comment]
@nogainbar would be willing to mentor if week 10 involved UX.

**Comment by jsms90** [comment]
[This](https://github.com/foundersandcoders/master-reference/issues/14#issuecomment-270013472) sounds brilliant to me!

The only thing that I would change is
> being the client to their own MVP

Your rationale is sound, as it would be _so_ valuable for them to to build their own ideas, and even better to encourage them to think very seriously about building tech for good! But, then they would miss out on one of the core learning opportunities from our week 10 - managing client interaction.

So, on balance, I would probably go with building something for F&C instead i.e. the donation page, a different feature for the F&C website, an app for our meetups (see "spreadsheet/app" in https://github.com/foundersandcoders/london-programme/issues/149#issuecomment-272323781), [somewhere for students to share resources](https://github.com/foundersandcoders/resource-sharing), [somewhere better than gitter for F&C freelancers to share work opportunities and advice on finding new leads](https://github.com/foundersandcoders/tasks/issues/12#issuecomment-270995964) etc.

Maybe they could have @sofer for London and @des-des for Nazareth acting as the client on behalf of F&C? If that's not feasible, then someone else as a representative? Students would still get client interaction practice, because these are things that F&C does actually want/need built! It's just very different from having your client sitting next to you at all times because they are actually part of your dev team.

It would also enable them to give back to F&C in a very direct way, which is still doing some social good. Plus, we finally have a way of making sure that F&C projects get built :)

Dan and Eoin's expectations may not be as unrealistic as real-world clients, but you will never get that without either the pure role-playing for our cohort, or having an actual real-world client. Hopefully the design sprints that come at the end of the course should provide some practice for that? We can also still bring this to their attention during Ines' talk about client interaction and/or demos of alumni's real-world projects.

**Comment by jsms90** [comment]
# Weeks 11+

It is entirely possible that we will need _all_ of weeks 11-15 for design sprints in future: https://github.com/foundersandcoders/tasks/issues/4, so any discussion of introducing new material beyond week 10 may become pointless...

But I'm going to throw this out there anyway, because it's all still quite fluid right now.

A huge topic that came from F&C9's week 11 s-g-c (@msachi could you post the s-g-c here?) was about whether these weeks of the course should be as rigid as the week 1-10 portion of the curriculum, or whether we are losing something seriously valuable from F&C history - self-organised learning.

Many of us continued discussing this on Friday night, and the take away suggestion seemed to be:
1. Set expectations - ensure that there is a well-defined, clearly explained switch between the curriculum portion of the course and the style of the subsequent weeks
2. Present students with a wide variety of extra topics, with a clear explanation of _why_ they might want to explore these, so that they can make an informed decision. After all, students should still be benefiting from the experience of the people who have come before them. Example ideas:
  - [functional programming](https://github.com/foundersandcoders/master-reference/tree/week-11-functional-porgramming-redux-todo-UX-testing-field-trip/coursebook/week-11) - arguably should go earlier in the course - see: https://github.com/foundersandcoders/master-reference/issues/62
  - [redux](https://github.com/foundersandcoders/master-reference/tree/week-11-functional-porgramming-redux-todo-UX-testing-field-trip/coursebook/week-11)
  - [react](https://foundersandcoders.gitbooks.io/fac8/content/week9/)
  - elm
  - progressive web apps
  - [data visualisation tools](https://github.com/foundersandcoders/master-reference/issues/15)
  - build tools (e.g. webpack, babel, gulp)
3. Encourage them to self-organise and choose what they want to work on. Mentors can help by:
  - pointing them to the best resources that we are aware o f /have made
  - asking alumni with any relevant experience to offer advice and demo their projects
  - reinforce the idea of _documenting their learning experience_ so that future cohorts (& the rest of the world) can benefit from their learning

**Comment by msachi** [comment]
Week 11 s/g/c notes as requested ☺️ 

** Stop ** 
- Learning from videos as the main resource (prefer workshops)
Discussing structure of current week on GitHub (do it in person instead)
- Confusing combination of ‘we have a plan for you’ and ‘you should self-organise’ (communicate clearly which is the case)
- Half-finishing material e.g. Frisby’s functional programming book (unless it is communicated that we are only planning to go through chapters 1-4 for a reason)
- Read / watch on your own without giving any direction on how much to do (however — context switching, feeling the pressure, uncertainty of learning are all important skills to learn)
- This type of learning is awesome but need to be clear if it’s part of the formal course (it’s being treated as optional, e.g. people not coming in some days)
- Miscommunication about the ‘mental shift’ from structured work (weeks 1-10) to unstructured work (week 11 on)

** Go **
- Clear learning objectives communicated at beginning of week
- Ability for us to start at 10 even if mentor not here
- Material which makes maximum use of being in a group (or allow people to work from home)
- Put user research / testing into a context i.e. learning objectives of the activity
- Tell us plans in advance (like GitBook for weeks 1-10)
- Heating

** Continue **
- Game of life
- Jobs talk for all future cohorts
- Redux Q&A session, Andrew’s demo
- Some solo project time, but still working alongside each other
- CSS talk from Tableflip
- Intro to FP really useful before Redux

**Comment by des-des** [comment]
@bradreeder I like your proposal.

So my thoughts on what can be tacked on to this. Students can also choose a new technology to learn + organise into 2/4 person teams. I think this will help more generally since there is pressure for various technologies such as elm, react, express, d3 and more. Giving students a choice might allow students to focus on what is best for them.

**Comment by bradreeder** [comment]
@des-des I'm happy with what you're suggesting -- @sofiapoh also proposed over a spot of tea today that we could add a day's workshop on deployment in the second week so they get to deploy the project as well (we cover heroku, but deployment is a gap really.)

I know we discussed this briefly, but in light of what you're saying what are your feelings on redis becoming one of the optional technologies students could explore rather than a mandatory week? (websockets could always be taught elsewhere in the curriculum as it's not strictly tied to redis?).

Main reasons:

1) I think 8 weeks is a more round number for the core part of the curriculum we should aim for than 9. That leaves 9-10 for project, and gives 11-12 space for curriculum-planning & advanced material like in @nelsonic 's proposals.
2) I think having the week break positioned at the end of the core part and before the final project is ideal. That way there's a sense of closure for students and they can reflect on what they want to do for the project over the break. We have to do the break after week 8 for FAC10, due to Easter, and I find the idea of coming back from the break to do another taught week before the project out of place?
3) People's tendencies are to keep adding on weeks, when realistically student's can only integrate so much in a short span of time. I think it's better to aim to be compact with less time than try to do too much.
4) Of all the things we could cover for an extra optional week is redis really that fundamental? What about web standards, history of the web, design patterns & architecture, front-end framework, deployment? etc etc. I do admit, I don't understand why redis + sockets was chosen, as I think if students have learned postgreSQL it will be easy enough for them to pick up redis on their own? I don't remember it being that hard.

**Comment by des-des** [comment]
@bradreeder :heart: 

I can see what you are saying about redis and am happy to concede there.

Another thought is that we push the final project out to three weeks, with week three as a post testing mini-sprint?. We could add a requirement that the students build a proper readme, like either you contribute to a dwyl readme on the subject or if one does not exist, build your own.. Not sure, it might be a good way of trailing new technologies that may move into the curriculum. Another thing that I have not mentions are PWAs.

**Comment by bradreeder** [comment]
@des-des If you're okay with this, are you happy for me to propose the change in outline to FAC9 on Thursday morning for 9-10 as final project until further notice on 11+? I'm personally happy with 3 weeks but it might require further discussion as it overlaps with the currently proposed plans for week 11 #63 

Discussion can continue here until then if anyone has an issue with this.

**Comment by des-des** [comment]
@bradreeder I am going to try build these thoughts into a solid proposal by tonight!

**Comment by jsms90** [comment]
@des-des This is getting quite complicated, as we're sort of discussing lots of things in the same thread. Are you building a proposal for weeks 9-10?

We also need one for weeks 11-12. Depending on the feedback that you get on Thursday morning, we should probably close this issue and start two separate ones for discussions on the separate weeks / sets of weeks?

**Comment by des-des** [comment]
@jsms90 @bradreeder .

I would propose this issue get renamed final project.

That was always my intent for this discussion and broadly captures lots of the discussion. Content for these weeks has now gone into master reference, but I feel there is lots of value in putting together my final proposal on the subject, as I have been thinking about this for a while and would like to get my thoughts down in a coherent way.

**Comment by jsms90** [comment]
@des-des Sounds good to me. As I understand it, the distinction lies between the two aspects of your original post:
- frontend frameworks could belong in [this version of weeks 11-12](https://github.com/foundersandcoders/master-reference/issues/14#issuecomment-272724173)
- the "Bigger project" - now "final project", feel much closer to F&C9's experience of UX/UI week and it sounds like that has become the proposal for weeks 9-10?

**Comment by des-des** [comment]
@jsms90 @bradreeder I have something together. Is it possible that we could all three skype tomorrow / today? @jsms90 I realise I have also missed some of your points in the thread.

**Comment by bradreeder** [comment]
@des-des sounds good, me and @jsms90 are both in the office now and imagine we will be until 6ish. I think we'll both be in tomorrow as well.

**Comment by des-des** [comment]
@bradreeder Free until or after 6. Free now for one hour and a bit. Also maybe free later.

**Comment by bradreeder** [comment]
@des-des cool cool. There's a downstairs talk happening right now so will check back when it's finished before 6.

**Comment by sofer** [comment]
I find myself in strong agreement with a lot of what has been said here (hence the rash of 👍's). 

Let me reiterate some of the things I agree most strongly with:
- splitting the course into two halves with a break after Week 8;
- a distinction between a core curriculum in the first half and a peer-led curriculum in the second half, where the recent graduates and current students have a greater input on the content;
- a week or two (or possibly three, as suggested by @des-des), where students work on either optional topics or their chosen projects;
- embedding of UX/UI and user testing into the design sprints.

On @jsms90's point about it becoming *"entirely possible that we will need all of weeks 11-15 for design sprints in future..."*, I agree that longer term that might be the case, although I suspect that if this happens, it will happen gradually, so it is still worth planning for FAC10. I probably need to post something about my plans for the design sprints elsewhere.

Incidentally, I don't think you can call something a *final* project if it happens halfway through the course ;-)

**Comment by des-des** [comment]
@bradreeder check gitter (lets stop spamming)

**Comment by des-des** [comment]
@bradreeder @jsms90 super rough atm but lets put it together here: https://hackpad.com/-Final-Project-Proposal-ORrmQ2jqeN2

**Comment by des-des** [comment]
@jsms90 @bradreeder okay I have gone over the proposal, I think it should be almost ready to go now.

**Comment by bradreeder** [comment]
@des-des Will review today, thanks Eoin.

**Comment by nelsonic** [comment]
@des-des your _HackPad_ notes for the Final Project is looking really promising. 😍 
(_didn't know we were still using HackPads..._)
@bradreeder did you get a chance to look at: [/coursebook/week-12/project.md#how](https://github.com/foundersandcoders/master-reference/blob/8de1de2e98b5e19b398932b6ae29d1baa613828c/coursebook/week-12/project.md#how) ? 💭 
It probably needs some re-work to incorporate all the ideas/insight in the HackPad ... 📝 
or feel free to `delete` it and start over. 👍

**Comment by bradreeder** [comment]
@nelsonic I noticed and was planning on reviewing all the week 9+ material together some time this afternoon. ❤️

**Comment by jsms90** [comment]
@des-des we updated the hackpad, if you wanna take a look and see what you think?

**Comment by des-des** [comment]
delivered
