### ISSUE TITLE
Clarify contribution process

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#155]
Okay so there seems to be a fair amount of confusion around the contributing process here.

Our contributing file is here: https://github.com/foundersandcoders/master-reference/blob/master/CONTRIBUTING.md.

As I am finding it quite difficult to keep track of where confusion is happening I want to keep this issue open to document where people are confused and where people are going wrong. Then we can take steps to make the contribution guidlines more clear

**Comment by des-des** [comment]
@bradreeder my main question here is around the way people are merging all there work into one super-pull.

To me this seems backwards. Would you be opposed to changing this?

**Comment by bradreeder** [comment]
@des-des FAC9 are doing that as I advised them to during curriculum-planning. Main reasoning being as I thought at the time it might be easier for us to track progress on weeks if all discussions were kept to a single issue/ PR. And also to decrease the number of open issues/ prs. 

I'm open to suggestions on how to improve the process, and am sorry if this turned out to be the wrong call this time around.

**Comment by emilyb7** [comment]
@des-des @bradreeder

Some suggestions to help take the pain out of the contributing workflow:
- branch restrictions to reduce the likelihood of accidentally committing stuff to master (https://help.github.com/articles/enabling-branch-restrictions/)
- enforce commit messages https://gitmagic.io/ (this is free at the moment, although not sure about long-term cost, maybe there's another way of automating this anyway)

**Comment by jsms90** [comment]
## Multiple PRs per week
@bradreeder I completely misunderstood that instruction of yours - you can see that I've been making lots of little pulls, because bite-sized pieces are easier to merge. In the same way as it is with code, having lots of smaller PRs about separate areas of your week, won't then hold up merging the rest of it.

I thought your instructions were simply about raising all of our pull requests against just one _issue_ (rather than raising loads of mini-issues about your week). That's what I've been doing, and personally, I think that's worked really well for week 1's mentors. @njsfield @Cleop would you agree?

I also thought that was why the `week-toolkit`, `week-node`, etc labels were introduced. Although not stated in the contributing file, I assumed they were created as a way for you guys to filter PRs (see suggestion 1 in https://github.com/foundersandcoders/master-reference/issues/137#issuecomment-281394141 )

This may not be the best use of labels - see suggestion 2 in https://github.com/foundersandcoders/master-reference/issues/137#issuecomment-281394141 

## _Who_ to assign our PRs to
Re: @nelsonic 's message https://github.com/foundersandcoders/master-reference/issues/137#issuecomment-281618653
It is not clear (at least to me), who we are supposed to be setting as reviewers/assignees of our PRs.
+ The contributing.md suggests any one of 5 people. I had assumed that assigning @des-des or @bradreeder was the most sensible, since they are the ones who made the master-reference, and it is considered a large part of their roles.
  + Especially @bradreeder, as the curriculum developer / course coordinator who has been running all of our curriculum days, and knows everything about the feedback we have given during s-g-cs, and the curriculum development days.

1. Perhaps it would be more efficient for us to assign particular types of PR to particular individuals?
2. Or just assign _everyone_ on that list, so that PRs get merged as soon as any of these people are free?
3. Or make everyone on that list a _reviewer_ for every PR - so we have more chances for problems to be picked up on. BUT only @des-des and @bradreeder as _assignees_, so that there is someone that is actually across everything about the current state of the repo?

**Comment by jsms90** [comment]
@emilyb7 I can see this being problematic:
> branch restrictions to reduce the likelihood of accidentally committing stuff to master (https://help.github.com/articles/enabling-branch-restrictions/)

This might help if the mentors for each week were working on one branch e.g. a branch called `week-toolkit` (like the labels) - then restrictions would be meaningful. But:
+ if one/more mentors became unavailable for whatever reason, it would be easier if someone else were able to step in, without restrictions having to be lifted - this just makes collaboration more difficult
+ this would still result in the problem of having a monolithic PR, once that branch was finally ready to be merged with master - this might not be a problem in future, if curriculum planning could be completely finished _during_ course time, but we're far from that atm

**Comment by emilyb7** [comment]
@jsms90 in the event that none of the 5 people permitted to merge to master are available, it wouldn't be difficult to life the restrictions

I'm aware that this isn't a solution to the main problem raised in this issue, it's just something related that I think would be sensible

**Comment by des-des** [comment]
@bradreeder So to be clear, you are keen to stick with the advise you gave around pull requests (I would rather change it so that people contributed in a similar way @jsms90)

@emilyb7 Yeah I think we should prob have branch restrictions, but would not prioritise spending time on that discussion.. Gitmagic looks cool!

**Comment by bradreeder** [comment]
@des-des I'm not keen to stick with what I advised I just wanted to make it transparent why FAC9 have been working that way. 👍

**Comment by bradreeder** [comment]
@des-des I only raised it to be transparent on why FAC9 have been working that way. 👍

I think keeping to a single issue, and committing their plans against a single issue, for each week's discussions has been helpful as it's easier for everyone in the organisation to track what's been discussed and join in the dialogue. 

We also need to think of these issues as an archive. If people on their weeks keep updating their plans through loads of issues, then they need to assign their week's label to the issue (and the FAC10 label) to the issue so that we're able to archive what decisions were made on FAC10 Week-1, FAC12 week-6, etc etc. A single issue per week is simpler in my opinion.

I think it was a mistake for me to advise groups to push their plans in a single PR. My preference is single issue/ multiple PRs (for curriculum planning) at the moment.

**Comment by jsms90** [comment]
@des-des @bradreeder Sounds like we're all agreed on single issue, multiple PRs?

Now we just need to choose a way to enact PRs that helps with prioritisation and individuals' workload :+1: 

@emilyb7 OHHH you meant just for the `master` branch? yeah cool then :grin:

**Comment by bradreeder** [comment]
Is this issue resolved by #162  ?

**Comment by des-des** [comment]
@bradreeder I think there is more to be done here..

**Comment by jsms90** [comment]
+ Mentors are now raising granular issues & submitting separate PRs
+ Contributing guide has been updated to specify this
+ Separate issues have been opened to deal with assigning PRs for review

@des-des happy to close?
