### ISSUE TITLE
Connection between current running cohorts

### ISSUE THREAD

**Issue by esraajb** [foundersandcoders/master-reference#168]
Hi FACTERS

Im thinking about opening new gitter channel for the current running cohorts(LONDON and NAZ at the time ) to share resources and more.

we can use the -local- gitter channels for the daily workflow.

I think it can be beneficial to open this kind of channel for each running cohorts in the future also as it will make the community stronger.

**Comment by bradreeder** [comment]
Do you mean for the students @esraajb ? The mentors already share a curriculum-planning channel.

**Comment by esraajb** [comment]
for the students

**Comment by bradreeder** [comment]
I wonder if the students are likely to check multiple channels, and whether the fact we're running a day apart from each other might effect things, but I see no harm in trying it out in principle. 👍

**Comment by esraajb** [comment]
just an examlpe :

"I've created a repo which has notes from @sohilpandya's Git workflow and lounge workout session 
Let me know if we can improve this. https://github.com/PiotrBerebecki/git-workflow-workshop-for-two" @pioter

this  should be published at this kind of channel

**Comment by jsms90** [comment]
@esraajb Maintainers of the curriculum have a responsibility to ensure that all curriculum planning gets done on github, where it is publicly documented.

See [this guide](https://opensource.guide/building-community/) to building a community through an open source project
> Writing things down means more than just technical documentation. Any time you feel the urge to write something down or privately discuss your project, ask yourself whether you can make it public.
>
> For meetings, consider publishing your notes or takeaways in a relevant issue. The feedback you’ll get from this level of transparency may surprise you.

I still see one good use case for a campus-specific planning channel:
+ a space for mentors to communicate about things like changes to their [division of responsibilities](https://github.com/foundersandcoders/master-reference/blob/ea6b239a3c7ae4f6556fbeeefb21c63f51a58e2e/curriculum-planning/mentor-assignment-list.md), lateness, etc

Arguably that may not need to be private...?

I also see a current need for a joint channel. Primarily because Nazareth is extremely reliant on London at the moment, particularly since it is without a Course Facilitator to provide consistency throughout the weeks. So I have created a `summer-cohort-planning` channel.

@eliascodes this currently contains only London and Nazareth. Would it be useful for you to add Gaza? Or do you think this is less necessary for your campus?
