### ISSUE TITLE
Add Queers Gitter channel 

### ISSUE THREAD

**Issue by msmichellegar** [foundersandcoders/master-reference#182]
We do not currently list the Queers Gitter channel in the [reference file](https://github.com/foundersandcoders/master-reference/blob/master/gitter-channels.md). It would be nice to do that :rainbow_flag:

**Comment by iteles** [comment]
@msmichellegar Someone actually raised a good point to me the other day: we came down like a ton of bricks on the creation of a men-only F&C gitter channel.

It would be good to document in this issue how having a Queers gitter channel is any more warranted than a men-only or women-only or anything-only channel 👍

**Comment by msmichellegar** [comment]
@iteles Someone raised an issue specifically about the Queers Gitter channel?

A queer space is wildly different to a male-only space, and far more warranted. One is a marginalised group, the other is not.

There is no history of systemic discrimination against men. Don't think I need to tell you that historically, the whole universe has been a giant boys club -- especially in tech. The creation of a male-only channel just reinforces this sexist culture, and provides no benefit to the wider community.

Like other marginalised groups, LGBTQ folk experience widespread discrimination. Even in a progressive community, we can experience subtle micro-aggressions, or outright exclusion. An autonomous channel is intended as a safer space: where people can be out without fear, not be judged, network, share experiences, discuss queer-specific events and issues, and be in solidarity with each other. Sure it's nice to have the support of people who aren't queer, but it's also important to feel safe, and generally not feel like a zoo exhibit.

If Founders and Coders wants to be a diverse community, we need to let underrepresented groups know it's safe here and encourage networks. I believe autonomous spaces are an important part of that, and can be an excellent tool for leading diversity efforts. I'm in favour of us establishing an exclusive space for any underrepresented group who wants and would use one: women, people of colour, queers.

Here is some further reading for anyone curious:
* [3 Reasons We Still Need LGBTQ Safe Spaces & Why It's Important To Respect Them](https://www.bustle.com/articles/143343-3-reasons-we-still-need-lgbtq-safe-spaces-why-its-important-to-respect-them)
* [LGBT Safe Spaces And How To Be A Good Ally](https://www.theodysseyonline.com/lgbt-safe-spaces-good-ally)
* [‘A Little More Inclusive And A Little Less S Club’ - The Importance Of LGBT Safe Spaces](http://www.huffingtonpost.co.uk/matt-horwood/a-little-more-inclusive-a_b_12455878.html)

**Comment by jsms90** [comment]
Ordinarily I would be 100% against having a channel of any kind, which is private. Even for minority groups.

@msmichellegar has a point:
> There is no history of systemic discrimination against men

The word here is **systemic**. The reason why a female-only, or LGBT-only group is considered a "safe space", where a male-only group is considered "a boys club", is down to the _systemic_ nature of the discrimination that minority groups experience, often on a day-to-day basis. The way that this can wear a person down over time, affect their self-worth, and infect every aspect of their lives.. is very difficult to adequately express.

Having said all of that, I am generally against the existence of private channels, **and _thoroughly_ against any form of exclusivity**.

This is because exclusivity generally causes more harm than good _for everyone involved_. It encourages polarisation and feelings of otherness, and I don't believe that anyone's problems are dealt with most effectively through isolation from one another. To be a cohesive community, transparency and openness are really really important defaults. Even when the need for a safe space is evident! ...In fact, _especially_ then.

So I would be strongly against private and/or exclusive groups based on most diversity issues, such as race or gender. This is true _regardless_ of whether the group is female-only or male-only.

**Comment by jsms90** [comment]
BUT

There is one distinct difference in this situation. Being LGBT, it is often very dangerous for you to be found out.

Most of the LGBT people that I know, who are from this country, have _not_ had a good coming out experience. Many people's families kicked them out of the house for a time when they were young, at the very least. Some have been entirely disowned. Most who have come out, whose families can't handle it, just have to figure out how much of their lives they can speak about openly. Some only began having a hard time when they found a partner. Others are still in the closet well into their adulthood.

When we start talking about friends from other countries, the danger ramps up to a completely different level that I won't even go into. We need to be mindful of this. This is not only because we are moving beyond London, but

It is usually difficult or impossible to hide your gender or your race from those who may discriminate against you. Whereas LGBT people can often live under the radar. Aside from that, racial discrimination doesn't (usually) come from your family. For LGBT people, anonymity is often the only thing separating you from physical violence or ostracism from your own family.

**Comment by tbtommyb** [comment]
I'm a bit surprised that the difference between a male-only and queer-only group needs to be documented, to be honest.

If and when men become persecuted and discriminated against for being male I will also support their request to add a link to a male-only Gitter channel.

I don't see any way in which the existence of this channel can be considered harmful to non-members and if so then why not advertise it?

**Comment by msmichellegar** [comment]
Yes yes @tbtommyb 👍 

Definitely disagree about this being the *only* appropriate circumstance in which to have an autonomous channel @jsms90, but don't want to derail this issue which is specific to the queer group. Perhaps we can revisit when/if that becomes an issue.

**Comment by iteles** [comment]
@tbtommyb I'm with you. I also find the amount of times I'm attached for running women/non-binary only events surprising because the need for safe havens is so obvious to me. 
But the truth is it isn't obvious to everyone so we should have somewhere we can point to with our reasoning when asked, I think this thread has done a great job of this :+1:

**Comment by iteles** [comment]
@msmichellegar PR merged in (thanks @des-des) :tada: Please feel free to close this issue 👍
