### ISSUE TITLE
Add back team code walk-through session on Friday 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#195]
People not understanding the code base may be an issue. As suggested by @sohilpandya, Should we add back the hour of teams walking through their code before the presentations, so that they all understand all the code?

**Comment by bradreeder** [comment]
@sofer I have no objections but there's no time for it in the afternoon and in the morning they currently review other projects for an hour and then have two hours to respond to issues.

Are we suggesting reducing responding to issues time to an hour? I wonder if it would be better to incorporate periods like this into project time? If they're pair programming and reviewing the other pairs code then there should be opportunities before Friday for teams to cover the code base?

**Comment by sofer** [comment]
Currently we have:
> 14:00 - 15:00 -- Group s-g-c
> 15:00 - 16:20 -- Presentations (20 mins per group)
> 16:20 - 17:00 -- Team s-g-c

We might be able to carve out a bit of time from the other activities. So, perhaps we could have something like:

> 13:00 - 13:50 -- Lunch and posting s-g-c issues on whiteboard
> 13:50 - 14:00 -- Re-arrange the furniture to create a circle
> 14:00 - 14:45 -- Group s-g-c (60 mins --> 45 mins)
> 14:45 - 15:50 -- Team code walk-through (45 mins)
> 15:30 - 16:30 -- Presentations (20 mins --> 15 mins per group)
> 16:30 - 17:00 -- Team s-g-c (40 mins --> 30 mins)

This would create an extra 45-min slot by reducing all other activities by 25%

I get that students *should* be incorporating this activity into project time, it's just that some are better at this than others. The idea of an explicit time for it just before the presentations was well received in the group yesterday.

**Comment by jsms90** [comment]
@sofer I suggest that we keep 12:40-13:00 as the dedicated slot for presentation planning https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/week-schedule.md
When students aren't reminded of this, it shows during presentations.

As for the group s-g-c: last week, only 2 points were added to the board over lunch, and tbh they should be allowed to go outside and have a complete break if they want.

I suggest that we do continue with what ended up happening last week - still put the board up before lunch, so that people can add stuff if they wish. But start things off at 2pm by having the whole group _stand_ around the board together (it helps if the chairs aren't arranged in a circle yet - put the tables away before lunch, but don't create the circle).

Walking through the code could be shorter than 45 mins. I :heart: including this!! But if your team has been doing this effectively throughout the project, 45 mins is quite long.

I wouldn't advise making the presentations shorter. We ask them to go through quite a lot in this time, and it's hard to share 15 mins between 4 people.

**Comment by sofer** [comment]
@jsms90 so something like?

14:00 - 14:50 -- Group s-g-c (60 mins --> 50 mins)
14:50 - 15:10 -- Team code walk-through (20 mins)
15:10 - 16:30 -- Presentations (20 mins per group)
16:30 - 17:00 -- Team s-g-c (40 mins --> 30 mins)

(with a possible swap of the last two items, see #196)

**Comment by zurda** [comment]
Is this something we're planning to add, or is this outdated? Happy to help with a PR if needed @sofer

**Comment by sofer** [comment]
@zurda the point that @bradreeder originally raised about lack of time in the afternoon still holds. However, the timetable now allows for two hours before lunch to respond to issues *"and plan presentations"*, which would be the appropriate time to do a team code walk-through. Closing.
