### ISSUE TITLE
Design patterns and architecture

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#22]
A topic that has come up in both #10 and #18 now (as a high priority issue) is the absence of design patterns like MVC and architecture in the curriculum.

It was suggested in FAC9's feedback that it could just be something we return to as a topic in talks throughout the course but I'm unsure what this would look like. If anyone has any suggestions for the best way to include these topics in the curriculum feel free to discuss.

**Comment by eliascodes** [comment]
I'm interested in helping this become a thing. 

Talks and workshops are both quite possible. I had actually been thinking specifically about re-writing the [reputation builder](https://github.com/eliascodes/Reputation-Builder) workshop to make it more about designing (and then TDDing!) a small client-side app around a some simple patterns (module pattern, DI, and such). The `XMLHttpRequest` part of it would then be incidental, but actually a good way to reinforce what they would by then have already been introduced to.

I’ve also been thinking about a morning challenge to design a REST interface for a given set of resources. I think it’s a bit too light for a workshop. Should hopefully reduce the number of `/getCertainKindOfThing` routes we see.

If I have any other ideas I’ll put them here.

**Comment by bradreeder** [comment]
@eliascodes I've been thinking of proposing that an alumni could volunteer to act as a reviewer for a week of the curriculum, and a substitute in the scenario that week becomes under-manned. If you're interested in working on week 3 let me know if this would interest you. If you're able to work on the workshop, that sounds great either way.

**Comment by bradreeder** [comment]
Hapi templates project for week 6 is basically undefined at the moment. I wonder, given that one of the focus's of the weeks is views, whether we can go more into architecture then and get them to implement a basic MVC, or at least view-controller, architecture.

If you went into the module pattern in week 3, week 4 with node would likely be a good point to reinforce that knowledge too given they then have access to the `module.exports` and `require` syntax.

**Comment by eliascodes** [comment]
@bradreeder 

So I had a bash at this [design-y workshop](https://github.com/eliascodes/workshop-client-side-design), would appreciate any feedback from whoever is interested. Basically I want to know if it's actually what people wanted. I wrote it with week 3 in mind, but I'm not actually sure.

As far as week 6, sounds like a decent idea. Can offer advice, but possibly won't have time to make a workshop on it.

**Comment by eliascodes** [comment]
Having reflected a little on the workshop (now in foundersandcoders/workshop-client-side-design), I think I went a little over the top. I feel as though I neglected the fact that not everyone comes onto the course wanting to be a software developer, and that that's totally legitimate. As a result it may have alienated some people 😖 

The content I had intended for that workshop is possibly more appropriate for the second half of the course, either as an elective workshop for those interested, or for the whole cohort, once they're more comfortable thinking at a higher level of abstraction.

There is still a need to introduce some software design thinking in the first half of the course though, and I suspect week 3 is still a good place for it, given it's the first time they'll need to write something approaching reasonably complex on the course, incorporating DOM manipulation, asynchronous code, object/array manipulation, etc.

My suggestion is to have a shorter workshop/exercise introducing "the elements of software design in JavaScript", which explicitly covers the following:
* Functions as first-class objects (needed for understanding later abstractions)
* Closures (this is consistently a point of confusion)
* Procedural abstraction (i.e. generic functions for XHR requests, updating DOM, etc.)
* Async control flow (e.g. recaps of waterfall/parallel if already covered)

This would be done through simple examples, and possibly in a manner similar to [this workshop](https://github.com/ronanyeah/xhr-wrapper-workshop) by @ronanyeah. That list is almost certainly enough for that point in the course.

I would still like FAC to have a design/architecture resource available to it so that we can choose to offer it later in the course. I will continue to iterate foundersandcoders/workshop-client-side-design with anyone who is interested.

**Comment by eliascodes** [comment]
We have [ws-software-design](https://github.com/foundersandcoders/ws-software-design) and [Workshop-Software-Architecture-Design](https://github.com/foundersandcoders/Workshop-Software-Architecture-Design), neither of which are perfect, but enough to close this IMO.
