### ISSUE TITLE
Project pitching and team selection for Week 10 needs to happen before the break

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#229]
If teams have not been selected and projects decided on, there is no opportunity during reading week for each team to make a collective decision on what tech stack they are going to research and use (or indeed if they want to make a collective decision to rest up for the week and not do anything new at all).

**Comment by jsms90** [comment]
Personally, I think that if we do this, we are sending a clear message that reading week is about learning something for the second half. I don't agree with sending that message. I think we are in danger of forgetting how intense the first 8 weeks truly are!

Let's dial it back and ask ourselves, why do we give students a reading week at all? What is its purpose? I believe this should be about giving students a much needed break. If we're going to indicate anything to them about how else their time would be best spent, I think it should be about consolidating the first 8 weeks, _regardless_ of how intense they have found it. They may choose to learn something new, but this is about _what messages we are sending_.

If we then feel like the second half should offer an opportunity to learn something new (that's a topic for a separate discussion), I feel strongly about that _staying_ in the second half.

If we think that students should be spending this week researching a tech stack (one of the current learning outcomes of weeks 10-12), then I'm not sure what value a reading week is adding.

**Comment by bradreeder** [comment]
The main issue with pitching on the Monday they come back is user-testing. If you pitch on Monday and are expected to user-test on Friday there isn't enough time to guarantee they will be able to test with their target audience, so most will end up testing with people from FAC / dwyl. 

If we want students to see the practical value of UX I think students need the opportunity to work with real users, otherwise they only have an abstract understanding.

If they pitch before going on the break, there's more time for them to organise user-testing on fixed dates in advance, and potentially to do some user research (depending on level of enthusiasm for the project). It's nice to do exercises like user personas so students at least think of who they're designing for, but they're a bit hollow if they're purely fictitious, never verified, and not based upon any research.

**Comment by jsms90** [comment]
> there isn't enough time to guarantee they will be able to test with their target audience

I completely disagree. They could also have spent their reading week looking for an appropriate test audience. Arguably, you probably _should_ do this before you pitch your idea to anyone. And you _definitely_ should do some user research first. Absolutely none of what you're suggesting needs to wait until after a pitch. In fact, students will proabably be more invested in their pitches if they've actually gone away and thought about it to the degree of doing some user research. :tada: 

In which case, what _we_ could do, is provide them with some useful material on how to conduct user research (as opposed to testing). We could point them to that, as well as the tech stack advice, before sending them on their break.

Besides that, who says that you _have_ to have a predefined set of people set up for your user testing? I had FACN1 go onto the streets of Nazareth with 1 day's notice. That's still more valuable than doing it with FAC/DWYL.

**Comment by zurda** [comment]
I know for FAC-15 we've pitched before reading week, which made sense to me at the time (we made some arrangements for testing during reading week). 
Is this currently scheduled differently in other programs, @shiryz , @m4v15 , @astroash ? 
(and if it's the same for all programs, should this issue be closed?)

**Comment by sofer** [comment]
@zurda I can also confirm that FAC16 project selection is happening this week, Week 8. Closing.
