### ISSUE TITLE
permission to sort out issue backlog

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#241]
I am not 100% sure how to contribute to the curriculum in a way that will truly be actionable.

 I have quite a few issues that I would like to raise, based on my observations of FAC10 & FACN1's classroms,  _before_ FAC10's curriculum planning. (The `london-curriculum` & `nazareth-curriculum` repos don't feel like a useful way to do that.)

But I'm wary of doing so, because the current backlog in this repo is already large and unweildly. It is diffcicult to know when an issue has reached a conclusion, or how to action  #it.

I'm _very_ keen to make sure that everyone i.e. current cohorts, as well as alumni (not just me :sweat_smile:) are able to contribute their observations, so that we can arrive at solutions together & come up with a contributing guide that makes those suggestions actionable.

**First step**
@bradreeder @des-des Thoughts on allowing me to clean up the backlog, like I have done for `london-programme` https://github.com/foundersandcoders/london-programme/issues/227

(**Maybe after that** put in place a stronger contributing guide?)

**Comment by bradreeder** [comment]
I'm happy to work on this with you @jsms90 , particularly the issue of contributing guidelines and how we make issues actionable (and how we decide at what point they are actionable.)

## Current

That was the original impetus behind having a curriculum committee. They could convert issues into proposals, modify them by consensus, and action them. Any proposals that needed to be approved by the students would then be discussed with them during planning. This hasn't worked as no one in the committee has been active. 

## Suggestion

Personally I'm moving more to the position that all curriculum planning should be done with the current students, and that any alumni who feel invested in the process or want to be involved should be involved, so that the feedback of past cohorts is included and decisions reflect a broader consensus.

One thing I'd note is that a lot of the open issues are threads that were opened from FAC9's curriculum-planning. We will be doing the first day of curriculum planning with FAC10 on Monday, where we will similarly be identifying patterns in their feedback and converting them into issues (or appending them to existing issues).

At the end of the day I want students to identify issues they've created or issues in the backlog they care about, and come up with proposals (in the style of a business meeting proposal) to open in `london-curriculum`. Then on the first day of week 15 we'll have a business meeting together in which we'll go through them, modify them, and action them. Alumni & curriculum committee will be made aware of it in advance so they can attend or come up with their own proposals.

I'd suggest holding off clearing the backlog until then @jsms90 if you agree?

**Comment by jsms90** [comment]
Sure thing. I think I'll leave this to you guys. Seems like you have a plan
