### ISSUE TITLE
Teaching HTML/CSS

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#25]
It's clear from the feedback in #10 and #18 that css/sass/less is one of the things students feel is not covered well enough in the course. There's confusion as to the best ways to solve CSS problems.

This could be mitigated to some extent if we had clear resources students could consult on CSS best practices throughout their project and client work, that could be introduced early in the course. If good ones already exist on the web feel free to link here, otherwise open for discussion.

@harrygfox @msmichellegar @heatherlauren @njsfield resident masters, any thoughts?

**Comment by harrygfox** [comment]
I my opinion you can't call yourself a full stack developer if you can't code front-end. Front-end work suffers from a lack of credibility / validity in out circles. "HTML, CSS, markdown." is one of the pre-requisites for joining founders and coders.... before we get to the really difficult important stuff, right? I wonder then, why these full-stack developers can't code a remotely maintainable css file. 

It sounds to me like there's FINALLY an appetite to take it more seriously. So let's not continue the trend by compiling resources that only the impassioned few will regards. 

Instead:
### Let's _Teach_ HTML & CSS

**Comment by njsfield** [comment]
If no dedicated week to teaching HTML & CSS is in place, one solution to providing more resources that can be practically used is by adding additional helpful CSS resources related to the weekly projects. So perhaps when introducing the projects, the project brief README could include related CSS resources (that students may choose to use)...

For example, during the autocomplete project- many of us looked up CSS techniques for styling input tags, centering (google search style), and styling ul/li elements underneath. So perhaps;
### Related CSS Tutorials;
[Search Box CSS](https://blog.udemy.com/search-box-css/)
[Centering A Div](http://www.tipue.com/blog/center-a-div/)

This could help save time searching for good css tutorials mid projects. Perhaps for some project briefs, give specific stretch goals design wise, e.g. make the stopwatch 3D

**Comment by bradreeder** [comment]
@harrygfox Thanks, I'll update the title to reflect a broader discussion. I agree with you, the question is more how and where we should integrate that teaching within the curriculum.

**Comment by jsms90** [comment]
There does seem to be a conflict with the messages that I'm hearing, that the likelihood is that FAC graduates are more likely to get frontend jobs after graduation, and yet the course is focused on backend from week 4 onwards. This is also reflected somewhat in the message from certain FAC8 members who were told that their CSS chops weren't up to scratch when applying for jobs.

@harrygfox I agree that we should be taking frontend skills more seriously than expecting students to cover this themselves in pre-reqs, pre-course & week 1.

Maybe a combination of the more involved pre-requisits and the readme suggestion from @njsfield would mean that we can & should _expect_ FAC10+ students to create projects with HTML & CSS, which is critiqued along with the rest of their code, rather than treated as an optional afterthought?

**Comment by nelsonic** [comment]
@harrygfox 🎉 
https://twitter.com/Lady_Ada_King/status/806559433123885056

**Comment by shiryz** [comment]
This has been tackled by introducing more challenges throughout the weeks and the design bursts, will close this issue but if anyone feels this is still relevant, please reopen
