### ISSUE TITLE
Teach Tape and Istanbul in Week 2

### ISSUE THREAD

**Issue by ConchobarMacNessa** [foundersandcoders/master-reference#253]
## What

We propose that we teach Tape and Istanbul in Week 2 (Testing) rather than QUnit and BlanketJS.

## Why

Overall, Tape and Istanbul are much more versatile testing and coverage frameworks which students can continue to use once they progress onto the backend weeks of the course. As it stands, it seems a shame to teach two frameworks which will get no use further down the course. 

I understand that there may be some reservations over using npm modules when node has not yet been taught, but I don't think this will be a problem as long as we make it clear that commands such as ```npm install --save-dev``` will become clear in the coming weeks. 

## How

The current cohort would need to write a workshop introducing using Tape on the front end. This knowledge would then be expanded upon when we teach back end testing. 

For Istanbul, Dwyl has a tutorial on how to use [Istanbul](https://github.com/dwyl/learn-istanbul)

**Comment by ronanyeah** [comment]
Suggestion for [Jest](https://facebook.github.io/jest/).

Reasons:
1. Facebook uses it for all their JavaScript.
2. Is the equivalent of having tape, jasmine, sinon and istanbul all in one, out of the box, with no config necessary.
3. Supports Node.js and transpiled Babel JS out of the box with no config necessary.

**Comment by ZooeyMiller** [comment]
I have only used Jest a wee bit, but I liked it and see no problems with using it in the curriculum.

**Comment by des-des** [comment]
@ronanyeah the api surface of jest is waaay bigger than tape. Might be overkill for week 2.

> Supports Node.js and transpiled Babel JS out of the box with no config necessary.

Again, this seem like a kinda post week 2 problem

**Comment by des-des** [comment]
@ConchobarMacNessa to test code with tape, you need to be able to run it in a node environment. To get code to run in node + in the browser does require some extra fiddling. Not making the point either way but wanted to leave that point here

**Comment by iteles** [comment]
This conversation has come up multiple times over the last few cohorts and ultimately the decision had been made multiple times that introducing node in week 2 was too complex.

If you're going to go ahead an introduce tape in week 2, could I please ask that a few hypotheses are created stemming from this proposal _before_ week 2 so that we can accurately measure and record the results (to help make a _qualified_ and _data-driven_ decision so that we can spare you guys from listening to the same discussions over and over again too)? 🙏

**Comment by sohilpandya** [comment]
@des-des I was under the impression that all proposals would've been discussed on Tuesday. 

What qualified the issues that were bought up on Tuesday? Did you & @bradreeder  just randomly pick issues for the meeting and leave rest out? 

The only thing I'm concerned about is that there will be questions that will be asked about NPM and NODE. Will you be spending the time required to explain all the concepts? (People will ask all sorts of questions because they are curious to find out more) I don't want us to be saying that it'll all become clear in week-4 as it'll leave them hanging. 

I agree that week 2 needs to be rethought because it's not working. People are still struggling to write tests in week 15. I'd really like it if we try to figure out what isn't working in week 2 and how we can improve the structure so that people are more comfortable with it rather than focus in on what tool to use. Because IMO it's not about the tool it's about the concept. 

If you feel that introducing tape will improve the understanding and get them to do it more then I'm all for it. But if the main reason to change it is that we use tape for every other week. Then its not good enough.

**Comment by bradreeder** [comment]
@sohilpandya Those that effected the regular week structure (readmes, lightning talks, html / css), or those that effected the structure of the curriculum as a whole (react, authentication, hapi vs express, etc) were selected as topics that needed to be addressed before mentors could be assigned to weeks.

**Comment by bradreeder** [comment]
@sohilpandya Those that effected the regular week structure, or those that effected the structure of the curriculum as a whole (react, authentication, hapi vs express, etc) were selected as topics that needed to be addressed before mentors could be assigned to weeks. Proposals related to a particular week were left out to be discussed by mentors assigned to those weeks and online due to time constraints. Apologies for not communicating that in advance.

I agree that testing is a subject that presents recurring problems in the curriculum, but  @finnhodgkin and @oliverjam only had time to make iterative modifications, and from their perspective it makes sense they'd choose to focus on what was raised by their cohort.

I don't have a strong opinion for / against this but agree with @iteles that some kind of system for testing (any) changes to the curriculum needs to be devised.

**Comment by jsms90** [comment]
@oliverjam @finnhodgkin Given that you guys have decided to go ahead with tape, I suggest that you follow [@iteles' suggestion](https://github.com/foundersandcoders/master-reference/issues/253#issuecomment-306054818) and clarify your hypotheses in this issue. That way, we can leave this issue open and assess at the end of summer cohorts, whether your predictions proved to be accurate :+1:

I have asked other groups to do something similar, based on @bradreeder's format with the addition of [a community lunch in week 1](https://github.com/foundersandcoders/a-pattern-language/issues/9).
+ Please follow the `problem`, `solution`, `hypothesis` format.
+ In the "problem" section, I suggest that you link to any evidence, perhaps from the SGCs of any of the cohorts or the Curriculum Planning meeting minutes.
+ When writing your solution and hypothesis, try wherever possible to address the concerns that people have expressed above.

**Comment by edgarfinn** [comment]
@jsms90 did you mean to assign me on this? Or @finnhodgkin ?

**Comment by oliverjam** [comment]
@jsms90 @finnhodgkin 

### Problem

On practically every FAC10 project after week 3 we were told to write front-end tests, but ended up with empty folders where the tests were supposed to be. One reason for this was that once CLI tests, Travis and Istanbul were introduced QUnit became super easy to ignore.

>Why bother to write front-end tests that are completely ignored by continuous integration?
- most of FAC10

As far as we know QUnit only works with Travis and Istanbul when it's run in a browser-less environment. So unless we teach JSDOM (or PhantomJS, etc) whenever QUnit is used to test browser functionality (the DOM) it won't work with Travis.

Even before we started Node QUnit was encouraging bad testing. A number of stopwatch projects contained tests like "`document.getElementById` returns an element" or "`setTimeout` delays the call of a function by 1 second" (and even "tests that `h1` has correct title").

Although this was mostly down to confusion about what and how to test, it wasn't helped by QUnit making this kind of test possible.

In our opinion it's as important to teach people to write testable code as it is to write tests. Switching to Tape could help enforce this by making sure that DOM manipulation and side-effect heavy code is both kept separate and to a minimum.

#### Evidence

FAC10's [ Testing Week stop-go-continue](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-2.md) included:

> Stop the stopwatch project
> Have a code-along demonstration of people doing TDD (this could be the romaniser challenge)

and from FAC10's [Node Week 1 stop-go-continue](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-4.md)

> There needs to be a strong direction for tests

### Solution

Encourage testable code and remove QUnit from the curriculum:

+ Give an overview of npm at the start of the week so they understand how to install and run Tape
+ Swap the "Learn TDD" Dwyl workshop for "Learn Tape"
+ Rewrite the Roman Numerals challenge as a codealong to demonstrate best-practice TDD
+ Swap the stopwatch project for something more testing-friendly (a to-do app)
+ Provide some pure functions as boilerplate in the project to encourage writing more testable code

### Hypothesis

Keeping testing consistent throughout the course should encourage students to write front-end tests even in the later weeks. Hopefully it will also give them a head start on writing more testable code in general.

Ideally we'll see FAC11 writing more pure functions, more modular code and more tests in general.

**Comment by eliascodes** [comment]
Proposal passed & implemented.
