### ISSUE TITLE
Proposal: Pre-Course Materials Revamp

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/master-reference#257]
## WHY

As students of Founders & Coders, some of us feel like the pre-course materials as it stands contains too much information with a lack of emphasis on what is important prior to the beginning of the course. 

Currently: https://github.com/yvonne-liu/master-reference/blob/master/coursebook/precourse/resources.md

## WHAT 

We feel like we could've benefitted more had the pre-course materials been better outlined by mandatory things to know before beginning of Week 1, and a [list of resources](https://github.com/foundersandcoders/master-reference/issues/255) that we'll need weekly as the course goes on. 

Some people feel like the pre-course was very front-end focussed and lacking in back-end information. This possibly ties into @oliverjam and @Samatar26's proposal on having a more comprehensive frontend pre-requisite prior to being accepted into Founders & Coders. 

## HOW

The pre-course should be a short list of things that you have to do to be successful during Week 1, but not necessarily everything you will encounter during the course. For example, the pre-course mandatory section should include only the following and encouraging the students to also complete one [advanced FreeCodeCamp project](https://www.freecodecamp.com/challenges/build-a-javascript-calculator): 

- Command Line
- Git & Github
- Markdown
- Semantic HMTL
- CSS

The rest of the material should be laid out week by week or by topic as weekly readings.

**Comment by jsms90** [comment]
These changes need to be made asap, in order for us to deliver this to FAC11 by tomorrow (hence not bringing this proposal to next week's curriculum meeting).

After an in-person conversation with @alexis-l8 & @yvonne-liu, we have distilled this down into the following changes:
+ Remove first paragraph beginning with "F&C is an intense course"
+ Provide numbered list at the top of the precourse page, so that students are aware of all the content and don't miss what's at the bottom i.e. the calculator project
+ Move "DOM manipulation" to "required"
+ Move calculator project to "required"
+ Move "JavaScript" section to "recommended"
+ Clarify what is _required_ before the course
  + Remove "recommended" section from the page itself, so that there is no potential for interpretation.
  + Put this list on a separate page & link to it at the bottom of the precourse page itself
  + Move learning objectives from separate file - add each one into the section of the precourse page itself
+ Add explanation of npm package manager to installation list (& what node is?)

I will be submitting a PR with the content above & assigning @alexis-l8 & @yvonne-liu as "reviewers". But everyone is more than welcome to add their own reviews :+1:

**Comment by oliverjam** [comment]
@jsms90 If you want a basic intro to using NPM (that shouldn't require understanding Node) I've been putting this together for a while: https://github.com/foundersandcoders/london-marketing/issues/7

**Comment by jsms90** [comment]
@oliverjam Thanks so much for this! This sounds great for students when they are about to start using node (`npm init` etc.) but maybe it would be worth staying quite high level for the moment?

We were thinking of linking to [art of node](https://github.com/maxogden/art-of-node). It also has a very nice explanation of callbacks. Looking at this article in week 4 was the first time I understood what a callback was :grin:

**Comment by jsms90** [comment]
Happy to close this issue @alexis-l8 @yvonne-liu ?

**Comment by yvonne-liu** [comment]
Yes @jsms90! Thank you! ✨
