### ISSUE TITLE
Teach a lot more HTML/CSS

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/master-reference#258]
Following on from #25  

## Why

HTML and CSS are fundamental aspects of web development and are not skills that can be relegated to a single morning challenge and a research topic. Neither should we rely on students coming to the course with this knowledge — I've noticed that the website is now specific about the pre-requisites including the HTML & CSS section on Free Code Camp (which is wasn't for our cohort), but this is woefully inadequate as it stands and barely even includes any CSS.

The new [Free Code Camp Beta curriculum](https://beta.freecodecamp.com/en/map) is much much more comprehensive, but is also 30 hours long (not including 150 hours of projects). Given this amount of focus/time from FCC, it seems obvious that we are severely lacking in this area.

## What

We propose a morning challenge/workshop on relevant HTML/CSS concepts every week. The mentors for each week will be responsible for finding an hour slot to fit a relevant challenge/workshop into their curriculum.

## How

We write one workshop per week covering a frontend fundamental skill that fits with the week's overarching theme. A few examples:

### Testing Week
If we're keeping the stopwatch projects we can have a workshop on building an accessible interactive UI with start/stop toggle buttons that work with screen readers.

### API Week
If we're teaching them how to query an API we could teach them how to layout the data in a responsive grid.

### Database week
If we're teaching students to POST user data to a Node server/database at some point then it would be good to show them how to properly create an accessible HTML form that does this.

---

There are lots of things I think would be important to cover (although at least some of these should be covered in a revamped Week 1. At least some of this could be lifted from places like FCC I imagine.

- Using the right (semantic) HTML elements

- Forms (accessibility, submitting without/with JS, validation, styling)

- Layout (grid systems, flexbox, [CSS grid](http://caniuse.com/#feat=css-grid) has surprisingly good support now)

- Creating and styling simple components (media object, cards, image galleries)

- Responsive design, mobile first (media queries etc)

- Structuring CSS (especially at scale - [cssguidelin.es](http://cssguidelin.es) is great)

**Comment by emilyb7** [comment]
My two cents on this:

I fully agree that it would be great if we could somehow fit all of the above things into the curriculum. I would also add simple CSS animations to the list! And I would love to see more CSS themed morning challenges (like, here's a cool looking thing - now try and replicate it without looking at the code)

However, disagree with scrapping API week (as you may all remember from week 3, I ❤️ APIs).

Reasoning:
- If we also go ahead with #256, we won't cover asynchronicity (client- or server-side) at all until week 4, when students are also grappling with the whole new concept of server side things
- It's important to understand how HTTP requests happen more generally, response codes, error handling etc. There's lots of complicated stuff that goes on in the browser, which students need an introduction to.
- When it comes to week 4 projects, students will have to simultaneously learn how to make a server and how to make requests to their server (bit of an overload, I think)

Sorry, I don't have a good solution to the actual problem here :(. I just don't think that losing API week is good move!

> we think API Week could be sacrificed since we cover API requests multiple times once we start learning Node.

so maybe we should have less focus on API requests during node weeks?

**Comment by emilyb7** [comment]
Oh wait I just read #256 and realised that it doesn't involve completely eradicating all async stuff from week 2's curriculum. It does seem to contradict the idea of getting rid of API week though... Guessing there are differing opinions here?

**Comment by jsms90** [comment]
@oliverjam (and anyone else) please see issue #25 for our recorded history on this topic and the discussion in the toolkit week issue #24 

### Scrapping week 3 :cry: 
I agree with @emilyb7 that scrapping week 3 might be a bad idea. I seem to remember you guys giving pretty positive feedback about [the introductory workshop](https://github.com/lucymonie/api-workshop#introducing-apis) (although I can't find anything in your sgc) and incredibly [positive feedback](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-3.md#continue) about @eliascodes' [design & architecture workshop](https://github.com/eliascodes/workshop-client-side-design).

It's also worth looking over the things that were taken out of your week 3, which [we had during research afternoon](https://github.com/FAC9/READMES/tree/master/APIs). For example, I was quite surprised to find out that your cohort didn't all know the structure of a URL by week 7, until I realised this was in our readmes. Makes `req.query` a bit mysterious :sweat_smile: 

### Isn't this largely week 1?
Your bullet pointed list very much sounds like existing content in week 1 + a bit more.

I acutally don't actually agree with week 1 needing to feel like a light introduction. I think students arrive, expecting a full on course, and giving them something slightly more intense would be beneficial.

Based on what you've written above, I would suggest iterating on the existing materials in week 1, scrap what you want to, remove the bloat. Look back through [FAC9's week 1](https://foundersandcoders.gitbooks.io/fac9/content/week1/), because you might want to save some stuff. I know @njsfield and I would be more than happy to give tips for your list. You could also get some brilliant advice from @nogainbar. There's tonnes of room for improvement. And depending on what happens to research afternoon #261, you might have even more time.

**Comment by oliverjam** [comment]
I agree with you both that scrapping Week 3 would be bad. It was just the only place we could think to squeeze this in (and we think teaching more HTML/CSS is critically important).

I disagree that this would only entail a bit more than the existing Week 1. I just had another look through our curriculum — we did nothing on this until Day 2, when we had a 1 hour accessibility challenge which spent more time on `tabindex` than anything else. We then had a research afternoon where one of the topics was "CSS". Finally we had a 1 hour morning challenge covering some CSS layout. Being generous that's about half a day's work on the entirety of HTML/CSS.

As I said above, Free Code Camp's Beta curriculum now includes 30 hours of learning and 150 hours of projects focused only on HTML/CSS. Even if we're assuming students come to the course with a certain minimum level of knowledge I think we need to seriously bump up the amount we cover in Week 1.

Alternatively we could increase the pre-requisites or pre-course material to include more of this stuff. For my cohort the requirements were just to get 5Kyu and build one website, so it's possible lots of people had hardly written any HTML/CSS before starting.

**Comment by lucymonie** [comment]
My thoughts about the points raised above:
- Do weeks need to cover specific topics or groups of topics, or can this be blurred? Would blurring create confusion and flabby MVPs?
- Would it be better to insist on beautiful css in every project from week 1 onwards?
- Could readme afternoon be replaced with a weekly front-end masterclass relevant to the week's topic?

**Comment by oliverjam** [comment]
@lucymonie

- I think having specific focused learning outcomes for projects helps a lot considering we only have 2 days for each

- At a bare minimum we need to dispel the idea that CSS doesn't matter because it's not in the learning outcomes. If we're going to insist every project has semantic markup, is accessible etc then maybe we should insist there is some bare minimum mobile first layout.

-  This could be a good compromise if we absolutely can't find time for a week focused on this. We could teach a new frontend thing each week and ask teams to use it in their projects.

**Comment by ZooeyMiller** [comment]
I agree with @jsms90 that it's fair to throw students in at the deep end and have week 1 be a bit more intense. Day 1 being fluffy is cool, but I was fully prepared for super intensity from day 1 and was surprised when it wasn't delivered. 

I like the idea from @lucymonie for a front end masterclass to replace readme afternoon, though a lot for the problem with readme afternoon is that some topic are super important and really need to be covered and some are less so, so we would need to find time to teach those things somewhere. 

I very much agree and believe good semantic HTML and CSS need to be more of a focus, I think the course would benefit from a little less back end and more CSS and HTML. One of the main things I'm working on now to improve my employability is CSS.
Seems weird that I'm on the tail end of FAc feeling that those are the skills i need to improve when really those are the fundamentals of web dev.
I think it's reasonable to dedicate a week to this, or at least an afternoon. I really like the idea of a new CSS concept each week and requirement to use it in that week's project.

**Comment by jsms90** [comment]
> I disagree that this would only entail a bit more than the existing Week 1

Definitely true! Personally, I would like to see us move towards a course which is 4 weeks front end & 4 weeks back end. I think we are all aware that the treatment of front end on this course is not really adequate. But that can only happen in small, incremental steps.

In order to take out an entire week of the current course, this proposal would need to be very detailed about how to retain the contents of that week elsewhere. I have said it already, but I would remove week 2. Not because testing is unimportant (you've all met me, right? :wink:) but because testing is _part_ of a project & doesn't need to be treated as an independent topic. But this is a huge change to make, unless someone has the time to think through a very detailed plan of action.

Which is why I would suggest that the most realistic thing that we could do in a short space of time is _dramatically_ improve week 1 (seriously, there's so much room) **and** pepper more content throughout the rest of the course.

I know that you guys are thinking about removing research afternoon. But don't feel restricted to the current format of the weeks. It's not about just filling that afternoon with something new. @oliverjam made a very good point during curriculum planning - a lot about HTML & CSS (at least the fundamentals) might be best delivered by allowing students to find out what's available & then practice! That lends itself extremely well to a morning challenge.

How about a morning challenge on HTML & CSS every week? One of many possibilities: 1 challenge about form submission during a front end week & 1 about form submission in a back end week.

**Comment by oliverjam** [comment]
@jsms90 I think a morning challenge each week could work. That would reinforce the idea that these frontend skills are constantly important no matter what you're learning or building, and ensure that students don't get sucked down a database rabbit hole and forget how to write CSS.

The enhanced pre-course material in #257 should help too

**Comment by jsms90** [comment]
@oliverjam The precourse material doesn't add any more CSS than you guys had :confused: 

You may or may not want to rebrand it from "morning challenge" though? Depends on its content I guess :thinking: 

"Morning challenge" works if it's something that they already have the skills to accomplish (with a bit of googling). It's slightly problematic to refer to something as a "challenge", if it is the section where you are delivering new knowledge. With CSS especially, as you have said multiple times yourself, it is imperative that it isn't seen as something we just tack on to the course half-heartedly.

If this is something that you want to be in your proposal, I suggest that you edit the version at the top. The version above should be ready for a 'yay' / 'nay' vote i.e. no "We propose...alternatively...." :+1:

**Comment by oliverjam** [comment]
Good point about the pre-course. I was thinking of the pre-requisites now specifying that applicants have to do some FCC. It was only a suggestion for us.

Once the beta curriculum goes live there I think we should leverage that resource quite a lot. It's a really comprehensive intro to front end (and without projects is 30 hours of work max).

Is it worth maybe suggesting applicants do that instead of the current old FCC (that hardly teaches any CSS before moving on to Bootstrap)? The only downside is that all their progress will be lost when FCC merge this into the main site

**Comment by oliverjam** [comment]
And I will update the proposal once I'm at a computer with some free time!

**Comment by bradreeder** [comment]
@oliverjam Could you update this tomorrow morning before the meeting in the afternoon? 👍

**Comment by oliverjam** [comment]
Updated 😄

**Comment by eliascodes** [comment]
Proposal passed & implemented.
