### ISSUE TITLE
React

### ISSUE THREAD

**Issue by finnhodgkin** [foundersandcoders/master-reference#259]
# Why

## Employability
The Stack overflow survey 2017 lists React as the 'Most Loved' and third 'Most Wanted' framework after Angular and Node. In their Developer Hiring Trends survey React takes the top position for highest increase in demand.

![React increase graph](https://stackoverflow.blog/wp-content/uploads/2017/03/ChangesinDemand.png)

**Every single** external speaker we've had has either recommended React or at least said it's a safe bet. 

## Production quality tool
The traditional vanilla JS / jQuery method of directly manipulating the DOM is not commonly used in production. The new paradigm heavily favours front end frameworks like React, Angular, Vue and Elm. 

## Everyone on FAC10 expressed an interest in learning it

# What

Add React to the later portions of the curriculum.

# How

#### A full week
A project based week of React similar to FAC8, but with smaller teams, possibly even pairs. 

#### Single day workshop
A single well-prepared full day workshop on React centred around building a todo app.

## Options for timetable
- Take a week out of free-form projects to learn React.
- Do week 8 as React (7 and 8 combined).
- Do a one full day React workshop.
- Half of UX week devoted to learning React instead.

@Akin909 @PiotrBerebecki

**Comment by iteles** [comment]
I have many things to say on this point but I will stick to the most important:
**Taking half of UX week to do _anything_ but UX related work should even not be considered to be an option.**

Happy to let others jump in on the actual topic at hand before I express my thoughts.

**Comment by jsms90** [comment]
Let's put this into context of what FAC is trying to do. **Learning to learn will make you more employable than any one technology ever can.** _That_ is what makes FAC graduates stand out & makes you truly employable.

+ FAC grads are definitely employable without it
+ If students don't feel equipped to learn it themselves, _that_ is the problem we need to solve.  
Our responsibility is to make sure that students feel excited about learning new technologies & have confidence that they can tackle that hurdle (@Akin909 :+1:). Let's make sure we get that right!

I'm not remotely convinced that React is a higher priority than any of the things in the list of what it would replace. But a one day tester session might be nice, if you want to whet people's appetite?

It think it would be _great_ if we could find time for this on the course! But IMO that's not our top priority out of the things that are missing. Temember the reasons outlined in our [house rules](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/general/house-rules.md) for not including frameworks on the course:
> + By solving problems using the foundations of the language first, you will begin to understand what problems frameworks were built to simplify. This will let you make more effective judgements on which technologies to use in future.
> + It arms students with the flexibility to switch between technologies, as the popularity of each one can shift.
> + F&C values are heavily aligned with open source software. You should be better able to contribute to and improve upon existing technologies if you have a deeper understanding of what is going on.

**We should start teaching people front end before we even think about introducing a framework into the mix.** :tada:

**Comment by ronanyeah** [comment]
I think more than any one framework in particular I think we are really letting students down by not teaching them Webpack, Babel etc. It's a very complicated ecosystem and is one of the hardest things about learning any front end framwork. Even Elm.

**Comment by ronanyeah** [comment]
Also regarding React, if the curriculum is truly an evolving document, is there anything wrong with teaching and advocating the most popular X solution at the time the cohort is happening? Things can always be revised. And this is coming from someone with no love for the React ecosystem, but it does a pretty good job and the job market is fantastic.

**Comment by ronanyeah** [comment]
@jsms90 You referred to house rules to reinforce the 'no frameworks' argument. But two weeks of the course is Hapi-based.

**Comment by jsms90** [comment]
@ronanyeah Yeah. To be fair, the house rules should probably be updated to specify that this refers to front end frameworks. I've never heard anyone suggest that it would be beneficial for students to spend all their time using node core. But a very big deal has always been made about "no frameworks" (at least during FAC9) and I think the reasoning is solid.

But I would be open to React in the second half of the course. But ideally, we would actually gave students an education in framework-less front end first :laughing:

**Comment by ronanyeah** [comment]
@jsms90 I think that it would be good to do cookie authentication with node core before moving onto Hapi/Express as I feel that authentication has this mystical aura because people only ever learn it using a plugin, which can lead to framework lock in. (Should probably copy that to the Hapi/Express issue...)

Anyway RE: framework-less, as I just said in Gitter, I think we could provide a solid webpack/bundling/minification workshop and then let them decide what to bundle. I'm not going to pretend that they won't all just choose React but at least that gives the curriculum a bit more flexibility for when Vue 12 is the BEST FRAMEWORK.

Bundling is an essential skill for front end developers these days and is not an easy one to pick up. This also solves the ES6 browser compatibility concern.

**Comment by ronanyeah** [comment]
Also I think it would be valuable to separate the ideas of UX frameworks and Data/Application frameworks. Bootstrap and React are both frameworks and are not at all related. I don't know enough about UX to comment on it's 'shortcuts' but I don't think anyone is really learning anything from building a data driven application out of for-loops and querySelectors...

**Comment by oliverjam** [comment]
I agree with @jsms90 that we absolutely need to teach more frontend. My projects weeks 5-8 had literally 0 lines of frontend JavaScript. Given the direction the industry appears to have been moving in for a while now (single-page apps, offline-first progressive web apps etc) are we doing students a disservice by teaching them to build almost the opposite? This is especially relevant to employment given almost all of us are going to at least start out getting frontend jobs.

I also agree with @ronanyeah that there's not much point learning to build complex frontend applications in vanilla JS anymore. All that's going to do is ingrain bad practices. It's more important to start learning the kinds of things React will introduce you to straight away. I'm going to quote from [Sacha Greif's super-popular article](https://medium.freecodecamp.com/a-study-plan-to-cure-javascript-fatigue-8ad3a54f2eb1) recommending beginners learn React:

>React will also introduce you to some useful concepts like components, application state, and stateless functions that will prove useful no matter which framework or libraries you end up using during your career.

>If you’re a very methodical learner, you might want to get a good grasp of the fundamentals of JavaScript before you do anything else.

>But for others, this feels like learning to swim by studying human anatomy and fluid dynamics. Sure, they both play a huge role in swimming, but it’s more fun to just jump in the pool!

**Comment by finnhodgkin** [comment]
Of course I agree that arming students with a strong basis in the foundations of Javascript is incredibly important, and that shoving React in at the beginning of the curriculum could damage the flexibility of graduates. But that’s *really* not what I’m suggesting – I for sure don’t think it should be taught until the latter portions of the course. 

And yeah okay, dropping half of UX week is a little extreme, but I don’t agree that front end frameworks - and the tooling that goes with them - are less important than oauth *and* JWTs in Hapi (week 8). Couldn’t we have a go at combining weeks 7 and 8 to make room for a front end framework?

Considering most graduate jobs are weighted towards front end work, it’s felt strange throughout the course that we don’t even touch on Webpack / a front end framework. I do appreciate that FAC encourages us to ‘learn to learn’ but that shouldn’t mean the things we do learn are niche or approaching irrelevance (curriculum-wide vanilla-only front end JS and no ES6 / babel).

I’m really glad our curriculum included a Node framework, but I never got the logic behind allowing Hapi but not a front end equivalent. I for one would much prefer to write a large, complex Node core server than a large, complex front end UI without some abstraction from vanilla DOM manipulation (plus state, etc.).

Maybe you’re right @jsms90 , and the answer is to provide better teaching of framework-less front end Javascript – but even then surely it couldn’t hurt to progress to a well adopted method like React, in the same format as progressing to Hapi from Node core.

**Comment by oliverjam** [comment]
@finnhodgkin That's a good point. I'd _much_ rather write a vanilla Node server than make anything halfway-complex using vanilla DOM manipulation.

I think right now we don't do enough frontend to justify a framework, but that's not a good thing!

**Comment by jsms90** [comment]
### Week 1-8 projects are often too ugly to go in a portfolio :sweat_smile: 
Off the back of:
> My projects weeks 5-8 had literally 0 lines of frontend JavaScript

I would also like to point out that we're not currently arming students with a portfolio of work that they could realistically show off to anyone. I know that we have graduate projects as part of the model now. But not everyone gets one (at least not yet). I don't think students should have just one project (weeks 10-12) to show for their 16 weeks with us. It doesn't matter how small or basic the week 1-8 projects are, they just shouldn't look _totally_ CSS-less and unfinished :sweat_smile: 

### Getting front end foundation right _first_
@finnhodgkin
> Of course I agree that arming students with a strong basis in the foundations of Javascript is incredibly important
>
> I do appreciate that FAC encourages us to ‘learn to learn’ but that shouldn’t mean the things we do learn are niche or approaching irrelevance (curriculum-wide vanilla-only front end JS and no ES6 / babel).

Exactly! My point is that we do _very, very little_ front end on the course and that needs to change. I would only advocate adding a framework in the second half of the course _after_ we add the funamentals. Proposal #25 is just one baby step in the right direction IMO. We can't fix everything in one go and I would say that adding React is, if nothing else, much too early for this stage in our curriculum's development. I think we are in danger of giving people further reading before giving them the core knowledge.

### Swapping back end framework for front end framework
I don't think we should be discussing back end framework _vs_ front end framework, as though they are interchangeable.
> I don’t agree that front end frameworks - and the tooling that goes with them - are less important than oauth and JWTs in Hapi (week 8).

+ As @oliverjam has said before, the hardest part about learning React is the required change in mentality, not learning the syntax. Regardless of the framework choice, at least we do give a more solid back end foundation _before_ introducing a framework. (I'm not going to start discussing FAC's specific choice of backend framework here).
+ As far as I know (!), _no one_ codes in node core on the back end. Since there's little chance of you stumbling into a framework-less back end project, it makes somewhat more sense to introduce one on the back end more quickly than a front end framework.
+ I don't know of anyone having problems with having learned the "wrong" back end framework and then being unemployable when the fashion of the day changes. Whereas that _absolutely_ happens on the front end. Even if you never code in vanilla JS on the front end every again, knowing what is happening under the hood is _fundamental_ to being able to change with the changing fashions.
+ Some people in the industry have derogatory attitudes towards front end development (i.e. it's easy / just about "making things pretty"). Front end has a perception of being more approachable. Lots of people won't trust a newbie with back end work. For all of these reasons, it seems like you get more cowboy front end codes. So the mish mash of libraries and frameworks makes it all the more important to know the fundamentals, in order to wade through the melee.


### Current content of hapi weeks
@ronanyeah Please see #263
> I think that it would be good to do cookie authentication with node core before moving onto Hapi/Express

**Comment by ronanyeah** [comment]
@jsms90 Do you think front end TOOLING should be a part of the curriculum?

**Comment by jsms90** [comment]
@ronanyeah for example?

**Comment by ronanyeah** [comment]
@jsms90 Bundling and minification. Essential front end skills these days, difficult to pick up, and framework agnostic.

**Comment by ronanyeah** [comment]
Can anyone point me to a resource supporting vanilla JS apps on the front end?

**Comment by emilyb7** [comment]
I think I agree with teaching webpack (or equivalent) before / above React. There are lots of good tutorials out there for learning react independently, but all those I've seen completely skim over the bundling part and it's confusing if you go into it with no knowledge.

**Comment by ronanyeah** [comment]
@jsms90 You seem to be conflating UX and design skill with front end JS engineering skill, when in my opinion they do not necessarily overlap. You can make a beautiful site out of jquery spaghetti code and can also make a rock solid immutable real-time data driven super app that looks like it was made in the 80s.

**Comment by ronanyeah** [comment]
I have opened a related issue: https://github.com/foundersandcoders/master-reference/issues/264.

**Comment by jsms90** [comment]
@ronanyeah 
> You seem to be conflating UX and design skill with front end JS engineering skill

Not at all! I think all _front end development_ is largely missing from the course. HTML & CSS is part of being a front end developer. Hence #25 being a "baby step in the right direction". Week 1 just needs tightening up.

We do also need [a full week on front end JS](https://github.com/foundersandcoders/master-reference/issues/263#issuecomment-302857016). But I think #264 is getting ahead of ourselves, and React is jumping the gun entirely.

During the past week with IP Cortex, some teams struggled with:
+ passing by reference vs passing by value
+ navigating the DOM tree
+ event listeners (using `e.target`, etc.)

**Comment by ronanyeah** [comment]
@jsms90 Yeah I'm totally in support of a front end week. I definitely do not want a framework in it. But I think webpack and ES6 modules are a must (as they are an essential front end skill these days and can be used with vanilla front end JS as well as any frameworks).

Perhaps we could could move this discussion to https://github.com/foundersandcoders/master-reference/issues/264 then and adapt it, and leave this issue for any React discussion.

**Comment by des-des** [comment]
@oliverjam 
>  Given the direction the industry appears to have been moving in for a while now (single-page apps, offline-first progressive web apps etc) are we doing students a disservice by teaching them to build almost the opposite?

The guardian, bbc and github all render on the server. I think that it is good to understand that server-side rendering is an important tool when it comes to building sites that load fast, and teaching students how to do it is not doing them a disservice.

**Comment by oliverjam** [comment]
@des-des You're right, and I wasn't arguing that we shouldn't teach any server-side at all. It just seems like we're missing a trick to teach almost no frontend on the course.

Also you can (and probably should) server-render React, so they aren't mutually exclusive.

**Comment by bradreeder** [comment]
@finnhodgkin @oliverjam @ronanyeah @jsms90 

A compromise for this (and #264 ) that currently springs to mind:

During week 11, FAC10 had a day's workshop on chatbots, which was good but in the context of that week only relevant to one of the group projects. Instead of this we could trial a workshop on Front-end tooling (webpack / bundling / minification).

* In the context of a week in which tech choices are more flexible, this is framework agnostic but will be a foundation for people who choose to explore react.
* Creating this workshop would be less time-intensive than creating a whole react week or a whole front-end engineering week #264 (which people are unlikely to have time for this round). It's easier to slot this into the current curriculum without disrupting other weeks. 
* The creation of this workshop would make creating one of these weeks easier at a later date as it could be re-used within them. I'm in favour of approaching the creation of new weeks in a gradual rather than all at once way so we can properly user-test workshops before replacing other core curriculum content with them.

Do you have any suggestions for where else this might fit?

**Comment by des-des** [comment]
yeah thats what the bbc does

**Comment by jsms90** [comment]
My preference would be to leave React [in the tech choices of the project build](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/fragments/product-build/tech-choices.md#react) & think more closely about introducing a [front end engineering week](https://github.com/foundersandcoders/master-reference/issues/264)

**Comment by zurda** [comment]
Am I mistaken, or is React officially in the curriculum for all programs? I apologise if I'm missing something (cc @shiryz , @m4v15 )

**Comment by oliverjam** [comment]
Yeah this can be closed. We have an official React Week that also teaches a fair bit of modern frontend (bundling, ES modules etc)
