### ISSUE TITLE
Why is the curriculum only 8 weeks?

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/master-reference#275]
After seeing all the discussions and proposals for things which people want added into the course, is there any particular reason why the 16-week course only has 8 weeks of structured curriculum?

I don't think I've seen this discussed at all anywhere.

**Comment by ronanyeah** [comment]
CONTROVERSIAL.

**Comment by jsms90** [comment]
@ronanyeah Is it controversial?

@mattlub The answer to that question just isn't documented in one single place. As I understand it, no one has had a "master plan" or a vision for the curriculum that has differed significantly from what was delivered many many cohorts ago. You can see that most cohorts have had an 8 week "curriculum" since curriculums have been recorded:
+ [old playbook](https://github.com/foundersandcoders/old-playbook/blob/master/foundation.md)
+ [FAC4](https://github.com/foundersandcoders/old-fac4-coursebook)
+ [FAC5](https://github.com/foundersandcoders/old-fac5-coursebook)
+ What happened to FAC6? :scream: 
+ [FAC7(?)](https://github.com/foundersandcoders/old-coursebook/tree/master/workshops)
+ [FAC8](https://foundersandcoders.gitbooks.io/fac8/content/) - 10 weeks: weeks 9-10 = React
+ [FAC9](https://foundersandcoders.gitbooks.io/fac9/content/) - 10 weeks: weeks 9-10 = UX/UI

What has been taught after the 8 weeks has differed from cohort to cohort. The last 2 cohorts just happen to have written weeks 9 & 10 down.

When the `master-reference` was forming, @des-des and @bradreeder were doing their best to gather info and opinion and document it all, rather than actually trying to define the direction of the course themselves. So given the history of the curriculum, it made sense to only set in stone the weeks that had been repeated for every cohort. The weeks after no.8 have been so ever-changing anyway.

For a bit of a clue as to the plethora of things there have been, take a look at [the peer review](https://github.com/foundersandcoders/master-reference/issues/35), where they gathered feedback from alumni.

Because of that peer review, you guys _almost_ had [Websockets & Redis](https://github.com/foundersandcoders/master-reference/issues/35). I can't quite remember why it didn't happen in the end. Maybe because my cohort didn't feel prepared to make the material, having never learned it during our course? Maybe cos plans were brewing to [move Reading week]((https://github.com/foundersandcoders/london-programme/issues/135) ), which then split the course into 8 week blocks? Can't remember.

By the time December/January rolled round, @bradreeder @des-des and I very much had a plan for weeks 10-12 to be a ["final project"](https://github.com/foundersandcoders/master-reference/issues/14) i.e. your 3 week build. Add that to the newly formed idea of "graduate projects" (a roaring success for FAC9), and whaddaya know, the second half of the course became fully about "building a portfolio" #88

**Comment by mattlub** [comment]
@jsms90 woah thanks for all the background.

It seems that there is no particular reason why, if some people had strong arguments for adding extra core material to the course (and of course people to produce the material), there couldn't be more structured curriculum time. I guess e.g. week 9 was nearly like one of the first 8 structured weeks, so maybe the course will just move slightly in that way anyway.

**Comment by jsms90** [comment]
@mattlub 
All good :wink: I've spent an inordinate amount of time trawling through the history of all the `foundersandcoders` repos & speaking to people in the organisation, trying to information-gather and understand what has gone before me. Over time, I hope we can distill this down into documentation, so that students who have these kinds of questions know where to look :+1: 

As for adding more "core material", I suppose it entirely depends on
+ how valuable people find the self-directed element of the second half of the course as it currently stands
+ whether we want to continue doing real-world projects as part of the course
+ whether they see value in having a self-directed, longer project to do before jumping into real world projects

If people want to keep all of that, then we can just try to find in one-day workshops, but probably don't have time for any more full-blown week on x technology type weeks.

...Having said that, the first 8 weeks are currently undergoing extensive revisions. I have a feeling they will go through even more extensive revisions over the next couple of cohorts. Perhaps addition "core" weeks aren't even what we need? :thinking:

**Comment by sofer** [comment]
@jsms90 for your entertainment:
- [FAC3](https://github.com/selforganising/book/blob/master/SUMMARY.md)

@mattlub  The main reason that the core curriculum is 8 weeks is, as @jsms points out, to keep the balance between core curriculum and portfolio building. It also neatly allows 16 recent graduates to spread themselves neatly in pairs between 8 project weeks. So it works, logistically.

If, on the other hand, FAC was [a 26-week programme](https://github.com/foundersandcoders/london-programme/issues/74) expanding the core curriculum weeks might make a lot of sense.

**Comment by astroash** [comment]
@mattlub are you happy for this issue to be closed?
