### ISSUE TITLE
Week 4 - Node Week 1 preparation

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#297]
1. - [x] Update learning outcomes for the week to reflect what we want students to get out of the week #441
1. This week had generally good feedback, we think this was largely due to the mentors knowing the material really well and delivering it in a clear manner
    * - [ ] Deeply familiarise ourselves with the material
    * see https://github.com/foundersandcoders/Node-Intro-Workshop/issues/7
2. - [x] Potentially remove tape workshop as week 2 will now be using tape, and week 5 will be doing the workshop on testing server routes with tape and shot
    * We will still be encouraging people to test back end and front end, but clarifying we expect tests on pure functions and not on the router
        * - [x] update project brief to include this.
    * If we don't replace (if we feel something is missing from week 2 or week 5 workshop) we will still reduce to 1hr rather than 2hr.
     * replace with the HTML/CSS workshop
3. - ~Create a HTML/CSS morning challenge on making an existing autocomplete search bar accessible (which we will then put in the requirements for the week's project) #442~
4. - ~We will decide on what exactly to do with research afternoon when we decide what form they will take~ We are keeping research afternoon _as is_ 
    * ~We are leaning towards making it into a relatively self directed workshop involving independent research  where the students do simple architecting, explore concepts in engineering and package and deploy on heroku~.
    * This week's research topics are all pretty important so we think it would be good to try and format it in a way where everyone does everything.
    * Include @eliascodes suggestion of understanding the structure of a URL to the research topic. 
5. - [x] add a few tweaks to @stevehopkinson 's ES6 challenge (make things clearer and remove a couple of things). 
    * already raised an issue on the repo, Steve has made a PR, will review and follow up.
    * see https://github.com/stevehopkinson/es6-challenge/issues/3
6. - [x] modfiy / rethink the modularisation morning challenge 
    * https://github.com/foundersandcoders/modules-challenge/issues/5 

Week 4 mentors LDN: @zooeymiller, @yvonne-liu
Nazareth: @zooeymiller @yvonne-liu @finnhodgkin
Gaza: @zooeymiller @yvonne-liu @finnhodgkin

(edited to change UL to OL to make points easier to refer to in comments, not to reflect priority)

**Comment by ZooeyMiller** [comment]
re: the ES6 workshop we have raised issues and re: the SGC notes.

**Comment by jsms90** [comment]
I :heart: this format. I think @bradreeder and I should bake this in to the curriculum planning process. It's very much like DWYL's `epic` issue process :+1: 

If you are removing the tape testing workshop, then perhaps you have space for @bradreeder's node shell workshop in this week? Prior to his redesign of that week, FAC was always actively warning students that week 4 was very difficult. Since then, FAC9 & 10 have loved it. Perhaps node week 1 is the appropriate place for it?

**Comment by eliascodes** [comment]
Could we add something about understanding the structure of a URL to the learning outcomes for this week? There is currently a research topic called "Working with URLs" but it's specifically on working with the `url` and `querystring` modules. Could be reworded to focus on understanding the structure of a URL, using those modules as support?

**Comment by ZooeyMiller** [comment]
On the second point of this (remove tape workshop) I think we can totally comfortably do this, and use the time for the HTML and CSS workshop. @yvonne-liu do you have any thoughts? Or @finnhodgkin as you will be mentoring this week in Naz and Gaza too?

**Comment by ZooeyMiller** [comment]
RE: Steve's ES6 workshop he has made some welcome changes which I have looked at, I am planning to make a PR to it updating a little bit of the wording in the readme (Steve has approved me doing this and will of course review the final PR with wording changes as well)

**Comment by ZooeyMiller** [comment]
Right now I think 3, 4 and 6 are the most demanding and imminently necessary points to be worked on. I will get started on them and try to have the PRs in by Monday 10th.

**Comment by eliascodes** [comment]
@ZooeyMiller any word on [my suggestion](https://github.com/foundersandcoders/master-reference/issues/297#issuecomment-305829263)? Agree/disagree/etc?

**Comment by ZooeyMiller** [comment]
@eliascodes apologies, yes I think that we should do that, good suggestion.

**Comment by ZooeyMiller** [comment]
Still unsure of what exactly to do with the Research Afternoon, will make an issue detailing things to do when clarity is achieved.

**Comment by ZooeyMiller** [comment]
PRs made to `Node-Intro-Workshop`. https://github.com/foundersandcoders/Node-Intro-Workshop/pulls

**Comment by yvonne-liu** [comment]
My suggestion for week 4 research afternoon would be a mini-project that includes the major takeaways from the research afternoon: setting up a Node server, an accessible _something_ on the frontend, includes a `package.json` with `npm` packages, and deployed to Heroku. Thoughts? @ZooeyMiller @jsms90 @eliascodes @finnhodgkin

**Comment by yvonne-liu** [comment]
Some status updates because I don't want to overwrite Zooey's stuff up there: 

For 1. on learning outcomes, I updated #441 **_review pending from @ZooeyMiller and @jsms90 or anyone else._**

For 3. "Remove tape workshop as week 2 will now be using tape, and week 5 will be doing the workshop on testing server routes with tape and shot" - consider it done. I updated the project brief to include this. **_Review pending from @ZooeyMiller @jsms90, pelase see 5a7c4fe_**

**Comment by eliascodes** [comment]
@yvonne-liu are those the takeaways from research afternoon? 😕

[From what I can see](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-4/research-afternoon.md) the takeaways are understanding the differences between client/server, understanding modules, IO and async functions in Node, understanding npm and understanding deployment.

**Comment by yvonne-liu** [comment]
@eliascodes Yeah I didn't realize we're keeping research afternoon, that's my bad. I personally think learn by doing is the best of way of understanding something (understand deployment by actually deploying) -- but I think it's fine to keep everything as is but adding in your suggestion of understanding the structure of URL.

**Comment by eliascodes** [comment]
@yvonne-liu I wasn't necessarily speaking in favour of keeping research afternoon as it is necessarily; your idea of a mini-project could be a good way of doing it. I think I was just thrown that you had "front-end something" in there.

Would be quite happy for you to try it as you suggest, as long as they are clear on the notes they have to hit.

**Comment by yvonne-liu** [comment]
After a discussion with @ZooeyMiller and @jsms90 we're going to move forward with the following:
- Keeping Day 1 the same, but asking students to attempt the Node Girl Workshop until step 7. 
- For Day 2, _removing_ Tape Workshop because the material has already been covered by the mentors in Week 2. Starting the day with ES6 challenge, then allowing more time for Node Girl Workshop because previous cohorts have provided feedback that they were not able to finish the last few steps of the workshop, and those who have finished found it to be very useful. The students would finish the Node Girl Workshop steps 8-10. Then we would follow up with the modularization challenge. 
- On Day 3, we are now modifying the accessibility workshop into a morning challenge. It would show how autocomplete is done on the front end, at the same time showing how their project could benefit from making it more accessible.

**Comment by ZooeyMiller** [comment]
PR has been made on Steve's repo. Awaiting merge from him.:+1:

**Comment by ZooeyMiller** [comment]
Have gone through the modularisation challenge and made a pr: https://github.com/foundersandcoders/modules-challenge/pulls

**Comment by stevehopkinson** [comment]
I merged the hell out of that PR.
