### ISSUE TITLE
Week 7: Hapi views

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#33]
This issue is intended for usage by mentor's who get assigned to Hapi/ templates week and for discussion around the week. As a single source for S-G-C notes and FAC9 feedback, discussion, external feedback, and to commit their work against for review.

**Comment by bradreeder** [comment]
FAC9 feedback #18 :

* Replace makemehapi with a FAC-built workshop to introduce Hapi, similar to node girls workshop.

**Comment by bradreeder** [comment]
Week 7 S-G-C notes:

##### Stop

* Replace makemehapi with step by step workshop like nodegirls
* Having a consistent weekly structure is good (strong approval)
* READMEs being generated are too complex, not for beginners (strong approval). Give 15 minutes to read them before presentation.

##### Go

* Code alongs are good but go slow with a readme to look back at for reference. Do testing alongside introductory workshop.
* Vote on top 3 things at end of SGC
* More node before hapi
* introducing morning challenges to recreate some parts of Hapi's API
* Longer on testing. How to test different parts of back-end. Real projects with tests.
* During projects making sure that everyone understands the code within a team

##### Continue

* Workshops and projects that allow groups to be creative. As long as there's an objective.
* Monday - Friday week. Regular week structure.
* External Alumni talk (Rafe's error handling) is good, but make sure difficulty and length of talk are taken into account.
*  Introduce project planning techniques into the course eg. user stories, user testing, project managing.
* Francesco's talk (server testing) - well paced, well thought through.

**Comment by SavageWilliam** [comment]
# Learning Outcomes

## HAPI Templates
- hapi
- inert
- vision
- handlebars
- cookie (light intro)

# Project

CMS Blog based
- database
- templates/views/handlebars
- session management with cookies

# Structure

## Hapi Templates
- Weekend
  - libraries/frameworks article

- Mon
  - 10:00 - 13:00
    - Brief talk on abstractions, libraries, frameworks
    - Code Along: Hapi Server + Inert (following hapi.js tutorial)
    - Make me Hapi (rephrased!! - SGC notes that too advanced wording)

  - 14:00 - 16:00
    - Intro to handlebars and vision workshop (Check andrews repo)
- Tue
  - 10:00 - 11:00
    - Justens handlebars challenge, tailored
  - 11:00 - 12:45
    - Hapi shot/inject workshop
  - 12:45 - 13:00
    - Intro to readme topics + teams
  - 14:00 - 18:00
    - Readmes
      - validation (joi)
      - Views (MVC?)
      - Session management (cookies)
      - caching
- Wed
  - 10:00 - 11:00 setting a cookie workshop (codealong?)
- Thu
- Fri

**Comment by bradreeder** [comment]
👍 

* Make sure in one of your workshops you show them how to use postgres with hapi/handlebars as they will have learnt how to use dbs with node core the prior week, and haven't used dbs with the hapi framework before.
* Unclear what you mean re: make me hapi in Monday's workshop. How are you going to change the phrasing of an external npm module you don't have control over?

Will come back to this if anything comes to me, including with existing resources you might consider using.

**Comment by msachi** [comment]
@bradreeder Thanks for the feedback.

Re: make me hapi, forking https://github.com/hapijs/makemehapi would allow us to make changes to the app, and it's possible to run the workshop by cloning the repo and running `node makemehapi.js`.

**Comment by bradreeder** [comment]
@msachi Cool, understood. I'm unsure what is considered typical polite practice regarding that @nelsonic (?) but my 2 cents:

If [makemehapi](https://github.com/hapijs/makemehapi) is a popular resource designed to teach beginners hapi, and all of your experience of the resource suggests that the phrasing is too advanced for beginners, then I think it would be more beneficial to everyone who uses that resource if you first raised an issue on the repo with suggestions for how you'd change the phrasing, and then make a PR if they give the go ahead.

If they don't get back to you then fork it with your changes and state in the README.md why you've made the changes. 

(I appreciate I said you could fork my repo in the node thread, but realistically my repo is only used by our students and I don't mind, where this is an opportunity to improve a popular open-source repo that effects more people than current students.)

**Comment by marisid** [comment]
Just to summarise our chat regarding the readme topics of the week, we decided to remove caching from the list and replace with "using helpers in handlebars" for the following reasons:
- Caching is a wider concept that is not just applicable in the Hapi week and not directly related to the weekly project.
- Given that our cohort doesn't have much knowledge on this topic, we should arrange for an alumnus or an external speaker to give a talk about this and how caching relates to web performance.
- If arranging a talk on caching is not possible, we could instead find a good resource to send around so that people get familiar with the concept.
- Helpers can be used efficiently when setting up templates and is something that can be directly used in the weekly project, so it feels like a useful topic to research.

**Comment by msachi** [comment]
**GitBook responsibilities**

Edit the files in [this](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-7) repo

- week schedule @msachi
- short summary & context on the week's theme
- learning-outcomes
- project
- research afternoon
- resources

**Workshop responsibilities**

Make your own repo / fork existing workshops, then add links to the schedule.

- Brief talk on abstractions, libraries, frameworks
- Hapi Server + Inert (following hapi.js tutorial)
- Make me Hapi
- Intro to handlebars and vision workshop
- Handlebars challenge
- Hapi inject workshop
- Setting a cookie workshop

For all edits to the master-reference repo, please fetch the branch `week-7-hapi-views` and make a new branch off that branch. Do all your commits in your new branch, and submit PRs to be merged to `week-7-hapi-views`. Finally (once we're done with everything) we will submit a single PR to be reviewed and merged into `master`.

**Comment by SavageWilliam** [comment]
@marisid @msachi  I'll begin on the [resources](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-7/resources.md)

**Comment by msachi** [comment]
A summary of our discussion on whether we should have separate or combined projects for weeks 7 and 8 (keeping in mind that Friday of week 8 is a holiday and so we need to squeeze 10 days' worth of material into 9 days).

Points in favour of separate weeks:
- our cohort feels strongly about keeping the Mon-Fri week structure as it is
- we would like to avoid having a weekend in the middle of the project, as it could mean that people would start working on projects from home
- separate projects would gives an opportunity to practice Hapi twice
- combining weeks' structure would mean a lot of learning up front

Points in favour of combined weeks:
- do not currently have two separate project ideas to build on
- would not have to start a new project from scratch, which would save time
- we could have s-g-c and/or presentations for both weeks together, which would save time

We decided to keep the weeks separate, but that the project for week 8 would involve building on the previous week's project. The teams of 4 would be divided into two pairs, each of which would implement OAuth separately. This would allow everyone in the team to learn the entire process of implementing OAuth (from access tokens to jwts).

We would keep the s-g-cs and presentations for both weeks, because removing them from week 7 would not give us any more time that we could spend usefully in that week. In week 8, the pairs would code-review each other's work, compare their approaches, and present in teams of 4.

We need to make sure that the two projects (blog and guthub login) are compatible. The OAuth project would focus just on authentication more than on requesting data from the GitHub API., so it could simply replace the existing login that students implemented in week 7.

Please add anything I missed @marisid @SavageWilliam @jsms90 @lucymonie @denesnori

**Comment by SavageWilliam** [comment]
"We decided to keep the weeks separate, but that the project for week 8 would involve building on the previous week's project" 

I'm just writing up hapi-views project outline...

Do you think we should make the students aware of this 'project-rollover' plan when we present the Hapi-views CMS project in week 7?? 

What effects might this have? And are there any benefits for not telling them until week 8? If we decide to withhold this plan we'd need to remove the info from Hapi-Oauth project file. 

Related: #34 

@jsms90 @msachi @marisid @lucymonie @denesnori

**Comment by SavageWilliam** [comment]
@msachi Shall we reformat [the schedule](https://github.com/foundersandcoders/master-reference/tree/project-hapi-views/coursebook/week-7) with days as headings, timings as bullet points?

**Comment by msachi** [comment]
@SavageWilliam Interesting question. I can't really think of any benefits for actively hiding this information from them. But equally, if we ask them to do a CMS with a login, then we can be sure that their projects will be 'ready' for week 8 additions, even if we don't let them know in advance. I'd say put it in the GitBook but don't worry them with it until week 8.

**Comment by bradreeder** [comment]
Week delivered. Thanks @SavageWilliam @msachi @marisid !
