### ISSUE TITLE
Week 8: Hapi auth

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#34]
This issue is intended for usage by mentor's who get assigned to Hapi auth week and for discussion around the week. As a single source for S-G-C notes and FAC9 feedback, discussion, external feedback, and to commit their work against for review.

**Comment by bradreeder** [comment]
FAC9 feedback #18 :

* We need an introduction to caching and temp storage.

**Comment by lucymonie** [comment]
Week structure

Week project: GitHub API app or Spotify API app (to be tested) with options for greater flexibility

Weekend pre-reading TBC

**Monday**
10-13.00 OAuth + GitHub API workshop part 1
LUNCH
14.00-16.00 OAuth + GitHub API workshop part 2 
16.00-18.00 - Business tasks

Tuesday
10-13.00 JWTs workshop
LUNCH
14.00-18.00 - Start projects

Wed-Thu
Project work

Friday
Holiday (Good Friday)

**Comment by bradreeder** [comment]
Shame about Good Friday. This is a weak area for me so only thing that comes to mind is whether it's possible to have the project build on top of the last week's project. If they're building a feature that involves auth/oAuth on top of something they've already started it might fit into the time frame more easily.

**Comment by des-des** [comment]
@lucymonie @denesnori. 

The relationship between cookies and jwt's.
We put the jwt in a cookie for your project. Would it have been easier to but it in the http header, lots of projects struggled with getting this working properly.
Have you got a working example of spotify oauth? It would be good if someone could have a crack at getting a minimal example working.
We recommended using the hapi-auth-jwt dwyl module. Was this useful? This module works with zero config if using http header instead of cookies. If cookies are not in this week where are they in the course.. They are important.

**Comment by jsms90** [comment]
Monday:

10:00-10.15 - Introduction to gitbook, learning outcomes & project teams. Start each week with a mission and a goal.
10.15-11:15 - Topic explanation ([whiteboard session with Eoin](https://github.com/FAC9/notes/blob/master/week8-oauth/OAuth_steps_board_schematic.JPG)
11.15-13.00 - [Workshop](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html)
--LUNCH--
14:00-16:00 - [Continue workshop](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html)
16:00-18:00 - Business Development / Community Engagement

Tuesday:
10:00-11:00 - Morning Challenge
11:00-12:45 - JWT Workshop
12:45-13:00 - Introduce project
--LUNCH--
14:00-17:00 - Group Project
17:15-18:00 - Q&A session or external speaker?

Wednesday:

10:00-11:00 - Morning Challenge?
11:00-13:00 - Group Project
--LUNCH--
14:00-18:00 - Group Project

Thursday:
10:00-11:00 - Code Review
11:00-12:40 - Respond to issues
12:40-13:00 - Prepare Presentations
--LUNCH--
14:00-15:00 - Classroom S-G-C
15:00-16:20 - Presentations (20 mins per group)
16:20-17:00 - Team Retrospectives (Team S-G-C)
17:00-18:00 - Upstairs Project / External speaker

**Comment by jsms90** [comment]
### Tasks:
Write "gitbook" week overview (Lucy)
Create introduction to topic - Whiteboard walkthrough / talk / passing notes around (Lucy)
Tweak Matt's workshop (Jen)
Write JWT workshop (Nori + help from Jen)
Write "targeted questions" for presentations (?)

**Comment by jsms90** [comment]
@emilyb7 

@lucymonie tells me that you two did swap weeks after all? Are you ok to do the tasks above that have "Lucy" next to them?

@denesnori & Emily - we need to assign the last two tasks to someone :+1:

**Comment by emilyb7** [comment]
@jsms90 we swapped *teaching* responsibilities but i'm involved in the planning of week 6, so don't intend to take on this week as well

**Comment by jsms90** [comment]
Ahhhhhh gotcha. Makes sense! @lucymonie was this you're understanding too?

**Comment by jsms90** [comment]
A summary of our discussion with week 7 mentors - copied from https://github.com/foundersandcoders/master-reference/issues/33#issuecomment-274067713

A summary of our discussion on whether we should have separate or combined projects for weeks 7 and 8 (keeping in mind that Friday of week 8 is a holiday and so we need to squeeze 10 days' worth of material into 9 days).

Points in favour of separate weeks:
- our cohort feels strongly about keeping the Mon-Fri week structure as it is
- we would like to avoid having a weekend in the middle of the project, as it could mean that people would start working on projects from home
- separate projects would give us an opportunity to practice Hapi twice
- combining weeks' structure would mean a lot of learning up front

Points in favour of combined weeks:
- do not currently have two separate project ideas to build on
- would not have to start a new project from scratch, which would save time
- we could have s-g-c and/or presentations for both weeks together, which would save time

We decided to keep the weeks separate, but that the project for week 8 would involve building on the previous week's project. The teams of 4 would be divided into two pairs, each of which would implement OAuth separately. This would allow everyone in the team to learn the entire process of implementing OAuth (from access tokens to jwts).

We would keep the s-g-cs and presentations for both weeks, because removing them from week 7 would not give us any more time that we could spend usefully in that week. In week 8, the pairs would code-review each other's work, compare their approaches, and present in teams of 4.

We need to make sure that the two projects (blog and guthub login) are compatible. The OAuth project would focus just on authentication more than on requesting data from the GitHub API, so it could simply replace the existing login that students implemented in week 7.

**Comment by jsms90** [comment]
### Week structure
I'm not convinced that we should interrupt them from working on their projects on Wednesday afternoon:
> 17:15-18:00 - Q&A session or external speaker?

They only have 1.5 days as it is.

As for Friday afternoon
> 14:00-15:00 - Classroom S-G-C
> 15:00-16:20 - Presentations (20 mins per group) - must answer 3 very targeted questions
> 16:20-17:00 - Team Retrospectives (Team S-G-C)
> 17:00-18:00 - Upstairs Project / External speaker

+ FAC10 have asked for presentations to be immediately after lunch
+ I'm not sure whether we need a team s-g-c at all. Especially since they will each have been working with only one other person this week. Plus, we will break for reading week immediately afterwards, so they can't use this as action points to improve on for next week - there is usually less enthusiasm for team s-g-c in weeks before a teams rotate.
+ We don't have an external speaker to fill the final slot at the moment. But this might be a useful time to do a Q&A session, to wrap up the 8 week curriculum?

**Comment by jsms90** [comment]
@lucymonie It would be really great to provide some kind of diagram that shows what you intend the whiteboard walkthrough to look like when it's finished
e.g. https://github.com/FAC9/notes/blob/master/week8-oauth/project-flow.jpg but maybe something that's not hand-drawn, or is just neater?
Just so that Nazareth don't have to make this bit up on the spot by themselves :+1:

**Comment by jsms90** [comment]
### Morning challenge
@denesnori has suggested something on currying

I feel like we may be better off providing something that's more directly relevant.
The students are missing out on research day this time because of Easter
[FAC9 research day - hapi](https://foundersandcoders.gitbooks.io/fac9/content/week5/readme_topics.html) - [what we produced](https://github.com/FAC9/READMES/tree/master/hapi)

[FAC9 research day - oauth](https://foundersandcoders.gitbooks.io/fac9/content/week8/readme_topics.html) - [what we produced](https://github.com/FAC9/READMES/tree/master/oauth)

[FAC10 research day - hapi](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-7/research-afternoon.md) - [what they produced](https://github.com/FAC10/research/#week-7---hapi-views)

**Comment by lucymonie** [comment]
Sure @jsms90. I am going to write an intro for the week, and do a balsamiq version of [this picture](https://github.com/FAC9/notes/blob/master/week8-oauth/project-flow.jpg). I guess it might be useful to write some notes for the mentors on what the aim is with this session, and how we envisaged it working.

**Comment by lucymonie** [comment]
Here is the diagram - feedback please!
![oauth-flow](https://cloud.githubusercontent.com/assets/16781258/24704297/f2fa3a4a-19fe-11e7-9ea3-ba306b1a4a37.png)

**Comment by lucymonie** [comment]
Has FAC10 done TLS? Should we do a TLS morning challenge?

**Comment by jsms90** [comment]
I doubt they would have heard of TLS at this point. I'm not sure where it would have come up in weeks 1-8.

Also, what would they do in a TLS morning challenge, other than set
> var options = {
    tls: {
        key: 'your_key',
        cert: 'your_cert'
    }
};
?

**Comment by lucymonie** [comment]
Improved version with database:

![oauth-flow](https://cloud.githubusercontent.com/assets/16781258/24807947/17d71374-1bb2-11e7-82bd-4c7b02b7ea74.png)

**Comment by jsms90** [comment]
@lucymonie Beautifully clear!

**Comment by jsms90** [comment]
This week has been _really_ tough to plan in advance! Because:
+ FAC9 had hapi before databases, so we had no idea how FAC10/FACN1's hapi project (including a database) was going to go. Given that we are designing week 8 to build on the projects from week 7, this has made _effective_ planning almost impossible to do in advance. We didn't know how much of authorisation they would be aware of / would have implemented & therefore what to teach
+ FAC10 in particular (not sure about FACN1) had a bit of a tough time during database week, so they didn't perform as many different queries during their database week project, or CRUD operations in their CMS (hapi week project) as FAC9 did during their database week. This directly impacts what FAC9 can be expected to do during their project e.g. different CRUD operations are available to different users based on their permissions (authorisation - scopes) 
+ During "OAuth" week (not "authentication" week for us), our cohort had a very fragmented conceptual understanding of the topic before beginning the project. This is because FAC9 covered everything about [session management e.g. cookies](https://github.com/FAC9/READMES/blob/master/oauth/cookies-and-local-storage.md), [hapi authentication](https://github.com/FAC9/READMES/blob/master/hapi/authentication.md#what-are-some-of-the-different-ways-hapi-implements-authentication), [hashing passwords](https://github.com/FAC9/READMES/blob/master/oauth/authentication.md#how-and-why-should-you-hash-user-passwords-and-sensitive-information-bcrypt-example), [JWTs](https://github.com/FAC9/READMES/blob/master/oauth/jwts.md))& [authorisation](https://github.com/FAC9/READMES/blob/master/oauth/authorisation.md#what-are-authorisation-scopes) during readmes.
+ We're trying to cover all of authentication during week 8 (as well as OAuth specifically), in 4 days instead of 5
+ Cookies & authentication were touched on in week 7 through [a morning challenge](https://github.com/SavageWilliam/hapi-auth-cookie-ws), but not well understood - https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-7.md

**Comment by jsms90** [comment]
Based on FAC10's stop go continue, and questions raised during project presentations, @lucymonie @sohilpandya & I decided to change the schedule for Monday slightly:
+ whiteboard walkthrough on authentication in general
+ whiteboard walkthrough on the oauth flow, followed by FAC10 passing pieces of paper around (same exercise that FAC9 did), to make this part more interactive & ensure that everyone fully understands the flow
+ workshop

**Comment by lucymonie** [comment]
Hey @sohilpandya here is the draft authorisation flow diagram. Please be merciless. I want to get this right :smile: 

![auth-cookie-flow](https://cloud.githubusercontent.com/assets/16781258/24829473/3ef01d9e-1c6a-11e7-9e62-990f3829637c.png)

**Comment by jsms90** [comment]
@lucymonie

Suggestions:
+ Put the words on step 2 the right way up? You could put it on the left hand side of the arrow so you have space
+ Step 5: better to pass in the `user_id` than `username` - they kept saying username during our week 8 because we weren't necessarily going to have a database

**Comment by lucymonie** [comment]
@jsms90 - any better?

![auth-cookie-flow](https://cloud.githubusercontent.com/assets/16781258/24829735/625283e4-1c6f-11e7-9bd6-020e5663bfae.png)

**Comment by sohilpandya** [comment]
Looks good, we can definitely work with this. 👍 ❤️ 

@jsms90 are we doing a workshop for this as well?

**Comment by jsms90** [comment]
I would probably change step 4:
> If not in database, store details

That's kind of the job of a "register" route, rather than a login route.

If they're not in the database, the server should return an error to the client. This could be a 404 page, but more helpful than that would be a view of the login page, but with an error displayed (e.g. handlebars if statement)

So step 3 would be: query database to check username and password

Step 4:
+ if not in database, return view with error message
+ if in database, use sub query to get user_id

Step 5: set cookie (this assumes that the user _was_ in the database i.e. user is authenticated)

I would probably also remove mention of the specific hapi syntax. It's nicer to leave the diagram purely conceptual & not specific to any particular technology.
I also don't think this is quite right in terms of the parameters that you pass to [`reply.state` in hapi](https://hapijs.com/api#serverstatename-options).
Besides that, they may never use `reply.state`, if they're using `hapi-auth-cookie`

**Comment by lucymonie** [comment]
@jsms, could you possibly argue this out with @sohilpandya? This is what we agreed I would use in the diagram. I am happy to change it if you come to a consensus.

**Comment by sohilpandya** [comment]
@jsms90 I was just doing a combined route for both login/register.

**Login**
- check it in database
  - if exists then save cookie
  - if not redirect user
**Register**
- Save it in database
  - save cookie

That way they know what happens in either case. Are you suggesting to only do one of the scenarios?

Also the hapi state params being incorrect is totally my fault, I was trying to remember them off the top of my head.

**Comment by sohilpandya** [comment]
Also this is mainly authentication and does not talk about authorisation. @jsms90 are we talking about both authentication and authorisation on Monday morning? We can make both of them pretty clear to them if you like?

**Comment by jsms90** [comment]
@sohilpandya I was going to comment on that too, but @lucymonie referred to this as an "authorisation" diagram:
> Hey @sohilpandya here is the draft authorisation flow diagram. Please be merciless. I want to get this right  :smile:

I thought it was just unfinished....

**Comment by jsms90** [comment]
I _definitely wouldn't recommend that we conflate logging in & registering. I imagine that most teams won't have these in the same route (only one FAC10 team connected them in the week 7 projects), and I think it is likely to cause confusion for that reason.

Either way, the main problem is that the diagram lays it out like one definitely comes after the other: step 3 -> 4 -> 5. It doesn't mention "if they _are_ in the database" i.e. step 3 -> step 5. That's just confusing as a flow diagram. Which then isn't helped by the fact that you might not deal with login & register at the same time.

**Comment by jsms90** [comment]
@lucymonie I know you don't have any more time to work on this, so would you mind uploading the bmpr file from balsamiq so I can continue to adjust it?

It should also go somewhere in the master-reference so that Nazareth can use it & students can reference something which is bound to be neater than whatever mentors manage to draw on the whiteboard :sweat_smile:

**Comment by sohilpandya** [comment]
OK, lets stick to one like you are suggesting rather than combining them. 

We can draw the authorisation on a whiteboard once we go through authentication. Does that work @jsms90

**Comment by jsms90** [comment]
No, they're totally different and I think FAC10 are slightly confused about authentication because they were half introduced to it in week 7, but not fully. I think, given that this is "hapi auth week" not "oauth week" any more, we should really go through this properly. It was a great idea to do a second diagram.

It's not the end of the world if we don't have a diagram sitting on the `master-reference`. It would just be nice to communicate what we mean to Nazareth, and for you and I to be on the same page about what we're going through on Monday. But they've got experienced people in Nazareth, and you and I can always speak in person. So, again, it's not the end of the world if they don't have a balsamiq diagram :smile:

**Comment by lucymonie** [comment]
Hey @jsms90, when @sohilpandya and I talked through this we discussed it being either login or registration, sorry this isn't clear from the diagram. I think the point is that either way there needs to be a cookie, so I personally wouldn't get too hung up on which route it is. I think @sohilpandya can clarify this on the spot. Apologies about the naming of the file also, I should have called it a login flow with cookie. I don't think these are major changes. However, I do need to know what params actually should be passed into the state method, or whether we are changing this to something else entirely. Could youse (as we say in Australia) please clarify what you'd like so I can update? Tara.

**Comment by lucymonie** [comment]
I don't know if this is what you want but the link to the diagrams is [here](https://github.com/lucymonie/OAuth) in case it's useful.

**Comment by sohilpandya** [comment]
@lucymonie the above is configuring the settings for a particular cookie. 

The way you can set a cookie is actually `reply.state("name", "value", options)`

where the options is an object that contains all of the things that you've mentioned in your above comment. 
```
{
    ttl: null,
    isSecure: true,
    isHttpOnly: true,
    encoding: 'base64json',
    clearInvalid: false, // remove invalid cookies
    strictHeader: true // don't allow violations of RFC 6265
}
```

**Comment by sohilpandya** [comment]
Also I'd recommend reading the first 3rd of this article https://oauth.net/articles/authentication/ if you haven't done so, hope it helps :)

**Comment by jsms90** [comment]
### Day 1 workshop
FAC9 were given [this workshop](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html) in week 8 with [this example solution]( https://github.com/matthewglover/oauth-workshop)
There is also [this by @des-des ](https://github.com/des-des/oauth-example)

I started off with the workshop that FAC9 were given, and then changed the instructions to be a bit clearer

Based on @lucymonie's suggestion and a lot of reading around the subject, I've added in a step for getting an [SSL certificate](https://github.com/foundersandcoders/oauth/blob/master/step2.md). It is extremely strongly recommended that OAuth is not performed over an insecure connection i.e. HTTP rather than HTTPS

It also seems really bad that we introduce the OAuth flow by doing something as insecure as setting an access token in a cookie, without encryption. [Step 5 & 6](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html) of that workshop. So I have removed this in favour of ending the workshop on [a brief explanation](https://github.com/foundersandcoders/oauth/blob/master/step6.md) of what is coming up the next day, with JWTs

I imagine that the workshop will now be much too short. After all, removing the last 2 steps takes away a big chunk of this workshop. And clarifying the instructions, as well as the fact that this cohort have had a stronger introduction to the previous weeks than FAC9, means that I think they will sail through this. FACN1 finished 1 hour early.

Week 7 didn't have quite enough time to introduce auth strategies and schemes properly. And we don't currently introduce these anywhere in our week. So we are now having a 30 minute slot on authentication (prior to the whiteboard walkthrough on OAuth). I'm thinking of creating a separate auth strategies & schemes workshop for FAC9 to do first.

That way, it would become:
#### Day 1
+ 10:00 - 10:15 - Intro to schedule, [summary](../summary.md) & [learning outcomes](../learning-outcomes.md)
+ 10:15 - 10:45 - Whiteboard walkthrough on authentication
+ 10:45 - 12:00 - Hapi Auth workshop
+ 12:00 - 13:00 - Whiteboard walkthrough on the [OAuth flow](../oauth-flow.png)
— LUNCH —
+ 14:00 - 16:00 - [OAuth workshop](https://github.com/foundersandcoders/oauth)
+ 16:00 - 18:00 - Business development

#### Day 2
+ 10:00 - 11:00 - Morning challenge
+ 11:00 - 12:45 - [JWT workshop](https://github.com/denesnori/fac10_jwt_workshop)
+ 12:45 - 13:00 - Introduce [project](../project.md)
— LUNCH —

**Comment by jsms90** [comment]
Given that we don't have a morning challenge (not yet anyway), and @denesnori 's workshop finishes with [something that continues from my Monday set up](https://github.com/denesnori/fac10_jwt_workshop/blob/master/04_hapi_oauth_jwt2.md) anyway, I propose that we change it further:
#### Day 2
+ 10:00 - 11:45 - [JWT workshop](https://github.com/denesnori/fac10_jwt_workshop)
+ 11:45 - 13:00 - [Continuation of OAuth workshop](https://github.com/foundersandcoders/oauth)
+ 12:45 - 13:00 - Introduce [project](../project.md)
— LUNCH —

where this continuation is an amalgamation of [steps 5-6 of the old workshop](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html) and @denesnori 's [step 4]((https://github.com/denesnori/fac10_jwt_workshop/blob/master/04_hapi_oauth_jwt2.md))

**Comment by jsms90** [comment]
@denesnori How long do you think your workshop would take them to complete? Also, what questions do you intend to ask them?

Do you think the above looks reasonable? Or would it not fill the time?

**Comment by jsms90** [comment]
As @des-des pointed out, JWTs aren't used for encryption
![image](https://cloud.githubusercontent.com/assets/15656538/24846497/dca7bdaa-1db2-11e7-915a-e1a40a422e48.png)

So [my earlier objections](https://github.com/foundersandcoders/master-reference/issues/34#issuecomment-292784476) to [steps 5-6 of the old workshop](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html) don't really apply.

Apparently, putting the access token directly into the cookie is fine (at least, now that we have step 2 and students are on an HTTPS connection: http://sitr.us/2011/08/26/cookies-are-bad-for-you.html)

Changes:
+ I've added a bit more explanation to that step & an article to read about HTTPS.
+ I'm also adding back in the steps for querying the github API
+ Adding a few missing pieces, flagged by Nazareth

**Comment by lucymonie** [comment]
I am just fixing the diagram for cookies now and will update the readme in a few minutes in case you want to use it. I must say I am pretty horrified at the extent to which this subject was not taught correctly to us, and that we were about the pass that unsavoury gift on down the line...

**Comment by jsms90** [comment]
My comments to Nazareth on April 9th (Day 1):

### Changing the schedule / workshops for tomorrow
I'm working on a second half to the Monday workshop
(I don't want to push it unless I get it finished, since students know to look at the branches for a solutions branch, and might be confused if they see a half finished 2nd workshop)
This could potentially be a replacement for step 4 of the JWT workshop, based on Sohil's point https://github.com/foundersandcoders/master-reference/pull/219#issuecomment-292744166
### Known gaps in the current set of material, that could impact the project
Our 2 workshops, as they currently stand, don't explain hapi's schemes and strategies.
They also don't explain settings cookies (I don't know how FACN1 coped with last week's morning challenge on cookies but some bits confused FAC10 & I don't think it was enough as an intro by itself)
They also don't cover storing the access token!! Which was in step 5 & 6 of the old workshop
That's a lot of stuff missing for when they begin the project. So I would spend tomorrow morning trying to make sure that they're confident on all of that.
### If there is time left over tomorrow morning
Even if Nori and I don't finish the extra material in time, it's probably enough just to write a few bullet points on what they have to do, and point them to the hapi docs (that was largely how FAC9 learnt during hapi week anyway)
### Day 3 morning challenge instead
You guys could potentially do a morning challenge of some sort on the morning of day 3 though, if you wanted? FAC10 just doesn't have the time, so I didn't prioritise preparing one 
You guys are a lot more experienced than me, so maybe you can knock something together by tomorrow morning? Otherwise, here is a link to FAC9's morning challenge

**Comment by jsms90** [comment]
### Intro to authentication
**Notes for Nazareth**
I started writing something here that was going to give them an intro into what FAC10 have had so far - hapi-auth-basic & bcrypt but I stopped pretty quickly
They still have Nori's workshop to go through, which might take them quite some time.

**What I did for FAC10**
[hapi authentication morning challenge](https://github.com/jsms90/hapi-authentication-workshop)

**Comment by jsms90** [comment]
### Nazareth research topics (made by @mcelearr )
+ What is a JSON web token(JWT)? https://github.com/foundersandcoders/jwt_workshop/blob/master/Step2.md
+ JWTs under the hood. https://github.com/foundersandcoders/jwt_workshop/blob/master/Step3.md
+ Hapi auth schemes and strategies
+ Hapi auth cookie (we didn't do it last week)

**Comment by jsms90** [comment]
### London Day 2 - Continuation of OAuth workshop
I tried to add a new branch to my Monday workshop, to replace step 4 of Nori's workshop (since it built on Monday's anyway) but didn't know enough about JWTs in advance to finish in time.

So I focused on reading through Nori's workshop & roped @sohilpandya and @mantagen into helping me to deliver it.
[Not a roaring success](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-8.md) :disappointed:

**Comment by bradreeder** [comment]
Week delivered. Thanks @lucymonie @jsms90 @emilyb7 @denesnori !
