### ISSUE TITLE
WebSockets + Redis

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/master-reference#35]
This issue is intended for usage by mentor's who get assigned to Redis week and for discussion around the week. As a single source for S-G-C notes and FAC9 feedback, discussion, external feedback, and to commit their work against for review.

**Comment by bradreeder** [comment]
FAC9 feedback #18 :

* Concern that extra support from alumni will be needed as they haven't covered the topics before.

**Comment by bradreeder** [comment]
@tbtommyb @RhodesPeter @denesnori 

Given you haven't looked at this topic before I thought it would be a good idea to link you some resources you might look at in advance of curriculum planning over the holidays.

These are what I've found from a quick scour of the dwyl repo's:

https://github.com/dwyl/learn-redis
https://github.com/dwyl/learn-websockets

Trying to build a small real-time chat app like [this](https://github.com/dwyl/hapi-socketio-redis-chat-example) using these technologies might be a good way of learning it and reinforcing your server-side knowledge from the course.

@des-des Are they going to be teaching sockets.io or websockets? Also, can you think of any other good learning resources they might use?

**Comment by RhodesPeter** [comment]
FAC8 ran a Redis week which can be found [here](https://foundersandcoders.gitbooks.io/fac8/content/week5/).

**Comment by RhodesPeter** [comment]
There is a useful page that Nori found on SQL vs noSQL databases [here](http://www.thegeekstuff.com/2014/01/sql-vs-nosql-db/?utm_source=tuicool).

**Comment by RhodesPeter** [comment]
[Here](https://www.pubnub.com/blog/2015-01-05-websockets-vs-rest-api-understanding-the-difference/) is an article on the difference between REST and WebSockets.

**Comment by denesnori** [comment]
Which websocket library should we choose? Socket.io/ engine.io/ Primus/hapi plugin nes?
@bradreeder  , @des-des  do you have any suggestions or arguments for/ against any of them?

**Comment by RhodesPeter** [comment]
Here is our **very** rough outline for the week:

**Topics**:
1. Redis
2. Pub/Sub
3. WebSockets
4. SQL vs. NoSQL databases
5. In-memory database/store

### **Monday**:
1. Introduction to Redis and Websockets 10-11am
2. Morning challenge - [try.redis.io](try.redis.io) workshop 11am - 11.45am
3. Sockets.io [Get started: chat application](http://socket.io/get-started/chat/) workshop 11.45-4pm
4. Business development / community engagment 4-6pm

### **Tuesday**:
1. Morning challenge (content TBC) 10 - 11.30pm
2. Redis/WebSockets READMEs 11.30 - 5.30pm
3. Project Intro 5.30-6pm

### **Wednesday**:
1. Morning challenge (content TBC) 10 - 11.30pm
2. Group projects 11.30 - 6pm

### **Thursday**:
1. Group project all-day with the potential to have a guest speaker at around 5pm. 
 
### **Friday**:
1. Code review 10-11am 
2. Respond to issues 11-1pm
3. Group SGC 2-3pm
4. Present projects 3pm-5pm
5. Team STG 5-6pm

**Additional Technology**:
[nes module](https://www.npmjs.com/package/nes)
[sockets.io](http://socket.io/)

**Comment by tbtommyb** [comment]
Good work 👍 .

Do you think it might be clearer to do Redis/NoSQL on one day and then WebSockets the following day, rather than a bit of both? I just worry that people will be unclear about the distinction between the two if we introduce them together and intermingled.

I understand the Hapi people are doing a CMS for their projects. If we could find some way to link the weekly project to that it would give great continuity (perhaps a chat widget?).

**Comment by des-des** [comment]
@denesnori @RhodesPeter 

I think this is looking good!

In terms of the resource you have posted for the chat workshop, I do not think it will take more than a couple of hours.

Have you looked at the dwyl chat example. I think there is some complexity here. Do you think you can present this in a way the students understand. If the project is redis / websockets I think we need to understand the question: Why / how is redis useful here!

**Comment by jsms90** [comment]
:wolf::wolf::wolf::wolf:@bradreeder said I could close this:wolf::wolf::wolf::wolf::wolf:

**Comment by sofer** [comment]
I am re-opening this, have removed the Week and also removed the FAC10 label. I am not entirely convinced that losing WebSockets and Redis is a good idea. I am not quite sure which week it belongs in and I don't know that we will have room for it in FAC10, but I would hate to lose sight of this outline week, in case we want to bring it back. This might also be an opportunity to give promises an airing (I am not sure that we explicitly cover them anywhere else).

**Comment by jsms90** [comment]
@sofer @bradreeder @des-des I completely agree that we should work promises & websockets into the curriculum somewhere. But could we reopen / start a new issue that includes a link to this one, once we have an idea that is actionable?
Otherwise I am afraid that we will just have an extremely long list of issues, some of which are never going to get picked up. If we want to encourage people to be actively involved in contributing and making improvements, we should clean up the issues so that the backlog doesn't look longer than it needs to be.

**Comment by bradreeder** [comment]
@jsms90 I agree. I've fallen away from tidying this place while other things have been on my mind. But I will make sure to get up to date with this repo and start thinking about how we should organise the issues going forwards.

**Comment by nelsonic** [comment]
All for learning **Redis** and PubSub with WebSockets. 😍 
However `Promises` in the same week, not so much... 😕 

> Anyone _considering_ teaching `Promises` to novices, 
should watch: ***The Post JavaScript Apocalypse***: https://youtu.be/6Fg3Aj9GzNw
(_both an interesting history lesson and a deep insight into the state of JS... 
also... the **reason** why I reluctantly agree with [TJ](https://medium.com/@tjholowaychuk/farewell-node-js-4ba9e7f3e52b) ..._) 😢 

> introducing **WebSockets** _definitely_ does not _need_ `Promises`. 🤔 
**IMO**: ***Streams*** are a _much_ more _useful_ technique/abstraction to use when learning about WebSockets and PubSub with Redis as Streams are the _natural_ way of processing/piping a Stream of data ... see: https://github.com/substack/stream-handbook 💡 💧 
_ask_ @rjmk why using _streams_ is a _good_ idea... 💬 
We should cover ***Streams*** at the _start_ of "Node Week(s)"

`if` you are going to introduce people to `Promises`:
1. ***Explain*** `Promises` ***independently*** of any other tool/technology (_so people don't `falsely` think they **need** `Promises` in order to use WebSockets or Redis PubSub; that's misleading and confusing_) 😖  
There a few good resources for this: 
  + https://developers.google.com/web/fundamentals/getting-started/primers/`Promises`
  + Learn JavaScript `Promises` in about 70 minutes: https://qntm.org/promise
  + You're Missing the Point of `Promises`: https://blog.domenic.me/youre-missing-the-point-of-`Promises`/
  + Thinking Sync in an Async World: https://youtu.be/wc72cyYt8-c
  + Futures and `Promises` in JavaScript: http://davidshariff.com/blog/futures-and-`Promises`-in-javascript/
  + Discussion: "Aren't `Promises` just callbacks?": http://stackoverflow.com/questions/22539815/arent-`Promises`-just-callbacks
2. Teach people to _chain_ `Promises` not _nest_ them! https://twitter.com/lennym/status/805805375282905088 🤣 
3. ***Convey*** to people that `Promises` are [***Not Supported*** by Internet Explorer](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility) (_and will never be_) 
and as such to _use_ them in the browser you will need a Polyfill/Library for 25% of Users http://caniuse.com/#feat=`Promises` so the Promise-based code will be (_by definition_) _slower_ than callbacks/streams/events for _most_ tasks on both Client & Server. 🐌 
4. _ensure_ that people ***understand*** that _using_ `Promises` is not _just_ "_an alternative to callbacks_" it's a "_different way of thinking_" the same way that FP is a different way of _thinking_ from Imperative. 
5. `expect` it to be come the "_hammer_" that gets used to "_solve_" **all coding tasks**. 
see: https://en.wikipedia.org/wiki/Law_of_the_instrument 🔨 
and  `expect` that _many_ people will not broaden their horizon to use streams/pipelines once they get _stuck_ on `Promises`. 🔚 

Someone _can argue_ that because there are [`Promises` in Haskell](https://hackage.haskell.org/package/future-2.0.0/docs/Control-Concurrent-Future.html) (_a purely functional language_),
 _surely_ they are a "good thing", right...? 
[_maybe_](https://gist.github.com/briancavalier/3296186) ... 

`if` you _want_ to use `Promises` because they _seem_ like a _good_ idea or _sound_ cool, fair enough. 😉 
Just make _sure_ people _understand_ ***why*** they are being taught/used 
and not just "_because everyone's doing it..._" 🙃 
because _statistically, **everyone** is **not** using `Promises`_. 📊 

> I'd be _curious_ to see the _actual_ frequency analysis the _usage_ of: 
https://www.npmjs.com/package/async 
https://www.npmjs.com/package/run-async
https://www.npmjs.com/search?q=async&page=1&ranking=popularity
vs. all promise libraries e.g: 
https://www.npmjs.com/package/promise
https://www.npmjs.com/package/bluebird
https://www.npmjs.com/package/q
https://www.npmjs.com/package/es6-promise
https://www.npmjs.com/package/co
https://www.npmjs.com/package/pify
etc... 💭 

people who went to Douglas Crockford's talk last week will have heard 
that there are "_simpler_" ways of doing Asynchronous JS _without_ `Promises`
which DC described as "_incomplete_"...
but then what does _he_ know...? 👍

**Comment by des-des** [comment]
In the last cohort, I pushed for teaching the waterfall / batch patterns (if you can call them that). I think this was a good was of showing people that there are ways of dealing with callback hell that do not involve promises. That said, students should defo learn how to use promises, as they are used a lot.

**Comment by nelsonic** [comment]
@des-des agreed. worth _learning about_... 🤔 
However, no promises here: http://package.elm-lang.org 😉

**Comment by bradreeder** [comment]
This didn't end up happening for FAC10. We did #36 instead.
