### ISSUE TITLE
week 3 schedule - split software architecture workshop in two, change parallel function mc

### ISSUE THREAD

**Issue by edgarfinn** [foundersandcoders/master-reference#359]
To reflect changes in #300 

- Replacing Stackoverflow workshop with architecture white-boarding workshop, modular design workshop and flexbox workshop. 
- Revert to just one parallel functions morning challenge (Besart's)
- Link 'Introduce Projects' on Day 2 to the wk 3 projects file

**Comment by lucyrose93** [comment]
@smarthutza we need to add your flexbox workshop link then this is done

**Comment by jsms90** [comment]
Remember, branches and therefore PRs should be based on _features_ (e.g. a workshop within the week) rather than individual files (e.g. every change to the week schedule).

After all, a PR like #409 then relies on all of the other changes being complete first. So you get problems like the fact that we can't add the white-boarding workshop to the schedule until the flexbox workshop is finished.

If you treat each feature separately, their addition to the schedule can operate independently.

---

> we need to add your flexbox workshop link then this is done

@smarthutza can deal with adding the flexbox workshop to the schedule as part of issue #339 

> Replacing Stackoverflow workshop with architecture white-boarding workshop, modular design workshop and flexbox workshop.

This will be dealt with in issues #336 & #317 

> Revert to just one parallel functions morning challenge (Besart's)

Looks like this is being dealt with as part of #337 - see PR #408

**Comment by eliascodes** [comment]
Closing planning issue, since the week is over and this was done in #449.
