### ISSUE TITLE
Business development/community engagement

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#38]
I was really hoping that business development and community engagement be seen as two separate things. See https://github.com/foundersandcoders/business/issues/116. 

I really do think that we need to step up both our business engagement (to generate income and work opportunities) and our community engagement (to meet our wider social goals) and I don't think that 2 hours per person per week is going to cut it.

Do we have room in the curriculum (perhaps on Tuesday afternoon) for an extra two hours of extra-curricular activities?

**Comment by bradreeder** [comment]
@sofer I put them into a single slot only as it's been requested by the feedback I've collected so far - I agree we need more community engagement and would want to be personally involved in teaching schools, I just think we need to discuss seriously what will need to be adapted or removed in order for this to work. This issue is related (the comment on merging them is there): #27 

Monday + Tuesday are our main teaching days. Including lunch, this means we'd only have 10 hours of teaching time prior to projects on a course that's already quite intense. I think we should think about this carefully and involve more people in the discussion.

**Comment by bradreeder** [comment]
If we were to have two 2 hour slots this would be my initial suggestion. Happy to think of more:

Firstly, only have 1 external speaker a week maximum. On top of that, drop readme afternoons (related #17). Instead start projects on Tuesday afternoon and incorporate into the project group research time, on a focused set of themes we know they'll need for the project.

**Comment by iteles** [comment]
I've answered this on the original issue 👍

**Comment by bradreeder** [comment]
Issue closed as discussion was continued here: https://github.com/foundersandcoders/business/issues/116

10% time can be allocated to a 2hr slot per week during weeks 1-10 as long as we find a way to make up the quota in other weeks. i.e. #14
