### ISSUE TITLE
introduce a few git commands each week

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#416]
+ [requested by FAC10](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-1.md#go-1)
    > Git shortcuts - pepper more throughout the rest of the weeks?
    > Mentors to add a few commands to the beginning of each week / each project (Jen can help with this)
+ [requested by FAC11](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-11/cohort-week-1.md#stop)
    > Few git commands to be taught to students every week.

**Comment by jsms90** [comment]
Basics:
+ `git config`
+ `git init`
+ `git log`
+ `git diff`
+ `git fetch`
+ `git stash` & `git stash pop`
+ `git mv` & `git rm` rather than just `mv` or `rm`, so that a file isn't treated as being deleted & re-added & the history is preserved
+ using `git checkout` for commits (not just branches)

More:
+ `git tag`
+ `git reset`
+ `git rebase -i`
+ `git remote` e.g. `git remote -v`, `git remote add origin <path>` & `git remote set-url`
+ `git commit --amend`
+ `git revert`

**Comment by ZooeyMiller** [comment]
For this week (week 2) I feel like introducing them to the habit of going `git branch` to check what branch you're on before doing any adding and committing, and learning to use `git stash` and `git stash pop` would be really useful.

**Comment by jsms90** [comment]
@finnhodgkin @oliverjam Could you detail exactly what you gave to FAC11 yesterday?

**Comment by oliverjam** [comment]
We talked about `git stash` and `git stash pop` as a way to move your uncommitted changes to a new branch if you're accidentally working on master.

We also introduced `git reset HEAD~` to undo the last commit, and `git commit --amend` to amend the last commit.

**Comment by zurda** [comment]
We did week 2 and mentioned `git stash`, `git status`, `git branch`. I think different mentors will bring up different commands they use often, and this comes up naturally during the week. I think for FAC-16 there's also a talk about git workflow by @onwordi

**Comment by oliverjam** [comment]
FAC students tend to come out of the course with a pretty great practical understanding of how to use basic git commands to get their work done (if only because they have to use them multiple times a day every day).

I'm not sure everyone ends up understanding how git actually works, which is necessary for understanding some of the more advanced features, but this isn't too important for a short bootcamp.

Maybe it would be a good idea to cover some more advanced git a bit later in the course once everyone is comfortable with the general workflow.

This issue can probably be closed now though—unless we think we should formalise the "mentors show a few extra git commands" thing in the curriculum somehow?
