### ISSUE TITLE
Should we introduce / allow flexbox in the course (in general and/or in week 1)?

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#425]
Most students have come across flexbox now before they arrive at FAC. Those who haven't get introduced to it by those who have.

+ FAC9 were given flexbox froggy as a week 1 morning challenge and then told categorically that we weren't allowed to use it in our projects.
+ FAC10 & FAC11 have both raised questions about why this is a contentious issue. Both have used flexbox in their first week projects (and FAC10 beyond).
+ I don't think it has ever been made clear to FAC10 why anyone disagrees with having flexbox on the course

Given the proposal that was passed around introducing more HTML & CSS into the course, the week 3 mentors are writing a flexbox workshop / morning challenge. [Here is the hypothesis around the benefits this will bring to students](https://github.com/foundersandcoders/master-reference/issues/339#issue-237535310)

From FAC11 SGC
> Flexbox workshop in week 1 (@Jen-Harris)
>
>  + Flexbox not fully supported.
>  + You're denying the users which don't have access to modern browsers/systems from being able to access your product.
>  + An introduction to some form of positioning, what's best practice, rather than relying on flex-box.
>  + Learn-layout on pre-course, but Minesh found not intuitive. So some other resource on position to set for pre-course.
>  + Look into FreeCodeCamp beta which might help

**Comment by eliascodes** [comment]
I'm fully in favour of having flexbox on the course now. In the past the main argument against it (AFAIK) was from a browser compatibility point of view. 

To address the arguments in the OP in turn:
* Flexbox not fully supported.
  * Support is actually [really good now](http://caniuse.com/#search=flex)
* You're denying the users which don't have access to modern browsers/systems from being able to access your product
  * Legacy support of this kind is going to become an increasingly niche skill that is unlikely to provide much value to students. There aren't that many applications/products whose user base really warrants targeting < IE10.
* An introduction to some form of positioning, what's best practice, rather than relying on flex-box.
  * I don't agree with this framing of flex-box, as though it is separate from CSS positioning. It is part of the CSS standard. Using flexbox is no more cheating than using `Array.from`.

**Comment by sohilpandya** [comment]
We should use it but make sure they are aware of the limitations of it especially related to IE.

**Comment by ZooeyMiller** [comment]
I very much agree with @eliascodes sentiments.
I would be pro the use of and teaching of flexbox from early. With the caveat that if you wish to support older browsers (none of the user stories on any of the projects for FAC10 at least specified this as a user story) you need to use a fallback, but I think that that is a relative rarity. 
So, yes to flexbox! :heart_eyes:

**Comment by jsms90** [comment]
For the record, I remain stoically impartial. I don't have remotely enough knowledge on the subject to comment on whether it would be good or bad to introduce.

I'm purely interested in facilitating a conversation between those who have opinions on either side of this question, as it has appeared contentious in the past and never been well resolved.

**Comment by msmichellegar** [comment]
What @eliascodes said. Flexbox FTW 👍

**Comment by oliverjam** [comment]
Unsurprisingly I am also very pro flexbox. I feel like the modern layout techniques that were actually designed for laying out pages should be the default, and fallbacks for older browsers should be taught _as fallbacks_ (when a project requires them). 

I would like to ask anyone who thinks we shouldn't teach it because browser support isn't there yet: what level of support would be required for us to teach it? Or is the fact that IE8 will probably be around forever in some industries/locales a reason to never start using it?

**Comment by eliascodes** [comment]
@jsms90 given that flexbox is now explicitly part of week 3, and there doesn't seem to be any dissenting voices, can we consider this closed?

**Comment by jsms90** [comment]
@eliascodes Given the fact that there have been conflicting opinions in the past, I'm not sure that the discussion above sufficiently reflects the will of the whole community (I may be wrong).

Since this issue has only been open for a couple of weeks, I wouldn't advise closing this issue so quickly. I doubt that most alumni check `master-reference` so regularly. Historically, when issues aren't fully hashed out, this [causes problems](https://github.com/foundersandcoders/international/issues/79#issue-238913987)

In order to benefit from the fact that FAC has been running for so many cohorts, we need an effective means of hearing from our alumni network on these types of curriculum-wide questions. I don't think we have figured that out yet.

**Comment by jsms90** [comment]
Flexbox remains part of week 3 & there don't seem to be any objections any more.

Closing :+1:
