### ISSUE TITLE
Create "making an accessible drop down" workshop for week 4

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#442]
This is reliant on #441 
We want to make a workshop teaching how to create accessible dropdowns in week 4, this is informed by the passed proposal #258 

The choice for an accessible drop down is based on the fact that the proejct for the week is an autocomplete, which will need some kind of drop down menu. 

I will add problem/solution/hypothesis to this issue at a later date.

**Comment by ZooeyMiller** [comment]
Once this is done we will need to update the week schedule to reflect changes, this workshop will replace the tape workshopa s detailed in #297

**Comment by jsms90** [comment]
Some resources that should help
[accessibility video by google](https://webaccessibility.withgoogle.com/unit?unit=1&lesson=5) - excellent resource!!

articles:
+ http://terrillthompson.com/blog/202
+ https://www.lynda.com/Business-Accessibility-tutorials/Creating-accessible-drop-down-menu/89051/94612-4.html
+ http://webaim.org/techniques/forms/controls#select

**Comment by yvonne-liu** [comment]
@jsms90 @ZooeyMiller this is a good resource. I think there was some confusion with wording but our intention is to teach how to make an accessible autocomplete search bar (that ties in more with week 4 project): 

https://alphagov.github.io/accessible-autocomplete/examples/

**Comment by yvonne-liu** [comment]
More resources: 

https://www.marcozehe.de/2014/03/11/easy-aria-tip-7-use-listbox-and-option-roles-when-constructing-autocomplete-lists/
http://www.bu.edu/webteam/clrux/accessibility/autocomplete/autocomplete.html
http://www.visionaustralia.org/digital-access-autocomplete

**Comment by jsms90** [comment]
@yvonne-liu yeah absolutely :+1: maybe a bunch of links wasn't as helpful as I could have been. Also, I linked you to the wrong section of the google video before - [this is the lesson on autocompletes](https://webaccessibility.withgoogle.com/unit?unit=6&lesson=13)

http://terrillthompson.com/blog/202 - Even though you're creating a dropdown from an autocomplete, rather than a menu within a navbar, the following tips from the article are still relevant:
+ Aria Roles e.g. `role="menuitem"`
+ > Pressing enter, space, or down arrow on a top-level menu item should trigger the display of the dropdown or flyout menu if one is present, and pressing escape should close it and return focus to the parent menu item.

    If you're not sure how to deal with focus management, there's another google video which might be useful https://www.youtube.com/watch?v=x18vEEfpK3g&feature=youtu.be&t=30m05s

The last link I gave you is probably not very helpful. You don't want to use a select element really :sweat: The option element with `listbox` is better :+1: 

With respect to your last link though, I wouldn't advise showing them externally created libraries / widgets this early in the course.

**Comment by jsms90** [comment]
[This is a good list for potential user stories](http://uxmastery.com/anatomy-of-an-accessible-auto-suggest/) that you might add to the project brief, with a bunch of ideas about how you could satisfy them.

[`aria-live`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) is also useful
> aria-live="polite" indicates that the screen reader should wait until the user is idle before presenting updates to the user. This is the most commonly used value, as interrupting the user with "assertive" might interrupt their flow.

When in doubt, always look to [the government's advise on accessibility](https://designnotes.blog.gov.uk/2017/04/20/were-building-an-autocomplete/) :heart_eyes: 

This took me to [this example](https://github.com/UKHomeOffice/typeahead-aria). There are so many things you could do, it's crazy. [For example, this is a nice touch](https://github.com/UKHomeOffice/typeahead-aria/blob/master/src/typeahead/menu.js#L82-L99)

[Another example here](http://www.oaa-accessibility.org/examplep/combobox6/)

**Comment by yvonne-liu** [comment]
We've decided to not go forward with this morning challenge because it's not something that can be completed in an hour. Instead, we're going to put back the original four-hour slot for the Node Girls workshop (per @bradreeder's suggestion of his FAC8 experience).
