### ISSUE TITLE
build workshop 2 - Templating with Handlebars

### ISSUE THREAD

**Issue by PiotrBerebecki** [foundersandcoders/master-reference#466]
Link to workshop: https://github.com/PiotrBerebecki/express-handlebars-workshop

Use Marina's [workshop readme as example](https://github.com/foundersandcoders/handlebars-hapi-intro-workshop)
@marisid how do you feel about using your readme here?

**Comment by marisid** [comment]
Hey @PiotrBerebecki and @Akin909  - glad that you'll be teaching `express` to FAC11! Looking forward to seeing your repo. 

Of course you can use my readme as your base. Just make sure you adjust the wording where the text is "coupled" to `hapi`. Also, it would be good to reference (maybe at the end of your readme?) the `handlebars-hapi-intro-workshop` [repo](https://github.com/foundersandcoders/handlebars-hapi-intro-workshop) as a way to compare the use of a templating engine with different Node frameworks (`hapi` and `express`). 

This will also reinforce the idea of how libraries/frameworks/engines can be "glued" together depending on your project and following the relevant documentation so that there is no _single_ best way of setting up an app or a server. Love the idea:)

**Comment by PiotrBerebecki** [comment]
@jsms90 @des-des We've developed the code-along Handlebars workshop for Express week-8: https://github.com/PiotrBerebecki/express-handlebars-workshop

Could you please review it and let us know if anything in the `solution` can be improved.

@Akin909

**Comment by jsms90** [comment]
@PiotrBerebecki post in the `summer-cohort-planning` gitter channel :+1:

**Comment by des-des** [comment]
@PiotrBerebecki I have dropped a comment into the pull on MR
