### ISSUE TITLE
specify who is responsible for different elements of "new cohort checklist"

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#472]
The current checklist says the Course Facilitator is responsible for everything. This is what we want to move to.

Selection panel:
+ Send acceptance email to successful candidates, including a link to the precourse material

Biz dev task group + point person:
+ Send contact email (via mailchimp) out to FAC alumni to begin arranging external speakers dates for the new curriculum.
+ Use the Google spreadsheet of past alumni who gave talks / external speakers, stored in school-curriculum, to continue arranging external speaker dates for the new curriculum. Update the list from last curriculum if necessary.
+ Update the calendar every time a speaker is arranged.

Course Facilitator:
+ Introduce current mentors to the gitter chatroom for current-mentors under the foundersandcoders organisation.
+ Create a new github organisation for FAC-X with the following structure. Example.
+ Add new and previous cohort as owners to this FAC-X Github organisation, then create a students team and a mentors and add everyone accordingly.
+ Create a gitter chatroom for FAC-X within the foundersandcoders organisation, and delete the "incoming"/"lobby" room.
+ Add new cohort to Founders & Coders organisation.
+ Add new cohort to a FAC-X team within this organisation.
+ Invite the new cohort in for an installation party in the last week of FACX-1 to meet each other and mentors.
+ Arrange dates, and ensure alumni are notified, for a welcoming party in the first week. Add to the calendar.
+ Send email out to alumni and those active in space about start-date of course to increase numbers on the first day.

All Course Facilitators / maintainers of the `master-reference`:
+ Ensure all curriculum related files are updated: those in the coursebook general folder & the curriculum (London, Nazareth) repo.
+ Ensure the coursebook has been updated by the current mentors before start-date.

**Comment by sohilpandya** [comment]
I would remove the following items from the list
+ Send acceptance email to successful candidates, including a link to the precourse material
+ Use the Google spreadsheet of past alumni who gave talks / external speakers, stored in school-curriculum, to continue arranging external speaker dates for the new curriculum. Update the list from last curriculum if necessary.
+ Update the calendar every time a speaker is arranged.
+ Arrange dates, and ensure alumni are notified, for a welcoming party in the first week. Add to the calendar.
+ Send email out to alumni and those active in space about start-date of course to increase numbers on the first day.

**Comment by sofer** [comment]
@sohilpandya fair enough. We do need to make sure these tasks are done though and I would say that in the past these tasks have not always been done well. Have you got a clear idea of who's remit these tasks should fall under?

**Comment by rebeccaradding** [comment]
@sofer it looks like @jsms90 has edited her top comment already, perhaps to reflect @sohilpandya's suggestions. @jsms90 @sohilpandya could you please clarify?

**Comment by jsms90** [comment]
@rebeccaradding I edited the top comment 4 days ago. @sohilpandya commented 2 days ago.

This issue was created to clarify whose responsibility each task should actually be, because @sohilpandya and I both agree that the Course Facilitator doesn't need to be the one doing all the things on the list.

So I'll just echo what @sofer has said. These tasks need to be done by someone. The question is simply by who? What do you think @sohilpandya?

**Comment by yvonne-liu** [comment]
Since this issue is still open, I'm just going to comment here and open for a discussion with the current CFs for FAC12, FACN3, and FACG3 (Week 1-4). 

This [checklist](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/new-cohort-checklist.md) needs to be updated.

My suggestions are a little different from @jsms90 since a few thing's changed: 

A member of FCI or the next cohort's CF: 
+ Send acceptance email to successful candidates, including a link to the precourse material

Unclear, programme director, designated task group, open for discussion: 
+ Send contact email (via mailchimp) out to FAC alumni to begin arranging external speakers dates for the new curriculum.
+ Use the Google spreadsheet of past alumni who gave talks / external speakers, stored in school-curriculum, to continue arranging external speaker dates for the new curriculum. Update the list from last curriculum if necessary.
+ Update the calendar every time a speaker is arranged.

Course Facilitator:
+ Introduce current mentors to the gitter chatroom for current-mentors under the foundersandcoders organisation.
+ Create a new github organisation for FAC-X with the following structure. Example.
+ Add new and previous cohort as owners to this FAC-X Github organisation, then create a students team and a mentors and add everyone accordingly.
+ Create a gitter chatroom for FAC-X within the foundersandcoders organisation, and delete the "incoming"/"lobby" room.
+ Add new cohort to Founders & Coders organisation.
+ Add new cohort to a FAC-X team within this organisation.
+ Invite the new cohort in for an installation party in the last week of FACX-1 to meet each other and mentors.
+ Arrange dates, and ensure alumni are notified, for a welcoming party in the first week. Add to the calendar.
+ Send email (Gitter message?) out to alumni and those active in space about start-date of course to increase numbers on the first day.

Weekly curriculum task group along with current CF / maintainers of the `master-reference`:
+ Ensure all curriculum related files are updated: those in the coursebook general folder & the curriculum (London, Nazareth) repo.
+ Ensure the coursebook has been updated by the current mentors before start-date.

@astroash @shiryz @ZooeyMiller @rebeccaradding @sofer

**Comment by astroash** [comment]
I would also suggest adding 'Contacting alumni to create a pastoral care team' to the list.

**Comment by rebeccaradding** [comment]
> Send acceptance email to successful candidates, including a link to the precourse material

Should be done by programme director, _unless_ a campus does not have one, in which case FCI will support.

I would suggest reorganising to group together everything that could go into a MailChimp email (contact alumni about speakers, invite alumni to first day, invite alumni to a welcome party) so that we can create a template that makes it really easy for the CF to plug in.

**Comment by shiryz** [comment]
CF should also add everyone to the general fac chatrooms:
- `foundersandcoders`
- `city` chatroom (london/nazareth/gaza)

**Comment by shiryz** [comment]
> Add new cohort to Founders & Coders organisation.

this implies every new facilitator should automatically become an owner of the fac organization, is this something we want or should the cf ask one of the owners to do it?
