### ISSUE TITLE
New curriculum planning process

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#558]
related: #501 #544

# The problem

During the last iteration of the curriculum, the majority of the decisions were made in one day, in London.
 * Given that we have 3 campuses, this is highly problematic, as other campuses had little engagement in the process.
 * This process very much placed the burden of these decisions on the students, in a very condensed period of time, which may not be the most effective way of making decisions, nor utilised the vast experience base we have among alumnus.

# Proposal
 1. We create 8 working groups, one for each week of the curriculum. Each working group would be comprised of
    1. 2 students from each campus
    2. Mentors from the previous cohort. Likely the ones who delivered the content belonging to the working group 
    3. One facilitator, taken from the pool of current / recent / soon to be, course facilitators. 
    4. If possible, more experienced alumni.
 2. The maintainers of the master reference would continue to review all pull requests.
 3. Each week, from week 10 - 16, one afternoon would be set aside for students for engage in discussions on Github, and move forward with the preparation of new materials and updating existing materials. If possible, we should have these time slots happening at the same time across campuses, but this is not strictly necessary .
 4. If students want to suggest large changes to the curriculum, they should create a proposal, however the detail of how this should be done will not be included in here.
 5. Creation of working groups should happen immediately following agreement on this proposal.

#### Edits
14 Aug: Added recent mentors to the list of working group members.

**Comment by jsms90** [comment]
As stated in [this issue in international](https://github.com/foundersandcoders/international/issues/79):
> There is an assumption at the root of how curriculum planning has been done until now that is leading to problems: that students should be responsible for updating the curriculum materials in this time.

One week wasn't enough for FAC10. I really don't think 6 afternoons (probably less) are going to be enough time for these cohorts etiher. We're not addressing #501. **The priority of soon-to-be mentors should be learning and understanding the material, not updating it.** It's also becoming more and more evident that students need to spend time learning how to become good mentors. This is a skill and doesn't just come naturally to everyone.

How about making a working group from alumni instead? The most recent mentors (from all 3 locations) have the freshest experience of delivering a curriculum and are more likely to understand what works than those who have only been "users" of the material so far. We could also be engaging our most experienced members, who have seen multiple iterations, and have been pouring their time into the running of the organisation for a long time.
+ 1st meeting (reading week / week 10) - discuss curriculum as a whole & any overall changes that might affect multiple weeks
+ 2nd meeting - break into smaller groups for "sprint planning" & dividing tasks (The number of groups will depend on how many alumni there are. Maybe 2 or 3 groups with a few weeks each, maybe 8 groups with 1 week each)
+ Weekly stand ups on how progress is going

One hour slots during curriculum:
+ Week 12 (after SGC at the end of the 3 week project) - expectations for mentorship are set #365 & students discuss as a cohort & assign themselves to a week each
+ Week 14 & 15 - sessions on how to mentor #365 
+ Week 16 - alumni provide a brief overview on what has changed since the last version of the curriculum & students look over the material from their week

**Comment by rebeccaradding** [comment]
@jsms90 this sounds sensible, but I would suggest opening the working groups to students, so that if any particularly ambitious student wanted to join, they could.

Would you suggest setting aside time for current students to raise issues on the curriculum, to ensure the working groups hear user concerns?

**Comment by des-des** [comment]
@jsms90 I have previous mentors to the working groups explicitly.

> How about making a working group from alumni instead

I am not convinced that removing recent students from the working groups is necessary, or useful.
  * They have the freshest experience as both being a student, and consumers of the master reference
  * This proposal will leave decisions in the hands of a collection of mentors, alumni and students, this is shifting a lot of responsibility away from students.
  * We should involve as many alumni as possible, however, I do not think we have a good track record in engaging alumni. To change this proposal so that students, who have driven the curriculum for the past 10 iterations, are removed from this process seems both drastic and could result in a lack of human resources in building the curriculum.

To address you comments point by point

> One week wasn't enough for FAC10. I really don't think 6 afternoons (probably less) are going to be enough time for these cohorts either.

I am suggesting that we give the students far more support, they will not longer to solely responsible for upgrading the curriculum. I think, under this proposal the working groups are more likely to be able to create resources in time. **q** Do you think removing students from the working groups will help the working groups create resources?

> We're not addressing #501

I have not addressed the question of mentor preparation. I think discussing it here would make this proposal too broad. I think it would be best to keep this discussion focused on the idea of working groups.

> It's also becoming more and more evident that students need to spend time learning how to become good mentors.

I do not think removing students from the working groups furthers this.

 > The most recent mentors (from all 3 locations) have the freshest experience of delivering a curriculum and are more likely to understand what works than those who have only been "users" of the material so far.

I agree, recent mentors should be in the working group, that is already in the proposal.

> We could also be engaging our most experienced members, who have seen multiple iterations, and have been pouring their time into the running of the organisation for a long time.

Same as above

---

I do not understand your second point.

**Comment by m4v15** [comment]
I really like the original proposal, however  I think we need to address they types of changes that might be made to the curriculum:

 - Philosophical changes - Big changes that have a large impact eg: Hapi/Express change, Dumping research afternoons, losing oauth week
  - Delivery/Incremental changes - smaller changes that only effect specific days/workshops. eg: rewriting a workshop, changing the order of a day, maybe changing a project

I think this proposal address the second set of changes really well, but I still can't see a way where bigger changes (such as dropping research afternoons which seems inevitable) are appropriately dealt with - in this set up would each working group have to individually decide to loose it?

Also, who is across the whole curriculum, just maintainers of the MR. I feel like there could be benefit from everyone being at least somewhat aware of what other working groups are doing.

I feel like there needs to be an initial, 'global' meeting where we talk about the larger, philisophical changes. The agenda could be something like:

- Are the broad topics for each week (1-8) satisfactory/good to learn?
- For each week, what should the learning outcomes be/are they feasible?
- Are there any changes we could make to the generic week structure?

However, this feels like it will end up being a similar situation to the FAC10/N1 big curriculum planning meeting and I'm not sure how to avoid it.

**Comment by jsms90** [comment]
@des-des  I hear 2 worries here:
1. The curriculum will belong to a smaller group of people
1. We might not have enough resources i.e. interested / available alumni

To my knowledge, we have never tried to engage alumni in this way. I might be wrong, but I reckon we have quite a number of alumni who would happily spend an evening a week on this for a few weeks. Can we at least ask?

> I am not convinced that removing recent students from the working groups is necessary, or useful.

So do you disagree with "separation of curriculum planning and mentorship" #501 in general?

I am not suggesting that we remove students' _option_ to contribute. (I completely agree with @rebeccaradding's suggestions above.) But I definitely disagree with _expecting_ this from them.

IMO these should be the responsibilities:
+ students - learning the material & preparing to be mentors
+ mentors - delivering the material & contributing to curriculum planning/updates
+ alumni - contributing to curriculum planning/updates

In the second half of the course, students are still learning new information & consolidating their knowledge from the first 8 weeks. Moving curriculum updates into weeks 10-16 instead of week 16 and beyond doesn't really solve the fact that we're asking an unreasonable amount from them.

As the only group who has been expected to plan, update and deliver the curriculum (after `master-reference` was already written), how about doing a survey of FAC10's opinions on this?

**Comment by ZooeyMiller** [comment]
so my brief thoughts are:
> One week wasn't enough for FAC10. I really don't think 6 afternoons (probably less) are going to be enough time for these cohorts etiher. 

I feel that the 40 hours in that week would have been plenty, the problem was people _acutally_ doing the work. I think if we spread it over 6 afternoons there will actually more be done in that time than in the week given originally.

I generally agree that more focus needs to be put on people learning how to be good mentors, but I do not think this is deivorced from them working on the materials. I agree with the basic premise of #501 but do not think that getting different people to plan the content actually makes it easier for the students to deliver it, in fact it could make it harder, due to even less familiarity with the new material.

**Comment by jsms90** [comment]
:thinking: Everything you guys are saying makes perfect sense. Perhaps were not really suggesting mutually exclusive things here. I reckon it comes down to a separation between planning changes and making changes?

@des-des, it's not that I want to completely remove students from the process. I guess, like @m4v15's point above, I couldn't see an easy way of involving everyone (all 3 campus' students, mentors & alumni) in planning anything but the really small-scale stuff.

But you're right, we need to ensure that the curriculum reflects the input of the students. I'm all for them being involved in planning. @ZooeyMiller you're totally right that it's harder to deliver when you haven't been part of that!

I'm really not a fan of students then being responsible for also making all the updates. You have to be _really_ familiar with the content of the week before you can figure out how to get the concepts across to someone else.

They would need to:
1. Go through all the workshops from that week & read around the topic, to get to that level of familiarity
1. Suggest changes via issues & collaborate
1. Attend a sprint planning phase with the working group to prioritise issues & assign tasks
1. Work on their portion of the week
1. Submit changes for review via PRs
1. Review each other's PRs
1. Make alterations based on review comments
1. Send out the updated workshops for user testing (flagged as a problem every time this step isn't done)
1. Respond to new issues, work on updates & submit PRs for review
1. Deliver

Step 1 alone takes quite a lot of time. You have to know all of the week's content, not just one of the workshops. Realistically, if you've only just finished the 8 weeks, this takes more time than one or two afternoons. Whereas mentors and alumni already know the material.

I'm suggesting:
+ Steps 2-3 = everyone (no tasks assigned to students)
+ Steps 4-8 = mentors & alumni
+ Workshops are user tested & issues raised = students
+ Step 9 = mentors & alumni
+ Step 10 = students

**Comment by rebeccaradding** [comment]
It seems the biggest open questions relate to @m4v15's comment regarding what constitutes a "larger" change and who needs to approve such a change. @des-des thoughts on how to incorporate a process into the proposal?

**Comment by des-des** [comment]
@rebeccaradding  

> @des-des thoughts on how to incorporate a process into the proposal?

Sorry could you expand

**Comment by astroash** [comment]
Feels too broad, maybe narrow this down.

**Comment by sofer** [comment]
Let me apologise for attempting to facilitate a meeting I was so ill-prepared for on Wednesday, but let me summarise the outcomes (I am looking at the extensive minutes now):
- There was broad agreement that this proposal is a good one and we should go ahead with it (although there was no formal vote);
- Start by getting course facilitators collaborating to get alumni involved in the 8 working groups for each of the first 8 weeks of the course;
- Set aside the afternoon of Day 2 each week for planning;
- Kick it off in London in week 11;
- Set up a curriculum planning group which needs to agree any significant changes (and are also tasked with defining what's a "significant" change );
- Initial volunteers for this group are @sofer @des-des @mattlub @m4v15 @jsms90 @ZooeyMiller  @mantagen (in absentia), but at this point it is not a closed group.

I think the most important actions now are for the facilitators at all three campuses to work out a good way to coordinate their activities (keeping discussion in well-labelled issues and holding off on any decisions until students at all three campuses have had an opportunity to contribute is probably a good start) and for @jsms90 to gather around her a group of volunteers to kick the process off in London after lunch on Tuesday 5 September.

**Comment by des-des** [comment]
@sofer I think my bad planning did not help...

**Comment by eliascodes** [comment]
Superseded by #735 (I think?)
