### ISSUE TITLE
Curriculum Committee - timeline for weeks 10-16

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#601]
Based on the new curriculum planning proposal #544 and the minutes from [the meeting](https://github.com/foundersandcoders/master-reference/blob/5e41769866e4b76d0a734439dded3fd8f52d55ab/curriculum-planning/minutes/overview/2017-summer-curriculum-process.md), it seems like we are not yet separating "Curriculum planning" from "Mentor preparation" #501.

All of the curriculum updates should be made before FAC12 arrive.

Does anyone have a suggestion for how to:
1. fit the following steps into 5 afternoons (week 11, 12, 14, 15, 16)?
2. a date/time to conduct the sprint planning phase, considering the time difference & the fact that the courses are staggered by a week

The steps involved (originally outlined here: https://github.com/foundersandcoders/master-reference/issues/558#issuecomment-322673532):
+ Divide themselves between weeks 1-8 of the curriculum
+ Go through all the workshops from that week & read around the topic
+ Suggest changes via issues
+ Attend a sprint planning phase with the working group to prioritise issues & assign tasks
+ Update curriculum
    + Work on their portion of the week
    + Submit changes for review via PRs
    + Review each other's PRs
    + Make alterations based on review comments
+ Send out the updated workshops for user testing (flagged as a problem every time this step isn't done)
+ Respond to new issues, work on updates & submit PRs for review

**Comment by sofer** [comment]
I would like to propose the following timeline:

1. **London, Sept 6 (Week 11)** Set aside 3-6pm to:
    - **In advance** open 8 empty issues in master-reference for each of the 8 weeks;
    - **15:00** get FAC11 to assign themselves in pairs to each of 8 weeks;
    - **15:30** get volunteers from the Curriculum working group to be present and to assign themselves to one or more of the pairs, then get each of the 8 groups to review the SGC notes for the week from all three campuses and to comment on the relevant issue, summarising the notes from all three campuses and make a prioritised list of any suggestions for changes to the week;
    - **17:00** get each of the groups to present their reviews of the week with suggested changes.

1. **London, week of Sept 11 (Week 12)** Course facilitator-led review of material for the purposes of preparing for each of the 8 weeks. This one is nothing to do with incorporating changes, just to do with what students need to do to be ready to deliver each of their weeks;

1. **London, week of Sept 18 (Week 13)** Return to each of the 8 issues to review suggested amendments from all three campuses in the classroom, with facilitators present, followed by a meeting of the curriculum working group (students can possibly also attend, and from other campuses, although we probably want to avoid the chaos of the last planning session, so no blocking votes and a strict time-limit to discussions) to identify which of the suggested amendments are actually going to be carried out and by whom.

1. **London, week of Sept 25 (Week 14)** Course facilitator-led mentor preparation.  

1. **London, week of Oct 2 (Week 15)** Course facilitator-led mentor preparation.  

1. **London, week of Oct 9 (Week 16)** Final review of material and mentor preparation.

No further face-to-face meetings need be necessary and all work can take place remotely via GitHub.

All amendments must be merged into master, four weeks in advance of delivery in London, so that changes to Week 1 will need to be merged in by September 25th. If they are not, then changes will not be merged for another 4 months, at the earliest.

**Comment by rebeccaradding** [comment]
These weeks have concluded, so I am closing this issue.
