### ISSUE TITLE
Week 2 - Testing (cohort feedback)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#629]
[Week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-2)

Week facilitator: @ZooeyMiller @oliverjam 
FACG2: @mahmne @kefelhelou 
FACN2: @Wyrd00 
FAC11: @rachaelcodes @AbdullahChaudhry 

#### SGCs
+ [FAC11 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-2.md)
+ [FAC11 mentors](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/testing/summer-2017-handover-london-naz.md)
+ [FACN2 students](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week2.md)
+ [FACG2 students](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/2017-07-20.md)

Historical:
+ [FAC10 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-10/cohort-week-2.md)
+ [FAC10 mentors](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-10/mentor-week-2.md)
+ [FAC9 students](https://foundersandcoders.gitbooks.io/fac9/content/week2/stop_go_continue.html)
+ [FACN1 students](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/fac-n1/week2.md)

#### Open issues that relate to your week
[Week 2 issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-testing)

Note: this week had a big overhaul due to [a proposal to use tape](https://github.com/foundersandcoders/master-reference/issues/253) & [a proposal to change the project](https://github.com/foundersandcoders/master-reference/issues/256)

**Comment by kefelhelou** [comment]
1. The example of coins is hard, it should be replace with an easier one to concentrate about the testing rather than the problem solving { https://github.com/dwyl/learn-tape }

**Comment by kefelhelou** [comment]
2. The Bounce part (code coverage) was not explained nor having time to solve, so it should be more time to make sure to solve the bounce part because we use it in the next weeks { https://github.com/dwyl/learn-tape }

**Comment by kefelhelou** [comment]
There is not enough explanation and examples for Dom manipulation  { https://github.com/mantagen/DOM-manipulation-Challenge }

**Comment by kefelhelou** [comment]
There is not enough explanation and examples for Dom manipulation { https://github.com/foundersandcoders/morning-challenge-traffic-lights/blob/solution/script.js }

**Comment by Wyrd00** [comment]
Week 2 - Difficult week, very messy. Will like to do a massive overhaul.

Tape/TDD:
- It was alright, people are split about it
- Should be replaced with fizzbuzz, which would have been a much better intro

Roman numeral TDD code-along:
- Good.

Traffic light callback challenge:
- Overall, it was pretty good
- Decent introduction to callback, fun as well
- The instruction were relatively clear, hint was useful in getting ourselves unstuck

Pure Function:
- Very hard, poorly structured, sloppily made
- Not a lot of people enjoyed it
- Language of the instructions were confusing and boring, which is especially true when student don’t have a strong technical background yet. And why is the glossary written at the bottom? Fix flow by either defining the more difficult terminology when it comes up or move it to the top
- Consider adding more guidance within the files themselves
- Still no solution branch?

Research:
- Didn’t find certain topics useful
- Too much time allocated for research

DOM manipulation:
- Consider moving it earlier in the week, since it was a big part of the project - had it been taught earlier, the project would have been a lot smoother
- Way too long, and no one finished
- The documentation gave a poor overview

To-Do List Project:
- Difficult, many people didn’t understand DOM well enough
- Parts of the documentation were misleading, led all the teams astray 
- The concept of how everything were tied together were also unclear
- Easy typos not addressed

[FACN2 SGC - Week 2](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/facn2/week2.md)

**Comment by kefelhelou** [comment]
# Gaza 
## Testing week -week 2-


#### Day1 : DWYL Tape (TDD) workshop..

**Thoughts**

+ The example of Change Calculator was hard so we concentrated on solving the problem rather than the testing functions.
+ There should be more examples about testing.
+ The Bonus Level (Code Coverage) hasen't been explained and we didn't have more time to reach it, it should be focused on and being explained.
+ Code Coverage should has a workshop.
https://github.com/dwyl/learn-tape

___

#### Day2 : Traffic light callback challenge..

**Thoughts**

+ The challenge was useful but it needs more explaination about callback functions.
https://github.com/foundersandcoders/morning-challenge-traffic-lights
___

#### Day3 : DOM-manipulation-Challenge..

**Thoughts**

+ The Dom is an essential and important part but there is no good exapmle to follow, the excercise need more explaination and example codes.
+ It needs a code along example.
https://github.com/mantagen/DOM-manipulation-Challenge
___

#### Learning Outcomes:
+ Also the code coverage is not mintioned in the learning outcomes of the week.
https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-2/learning-outcomes.md

**Comment by rachaelcodes** [comment]
Comments from London's [SGC](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-2.md)

## Monday
### TDD Code-Along
* We felt this could include more examples, e.g. mocking data in tests
## Tuesday
### Callbacks morning challenge
* A lot of the group found this difficult, especially if they hadn't looked at the 'hint'. (It got brought up a lot as an example in SGCs later in the term).
## Wednesday
### DOM morning challenge
* We felt this was much longer than could be achieved in the time. There was some disagreement about whether this was a good thing. Some people liked having something else to work on, but it caused stress for others.  
* Apparently, we ended up with an old, longer version - make sure the coursebook is up to date!
## Project
* The week mentors said they could have done more to explain what each function and file should do, though we said it was good practice to read others' code.

**Comment by ZooeyMiller** [comment]
# WIP 
I'm posting this in this state as I have to get back to work, but will format properly later. 
 
Tape/tdd code along: main feeling is we want to make sure the focus is on testing not solving the problem, and the change calculator is quite location specific to the UK, the ideas were either to add in a brief intro to TDD in tape using fizzbuzz for 30 mins, shortening time for tape workshop to 1.5hrs. OR to make a new workshop altogether, which gives something easier/more location friendly than change calculator, but harder than fizzbuzz. 

keep roman numerals

Pure functions - swap it to tape, give clearer instructions and change the wording. 

traffic lights - keep, add more of an explanation of first class functions, and the difference between calling functions and passing them around as data. Add a repl to explain the code.

replace software development methodologies with something more relevant, DOM?

dom manipulation - move forked, better version in MR, swap them around.

project - add helper function for cloning arrays of objects, add info to readme about it. Make sure mentors explain what each file and function should do to give students a big intro.

**Comment by rebeccaradding** [comment]
@ZooeyMiller just a reminder to prepare your list before tonight's meeting, thanks!

**Comment by mantagen** [comment]
@ZooeyMiller, one outcome from Week 3's discussion was the feeling that Code Coverage should be a learning outcome for Testing week, as opposed to its first appearance coming as a stretchgoal/afterthought in an APIs workshop.
There was a sentiment that it simply wasn't prominent enough so many people haven't been doing it.
Could you bring this to the group at and see if you feel it's appropriate/viable?

**Comment by oliverjam** [comment]
I think you're right. It's not too much more effort to integrate Istanbul.

To be fair coverage was introduced before the API workshop—it was a [stretch goal](https://github.com/dwyl/learn-tape#bonus-level) (that everyone in London hit) in the first workshop of the week, and it was an entire research topic too.

I'm not sure the curriculum would have to change, but having it as an explicit learning outcome makes it clear that this is something they should be doing, rather than a nice-to-have that they can ignore.

**Comment by mantagen** [comment]
@oliverjam sorry my bad, it is a research topic ...

So the representatives from all campuses expressed that the code coverage as a stretch goal in the API week was not enough.
| London: our cohort didnt finish this workshop ... and [the coverage/testing section] would surely also require a bit more explanation

Anyway, yeah the feeling was that it's fine to have it as a goal in API workshop, so long as it's had sufficient intro before hand.

**Comment by kefelhelou** [comment]
Update week2 'Introduction to testing and TDD' #666

**Comment by rachaelcodes** [comment]
Has anyone got time to write the helper function for the project before the weekend? I’ve got this for introducing the files: http://slides.com/rachaelcodes/todoproject/fullscreen (mentors to talk it through as the cohort look at the codebase?)

**Comment by ZooeyMiller** [comment]
Closing this issue as the week has finished in all campuses.
