### ISSUE TITLE
Week 4 - Node.js 1/2 (cohort feedback)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#631]
[Week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-4)

Week facilitator: @yvonne-liu
FACG2: @EngAyoosh @moath14 
FACN2: @sajedazoabi
FAC11: @AseelM @dangerdak 

#### SGCs
+ [FAC11 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-4.md)
+ [FAC11 mentors](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/node-1/summer-2017-mentor-retrospective.md)
+ [FACN2 students](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week4.md)
+ [FACG2 students](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/)

#### Open issues that relate to your week
[Week 4 issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-node-1)

**Comment by moath14** [comment]
### Stop wasting course time and be responsible person

**Comment by EngAyoosh** [comment]
**In "ES6 morning challenge"** 
there should be illustration about ES6 and ES5 before this challenge.

**Comment by moath14** [comment]
## Stop put a lot of things in the research topics especially things which want a lot illustrations from the mentors not from the student

**Comment by moath14** [comment]
## workshop on heroku and how to host your site

**Comment by moath14** [comment]
## Show the student how to make code review from the first week

**Comment by EngAyoosh** [comment]
**In "Node.js & Node Intro Workshop"**
list the most usable functions in node.js and a brief illustration for everyone under the workshop.
list useful resources for more understanding.

**Comment by EngAyoosh** [comment]
Add more hints to the students how to make things in **" Node Girls workshop "**

**Comment by EngAyoosh** [comment]
## Continue
Write the code step by step when writing the server for the first time.
## Go
We need more illustration about how we moves from the front-end to the back-end and vise-versa, and how to connect them correctly.

**Comment by moath14** [comment]
### Continue 
## Understand the server and how to work it

### Go
## Explain how to work website and what is the relation between server and website
##Before begin in project we need clarification for files of structure specifically front-end folder and back-end folder

**Comment by paulhanna1933** [comment]
I think it's hard to gauge how long a code along workshop is going to take as it seems that the biggest hold up is when students get typos. Also, typos seem to be common with code alongs and it requires a stop and go process where one mentor is leading the code along while another mentor is walking around helping fix errors. The issue is that sometimes the entire code along needs to come to a halt depending on the number of typos and time that it will take to debug.

I think a good idea to solve this issue is that whenever we have code along workshops we could have a number of completion points in the workshop. Each completion point has a branch which can be checked out in order to start a clean slate for the point of the workshop that the class is currently in. Example if at mid point I run into some issues that I just can't figure out for the life of me, I can wait until the class get's to the next completion point to check out that branch and start fresh again.

Regards,
@paulhanna1933 Paul @sajedazoabi

**Comment by sajedazoabi** [comment]
@EngAyoosh  I agree, the Node Girls workshop was fun but needs more hints

**Comment by msmichellegar** [comment]
@sajedazoabi @EngAyoosh Hey! Node Girls organiser here! We'd be super, SUPER happy for any of you to make PRs to our workshop to make it better and more useful :) 

Also in reference to the comment above from @paulhanna1933, we've previously used branches in our Node Girls workshops, and found they cause extra Git problems for the class. You could give it a try, but be aware that with 16 people in a room you will probably run into lots of weird Git stuff. See the issue on it [here](https://github.com/node-girls/workshop-cms/issues/37) and [here](https://github.com/node-girls/workshop-cms/issues/36).

**Comment by moath14** [comment]
## GAZA

### [ES6 morning challenge](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-4/morning-challenge-day-2.md)

**Thoughts** 
 + there should be illustration about ES6 and ES5 before this challenge. 


---

###  Research topics

From SGC notes :
> + Stop put a lot of things in the research topics especially things which want a lot illustrations from the mentors not from the student and finally we use it in the project.


---

### Learning outcomes 

**Thoughts**

 + we do not learn how to use  heroku but i think we should .
 + Understand the server and how to work it. it needed more introduction explanation.


---

### Code review
 + Show the student how to make code review from the first week

---

### Most usable functions about Node.js
**In ["Node.js & Node Intro Workshop"](https://github.com/foundersandcoders/Node-Intro-Workshop)**
+ list the most usable functions in node.js and a brief illustration for everyone under the workshop.
+ list useful resources for more understanding.

---
### [" Node Girls workshop "](https://github.com/node-girls/workshop-cms)

**Thoughts**

+ Add more hints to the students how to make things in this workshop  because the students have no idea about it before.

---
## Writing the code 

+ Write the code step by step when writing the server for the first time.


**Thoughts**

+ We need more illustration about how we moves from the front-end to the back-end and vise-versa, and how to connect them correctly.

---


## When begin node.js

* Explain how to work website and what is the relation between server and website
* Before begin in project we need clarification for files of structure specifically front-end folder and back-end folder

**Comment by AseelM** [comment]
# London @aseelm @dangerdak 

## Node intro talk
* Popular :)

## Code along

* Coding then explaining -but explicitly telling students that the explaining time isn't for typing catchup.
* Code along ran over time - could create multiple check points during the workshop to minimise time wasted and provide people with working version if they get stuck/lost/behind (https://github.com/foundersandcoders/master-reference/issues/520)

## Node girls workshop

* It was really good for using node and learning to build gradually step by step.
* The workshop had multiple typos.
* Instructions were very vage at times.


## ES6 morning challenge

* A small intro to different versions on ECMAscripts and refraining from stating opinions as facts rather communicating why it might be prefered to use ES5 in the front end especially that there are tools such as babel that allow us to do that

## Research afternoon

* Topics in Node week were all very relevant.

## General Suggestions

* Learn about debugging:
>  The possibility of adding a small talk about debugging plus recommending some tools and techniques.

* Analogies for explanations:
> As a way of explaining tricky concepts such as by reference vs by value: how JS passes usually by value but in case of objects passing is done by reference. because I think that was confusing for people!

* [Glitch for node week?](https://github.com/foundersandcoders/master-reference/issues/242)

**_Be excited about node! :)_**

**Comment by sajedazoabi** [comment]
# Nazareth
##### @sajedazoabi @paulhanna1933
---------------------
###  Intro to servers and Node.js & Node Intro Workshop

The explanation is really a great help for the Node.js beginners.
Zooey did a great simple lecture on that. 

-----------
### code along

We prefer to finish coding and then explaining, zooey was writing the code and explaining and we followed him, but it was really hard to concentrate, especially when someone of us had an error, but Finn was really good helping us to fix the errors and go back to join the group code along.
Code along and explaining  ran over time - and it should be doing something to minimise time wasted and provide student with the original version if they get any error or you should set a time limit for every error, if the student and the mentor didn't success fixing it, then provide them with original version and complete the code along.

We have another good idea to solve this issue is that whenever we have code along workshops we could have a number of completion points in the workshop. Each completion point has a branch which can be checked out in order to start a clean slate for the point of the workshop that the class is currently in. Example if at midpoint I run into some issues that I just can't figure out for the life of me, I can wait until the class get's to the next completion point to check out that branch and start fresh again.


--------------------
### Node girls workshop

It was really great to do that workshop, but as we dig deeper, the instructions are being not that good.
it should contain more instructions and information.

------------
### Research afternoon

The topics were really fine, but we think that deploying research should be on another Week.
we do not learn how to use Heroku but we think we should 
Understand the server and how to work it. it needed more introduction explanation.

-----------
### ES6 morning challenge

We really had a hard time to understand ES6, you should provide more simple information and better workshops, A small intro to different versions on ECMAScript.
why might it be prepared to use ES5 in the front end?

----------
###  SGC notes 


*  5 minutes explanation before every workshop

*  All students shut laptops during presentations / Mentors move to the back if they’re going to be on their devices
*  Continue practising 20/20/20


 --------
### Projects
We need more hints about how we move from the front-end to the back-end and how to connect them correctly.
When beginning node.js

Explain how to work website and what is the relation between server and website
Before beginning a project we need clarification for files of structure specifically front-end folder and back-end folder.

**Comment by mattlub** [comment]
Hi @yvonne-liu @AseelM @sajedazoabi @EngAyoosh @moath14, sorry for the delay in getting the notes up. Please leave a comment if either:
- you have more ideas about something
- you feel like there is a particular proposed change you would like to work on

### Proposed changes:

**CODE ALONG:**
- **add checkpoints/stages to the codealong (in separate branches?)**
- learning and typing is not really possible for most people, prefer typing then explaining
- potentially **add a debugging part**

**NODE GIRLS:**
- some typos to fix
- worth **making the first steps easier/more explicit**, so people can get to step 8 (more important steps)
- or extend the time for this

**ES6 morning challenge:**
- lots of people confused about ES6/ES5 etc.
- **add an intro (in the form of text/video/presentation?) to ES6/versions of javascript before the challenge**

**HEROKU:**
- **create a short technical workshop/guide**
- important but can we fit it in? Deploying on heroku itself does not take long, but maybe a 30 minute thing (walkthrough md file?)
- maybe teach heroku instead of introducing project

**RESEARCH:**
- (topics are architecting, engineering, packaging, deploying)
- keep research, maybe change topics slightly
- **try to make the topics more like mini-projects**

**OTHER THINGS TO POTENTIALLY FIT IN:**
- **example/guide for good file structure:** covered in architecture research in London, not so well in other campuses
- explaining certain concepts e.g. **object/array assigning by reference** should be in the Master Reference in this week, as a resource or a brief workshop?
- resource/walkthrough/example on **how to code review**
- Node Intro to include the SSSK from Sofer?
- Add a **glossary/resource/workshop for most common node functions and core modules**
- more analogies for explanation of concepts

**Comment by AseelM** [comment]
thanks @mattlub I believe this covers all things discussed in curriculum meeting.

**Comment by yvonne-liu** [comment]
Thank you so much for this @mattlub, really appreciate it.

**Comment by sajedazoabi** [comment]
great thanks @mattlub

**Comment by yvonne-liu** [comment]
Hi @dangerdak, confirming that we're not condensing #1-5 in the Node Girls Workshop, but instead adding additional time for students to finish the workshop, correct?

**Comment by dangerdak** [comment]
@yvonne-liu I think so yeah as it doesn't seem very condensable - not sure where to get the extra time from though!
