### ISSUE TITLE
Week 6 - PostgreSQL (cohort planning)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#633]
[Week schedule](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-6)

Week facilitator: @sohilpandya  
FACG2: @Ghadeer93 @Sohadwd 
FACN2: No one able to attend hangouts
FAC11: @azayneeva @RogeredBacon 

#### SGCs
+ [FAC11 students](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-6.md)
+ [FAC11 mentors](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/postgres/summer-2017-mentor-retrospective.md)
+ [FACN2 students](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week6.md)
+ [FACG2 students](https://github.com/foundersandcoders/gaza-programme/blob/master/stop-go-continue/FACG2/)

#### Open issues that relate to your week
[Week 6 issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-postgres)

**Comment by Sohadwd** [comment]
My added about Introduction to the topic of relational and SQL, I suggest to add this:
1. Learn how we can draw the scheme.
2. How we can transform the schema to ER diagram.
3. How can define the attribute and the relationship between it?
4. What the relationship & the type of relationship.
5. How we can think about the database and divided it to the attributes and tables.

Another suggestion about defining the type of database and the advantages and disadvantages of each one, and why we use the PostgreSQL.

And the last suggestion about this [morning challenge](https://github.com/foundersandcoders/db-morning-challeng ) I think that we should introduce the 

> Create a new database on Heroku

before this morning challenge.

**Comment by Ghadeer93** [comment]
I think before start workshop , I suggest monitors start talking about database in general and when we use it . then talking about dealing with database concepts
such as tables , attributes , Fk , PK , schema , relationship  and so on .
In addition, choose a particular project idea and work collectively to create their own tables as well as appropriate attributes . In order to explain the idea that a single database can have more than tables . 
Now , about database commands i thinks monitors start talking about it , what is select , where, join and so on . all note must  have material .

**Comment by Sohadwd** [comment]
**Problem**

Didn't learn How we can transform the schema to ER diagram.

**Comment by Sohadwd** [comment]
**Problem**

Didn't learn how can define the attribute and the relationship between it?

**Comment by Sohadwd** [comment]
**Problem**

What the relationship & the type of relationship.

**Comment by Sohadwd** [comment]
**Problem**


Didn't learn how we can think about the database system and divided it to the attributes and tables.

**Comment by Sohadwd** [comment]
**Problem**


Didn't define the type of database and the advantages and disadvantages of each one, and why we use the PostgreSQL.

**Comment by Sohadwd** [comment]
**Problem**

About this [morning challenge](https://github.com/foundersandcoders/db-morning-challeng ) we didn't introduce the 

> Create a new database on Heroku

in the workshop before this morning challenge.

**Comment by Sohadwd** [comment]
**Problem from FACG2 members**

We didn't understand how we can link the database with backend functions before we start the project.

**Comment by Ghadeer93** [comment]
In workshop [ installation instructions](https://github.com/macintoshhelper/learn-sql/blob/master/postgresql/setup.md)
@mrm7moud  has  Linux as operating System , when he run these commands to install Postgres on  his laptop not work done or may be commands contains errors .
So he think uses mongodb .

**Comment by sohilpandya** [comment]
@Sohadwd @Ghadeer93, Great work on noting down all the troubles we've encountered, It will be great to think about potential solutions to the issues and how we can implement them in the given week. 

@Ghadeer93, totally understand that noSQL db's are also worth learning about, but due to the time constraints we have of only having one week to do databases, we should put our focus on SQL for now. Maybe this is something that can be bought in later on in the course, But I don't want us to focus on it for now. :)

FAC London will also be using this so I suggest that we all review those comments as and when they come in and we can all have one big hangout together once we have proposals from each campus. How does that sound?

**Comment by Wyrd00** [comment]
Week 6 - Overall, good week. But it could be because it was slightly repetitive and could have addressed more challenging aspects of database

Whiteboard intro:
- Excellent overview
- Really helpful in defining different relationships

SQL commands:
- Decent introduction, smart to allocate time to make necessary installations

PG module code-along:
- Good, some people felt that it was too slow though

PG workshop:
- Really good, right amount of challenging
- Length was on fleek

Research:
- Mixed feelings - some research topics felt unnecessary, while others felt more important

DB morning challenge:
- Overall, it was good. However, at this point, more challenging topics could have been introduced

Project: 
- Overall, it was good. 
- Some students preferred more clarity over how many databases are expected

### [FACN2 SGC - Week 6](https://github.com/foundersandcoders/nazareth-curriculum/blob/master/stop-go-continue/facn2/week6.md)

**Comment by Sohadwd** [comment]
Thanks, @sohilpandya for your comment!

Yes, I think about a suggested solution for each problem I will share it now in this comment, and we can discuss it in the hangout, and hear your suggestion.

In my opinion that week 6 is very important and bases to all project. 

My suggestion, about 'Introduction to the topic of relational and SQL', add this:
1. Introduce to what we mean about Schema and ER diagram.
2. Learn how we can draw the scheme.
3. How we can transform the schema to ER diagram.
4. How we can define the attribute and the relationship between it.
5. What the relationship and the type of it.
6. How we can think about the database and divided it to attributes and tables.

> All the above point related to problems 1 - 5


_And about problem 6:_ 
Make a workshop that define the database and database types and what the advantage and disadvantage to each one, and why we use PostgreSQL.

To the seventh problem, we can introduce workshop about

> Create a new database on Heroku

before the morning challenge.

And to the last problem, we can write work shop about how we can build functions that connect between the database and the backend.

Really Thanks @Wyrd00 for your comment, it makes a really benefits feedback.

**Comment by Sohadwd** [comment]
## Gaza, Week 6

### whiteboard walkthrough
- Excellent overview
- Suggest to expand it and add this point.
> 1. Introduce to what we mean about Schema and ER diagram.
> 2. Learn how we can draw the scheme.
> 3. How we can transform the schema to ER diagram.
> 4. How we can define the attribute and the relationship between it.
> 5. What the relationship and the type of it.
> 6. How we can think about the database and divided it to attributes and tables.

### [Installation instructions](https://github.com/macintoshhelper/learn-sql/blob/master/postgresql/setup.md) and [sql-commands-intro workshop](https://github.com/foundersandcoders/sql-commands-intro/)

- Very useful good


---

### workshop on SQL commands and psql

- good but very long


### pg module code along

- Good
---

###  workshop on making small node app with a database connection

- Very useful and prepare to project
- Make practice to database

---

### morning challenge

> + too long
> + Feeling harder becuase first time to know about ` database on Heroku`


**Thoughts**
+ Add short introduce workshop that explains ` database on Heroku`


---
### Research Topics
+ Schemas and relationships are good and very important, but I think it must be first in week-6
+ Database setup and maintenance, Testing and Script injections/safety issues
are very good 
+ Now, I think to add new topic such as learn NoSQL databases like MongoDB.

---
### project 
- Good
- Some students preferred more clarity over how many tables are expected from the projects because it makes a long time and didn't finish the project.

**Comment by des-des** [comment]
@mantagen I think I am facilitator on week 8 only??

**Comment by azayneeva** [comment]
@sohilpandya , @Ghadeer93 , @Sohadwd , guys, do we have a hangouts call today? If yes, could you please send me a link? If not, when are we going to have one?

**Comment by Sohadwd** [comment]
@azayneeva  yea https://hangouts.google.com/call/VWD2dsACpv1RoaBLzSubAAkI

**Comment by rebeccaradding** [comment]
@sohilpandya do you have a list of suggested changes ready for tonight's meeting?

**Comment by sohilpandya** [comment]
No new changes from london. Waiting to hear back from Gaza. But likely to keep the same schedule. 

I wont be attending the meeting tonight.

**Comment by rebeccaradding** [comment]
@sohilpandya thanks for the heads up. Sorry if I misread the Doodle, I meant to ensure all week facilitators could attend! Sounds like week 6 won't require any significant review, and you can update the working group at its next meeting.

**Comment by mantagen** [comment]
@sohilpandya there's been a bit of a problem with pgcli here sometimes when
running the commands to run sql script from file. Haven't figured the cause
and generally when it's occurred have got them to use psql. @eliascodes do
you remember any such problems during the actual week?

**Comment by eliascodes** [comment]
@mantagen not specifically, but @ZooeyMiller spent more time in class than me that week, so maybe he noticed something?

**Comment by sohilpandya** [comment]
Here is what the team in London and Gaza have come up with. 

**Day 1:**

10am - 11am: whiteboard walkthrough with introduction to the topic of relational databases and SQL, overview of other databases and explanation why we focus on PostgreSQL

11am - 1pm: installation instructions , those who finish installing can help others with installation problems. Then go to sql-commands-intro workshop and work through in pairs if time remaining (help each other first)!

1pm - 2pm: lunchtime 😋

2pm - 4.00pm: workshop on SQL commands and 

4.00pm - 6pm: biz dev and community outreach

**Day 2:**
10am - 11am: pg module code along

11am - 1pm: workshop on making small node app with a database connection

1pm - 2pm: lunchtime 😋

2pm - 4.30pm: research

4.30pm - 5:30pm: Review and present research topics

5.30pm - 6pm: introduce projects

**Day 3**
10am - 11am: morning challenge
**@Gaza want a morning workshop related to analysis of databases and tables. @Sohadwd could you please provide a little more information on this and if you’d be happy to take that on?**

11am onwards: projects

17pm - 18 pm: normally we had an external speaker here, so maybe change this to MongoDB?
> I don’t think that 1 hour is enough to do an intro to mongo. We should keep to a speaker here 

**Day 4**

Continue work on projects

**Day 5**
10am - 11am: code reviews

11am - 12pm: responding to issues

12:40 - 1pm: preparing presentations

1pm - 2pm: lunchtime 😋

14:00-15:00 -Cohort Stop Go Continue (retrospective)

15:00-15:40 - Team retrospectives

15:40-17:00 - Presentations (20 mins per group)

17:00-18:00 - External Speaker or Alumni Project Presentation - maybe MondoDB workshop instead?

**Comment by azayneeva** [comment]
By Friday 27th October

Updates:
- [ ] Update week's schedule readme to reflect the week's proposed structure
- [ ] Detail the learning outcomes for the week
- [ ] Update whiteboard walkthrough #531
- [ ] Update installation instructions #288
- [ ] Update workshop on SQL commands #291 
- [ ] Update pg module code along #290 
- [ ] Update workshop on making small node app with a database connection #296 
- [ ] Update morning challenge #294 

Possible changes:
- [ ] Agree about research topics #308 
- [ ] Agree about project requirements #308 
- [ ] Agree if we need workshop on Mongo DB #308
