### ISSUE TITLE
Week 7 - Authentication (cohort planning)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#634]
[Week Timetable](https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-7)

- [London Mentor Retro](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/authentication/summer-2017-mentor-retrospective.md)
- [London SGC](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-11/cohort-week-7.md)
- [Nazareth SGC](https://github.com/foundersandcoders/nazareth-programme/blob/master/stop-go-continue/facn2/week7.md)

[Open issues](https://github.com/foundersandcoders/master-reference/issues?q=is%3Aopen+is%3Aissue+label%3Aweek-authentication)

Note: this week was created & delivered for the first time based on [this propsoal](https://github.com/foundersandcoders/master-reference/issues/263)

Week facilitator: @ronanyeah 
FACG2: @SamerElaila @SalwaAlnazly 
FACN2: @matthewdking
FAC11: @morkeltry @astroash @maxgerber

**Comment by SamerElaila** [comment]
Morning challenges in This week are not relevant to week's topic

https://github.com/foundersandcoders/mc-client-side-validation
I think it is better to move it to week 1 or week 2

In callbacks morning challenge , we saw the challenge after we get comfortable with callbacks, I think it is better to move it to week 4 or weeks 5 , it was too easy so we didn't learned anything new in that week about callbacks
https://github.com/foundersandcoders/mc-do-this-then-do-that

**Comment by SamerElaila** [comment]
I think we need a little bit more explanations in this workshop
https://github.com/foundersandcoders/ws-session-management
because we need to understand sessions very well and when to use them in our projects

**Comment by ronanyeah** [comment]
London week 7 retro: https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/authentication/summer-2017-mentor-retrospective.md

**Comment by ronanyeah** [comment]
@SamerElaila Could you be more specific about the 'explanations'? We can open up an issue/issues on the workshop repo eventually but we can discuss it here for now.

**Comment by matthewdking** [comment]
### Password Management
From SGC notes:
> + quite short, didn't fill the time at all
> + had issues with tests

**Thoughts**
+ Spend more time explaining what bcrypt actually is, because the exercise can be done very quickly without really understanding what is happening.

### Cookies

+ Good workshop I think we as a cohort got what we wanted out of it.
+ Timing was good.

### Client Side Validation
From SGC notes:
> + Heather: well-written, instructions clear
> + generally well recieved

**Thoughts**
+ Move it to another week earlier in the course as is fairly basic and concerns the client side.
+ This taken from the workshop is not relevant and should be removed.
> Firstly, style the form using the design as a guide. Making your own stylistic choices is strongly encouraged.

### Session Management
From SGC notes:
> + King, Vered: a tough one (concepts were difficult)
> + Was problematic but don't fully understand why

**Thoughts**
+ How are real life applications dealing with session management - what are the advantages and disadvantages of each approach (tokens vs cookies vs both). Put this in the description for the workshop?
+ Make connection clear between hmac and JWT. JWT can use hmac to hash it and this isn't mentioned in the workshop.

### Callback Morning Challenge
From SGC notes:
> + Vered: wasn't actually that bad same test problem, all the tests were passing
> + King: would it have been useful earlier in the course?
> + Lubes: so was it a good workshop? did you learn a lot?
> + King, Heather did
> + Vered: maybe swap with a different one: parallel or traffic lights
> + Shireen: replace parallel with waterfall?
> + Lubes: we are discussing improving teaching of callbacks

**Thoughts**
+ Move this challenge to earlier in the course - possibly week 3.
+ Slightly unclear exercise 1 was the synchronous version of exercise 2.
+ Is the first task even needed? It's not actually related to callbacks.

### Research Topics
+ Probably some of the better research topics in the course. Lots more demos at this point and more people felt like it was actually useful.

**Comment by ronanyeah** [comment]
Awesome feedback, thanks a lot. Once we get the final input from London and Gaza we can start piecing it together and opening issues to action on, in both `master-reference` week 7 folder and the workshop repos, if applicable.

**Comment by astroash** [comment]
## London

### General Thoughts

+ @eliascodes in Issue #4 of Password-Management went through the readme and line-by-line commented places where he suspected people might have questions or needs for clarification. I think this would be a great way to prepare for our teaching of this week - perhaps by having teachers' notes. This could run through the readmes but if we wanted to be super prepared could be notes/annotations on the actual workshops (Max)
+ We should consider refactoring a workshop into a step-by-step format, but as the feedback for this week was quite good, it's possible that this is unnecessary. (Max)

### Password-Management
From SGC Feedback:

From Issues:
* signed cookies and 'claims'

**Thoughts**
* password management itself seemed less important than the under-the-hood stuff
* great material, well presented (Tom)
* Great balance of explanation and exercises in workshop (Aisha)
* Mention base-64, to be more fully explained when it's used? (Tom)
* Need an accepted clear and uncontentious definition of 'signature' in different contexts, so as to reduce confusion with jwt.sign() (Tom)

---


### Cookies Workshop
From SGC Feedback:
> * last minute workshop merging? (bad)

From Issues:

**Thoughts**
* Great intro to cookies but workshop was a little short, flags were not clear (Aisha)

---


### mc-client-side-validation
From SGC Feedback:

From Issues:
 * explain why:
  > no matter how much front-end validation you have, you should still validate on the server side to ensure that your form is secure
 * point students towards validating on `blur` / `keyup`  type events, rather than `submit`. Cos we're all modern an' ting.
 * 

**Thoughts**
* Loved there being *some* emphasis on 
* Would really like to make the CSS and presentation on this look super profesh (Max)
---

### Session Management Workshop
From SGC Feedback:
> * last minute workshop merging? (bad)

From Issues:
* Rename workshop to JWT
* After using 'validate', using a whole JWT seems like a jump. Explanation of what they do (?explicit link back to presentation?).
* Everyone got why we use base64?
* [nice](https://github.com/foundersandcoders/ws-session-management/issues/5)


**Thoughts**
* Written section on JWTs and section on JWT exercise needs more detail, and more flagging up what is important to unserstand first in order to implement. (Tom)

---

### Callback Morning Challenge
From SGC Feedback:
> + The callback workshop felt shoehorned in because people felt uncomfortable with them. Some of our cohort were still nervous about how they worked. As a result, however, the general consensus was that the workshop was too easy.

**Thoughts**
* Likely not to be the same - maybe swap with wk2? maybe Promises? T
+ I feel that the main issue with callbacks came from being confused about how data flows from one function to another. (Max) 
+ There are basic concepts that went over our heads when we first learnt about callbacks which meant that when (for example) I read that callbacks and asynchronicity were FUNDAMENTAL to Node.js, I panicked.
+ Can this be a **promises** mc?? - pretty please with :cake: on top
---

### Research subjects
From SGC Feedback:

**Thoughts**
* HTTPS important, but not learning outcome (Tom)
* XSS / CSRF / MITM - important but open subjects. Can happily be ignored forever, but shouldn't be! (Tom)

---

### Projects
From Feedback:

> * How to deal with prject was contentious at SGC
> + There was a lot of agreement that the project's scope was unfeasibly massive. We proposed making a mini-project with week 6's Database-based app, allowing us to spend our week 7 projects more focused on the learning outcomes of the week - Authentication. (MAX)
> * Intelligent use of cut & paste; diving into other people's code.


**Thoughts**

* Too much focus on previous weeks' learnings - some CTRL-C,CTRL-V'd previous weeks and did OK. Others tried to redo previous weeks and found project too big. T
* It would be great if projects could be a continuation of the previous week, this way they would be able to focus on practising authentication and writing substantial tests. (Aisha)

**Comment by ronanyeah** [comment]
Based on the Wednesday September 20th meeting, each campus will take ownership of a workshop:
- London: [Cookies](https://github.com/foundersandcoders/ws-cookies)
- Nazareth: [Session Management](https://github.com/foundersandcoders/ws-session-management)
- Gaza: [Password Management](https://github.com/foundersandcoders/ws-password-management)

Next steps are to open issues/suggest changes based on:
1. Feedback from the cohorts in the comments in this issue.
2. Feedback from Stop-Go-Continues + Mentor feedback linked at the top.
3. Existing issues open in the workshop repo.
4. Your own personal opinions!

Let's try and get all the issues open ASAP, ideally by the end of this week.

Notes from meeting:
- Students not aware there was supposed to be a CSS challenge in each week.
- Callback challenge was out of place and would be better served by something relevant (like a hashing workshop).
- The project had a very large scope. It may be better to _add_ auth to the project from Week 6. This is what Nazareth did and it was very well received. (My personal feeling would be :+1: to this.)
- This weeks research topics were important and interesting. If research afternoons are scrapped we will have to ensure the topics are represented elsewhere in the curriculum.
- Alexis' presentation was very useful, so we will have to ensure its content is folded into the workshops.

[Changes to morning challenges, research afternoon and week project will be discussed at a later date.]
