### ISSUE TITLE
Week 11 - day 5

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/master-reference#64]
Although we are having excellent discussions about the overarching structure of the curriculum, and how this should be imparted upon F&C10+, concerns are being raised among F&C9 about tomorrow's schedule.

As this week's schedule has not followed the readme in https://github.com/foundersandcoders/master-reference/pull/63 so far, we would suggest that tomorrow be used as a continuation of what we have been doing today. For example, there are people who are not familiar with React, whereas a few have looked into it in their own time. In the readme, it is suggested that one day is used for the videos tutorials and the next day for building something, (which could then have been user tested on day 5).

It is not that we do not see the validity of real-life user testing. Not at all. But rather, that it belongs within a context e.g. within week 10, or in this week before then _using this research_ to build out the next feature.

Given how this week has evolved, it seems more important to maintain some continuity of learning, especially when that concerns completely new technologies. It is also important to make sure that we progress as a community. We do not want tomorrow to splinter into different people deciding on different courses of action for themselves, in a justifiable effort to make sure that their time is used most effectively.

We also feel that this would be best discussed in person (if possible), rather than through a stream of comments on this issue. But it is important to have a record somewhere. We have one more hour of today, before the talk. It would be great if we could discuss this during this hour, or at 6pm, so that we have a resolution before tomorrow?

**Comment by nelsonic** [comment]
@jsms90 ***thank you*** (_very much!_) for _summarising_ what _judging_ by the number of "thumbs up" reactions, appears to be the "_general sentiment_" among the **F&C 9 Cohort**.

![week-11-day-5-people-dont-want-to-get-out-of-the-building](https://cloud.githubusercontent.com/assets/194400/21899560/9339d2b6-d8e8-11e6-9553-7ea4493ef627.png)

To be ***100% Clear*** this Week 11 Curriculum ***Proposal*** was prepared for **F&C 10** and I was suggesting that we _trial_ _some_ of it for  **F&C 9**. As I _tried_ to explain _this morning_, people can _easily_ learn Redux in **one day** and that you can _easily_ condense day's 3 & 4 of the _Week 11 F&C 10 Proposal_ into one day.
_Given_ that _nobody_ has opened a issue with a Question on https://github.com/dwyl/learn-redux/issues as we discussed, my _only logical conclusion_ is that _everyone_ is making steady progress toward learning it. is that _incorrect_? is anyone "_stuck_"...? 😕 

I've taught people how to use Redux in the past in _less than an hour_ and Dan Abramov's videos teach you _everything_ you need to know and you can learn it at their own pace. That is what _literally hundreds_ of people who _don't_ have access to a "Full Time Free Coding Bootcamp" have done.  What all the kids in around the world who _don't_ have access to _seasoned_ professional app developers _don't_ have is _coaching_ on doing user research... 🤔 

> _Knowledge of Redux or React is **100% Optional** for doing User Research/Interviews, in fact the more you know about **how** to build things the less you will be **focussed** on **empathetically listening** to **Why** the person wants a particular feature..._

The _idea_ 💡  was to get _way_ out of your "***comfort zone***" (_i.e. sitting at a **desk** in Palmer's Road_) and do some _real world_ interviews guided by someone who has done _hundreds_ of them. Interviewing people is a skill that **requires _exactly zero_ React.js experience** or a "_working prototype_" in fact http://www.thesprintbook.com/ suggests you "***fake it***" which means doing a ["_paper prototype_"](https://github.com/dwyl/learn-user-experience-testing/issues/3), but if _everyone_ prefers to sit and learn React instead of getting out into the "_real world_", _who_ am _I_ to "argue" or _suggest_ that they are missing a _golden_ opportunity. 🙊 

> If people are avoiding the challenge to ["_Get out of the building_"](https://youtu.be/a-J_SwmMJyo) because they feel they "_don't know enough_" that is _kinda_ the _point_! You will _never_ know enough to build the "_perfect_" app. Ask *any* of the F&C graduates if they feel the "_know enough_" and haven't learned while _on_ the job ... or wouldn't do things differently with their post-project knowledge... Also, consider how _many_ startup/business/app ideas [***fail***](http://www.forbes.com/sites/neilpatel/2015/01/16/90-of-startups-will-fail-heres-what-you-need-to-know-about-the-10/#495bed6a55e1) because the developers don't _make_ the time to ***ask the people***... it's _way_ more painful to pour hundreds/thousands of hours of your life into building the ultimate app with a blazing fast "Virtual DOM" only for the project to be _cancelled_ because nobody _used_ it! I'm _trying_ to save you guys ***Thousands of Hours of your Life*** and you're "_passing_" on the chance...?! 😧 

I have no _appetite_ to "_force_" anyone to learn how to do primary ethnographic research which will be **_by far_ the _most valuable skill_** you will learn on the F&C Course ... I'm sure everyone can learn it _vicariously_ from a Medium Blog post later on without an experienced person to give priceless insight into the process. 👍 

For the record I cannot even _begin_ to describe how _frustrating_ it is when I _make_ time to do something fun/challenging with people (_when I should be working on interesting/rewarding client projects that solve real human problems_) and people "_pass_" on the opportunity. 

> @iteles we need to _fix_ this breathtaking devaluation of effort/investment ... 😞 
meanwhile I'm going to get back to work. 👍 

What I've _learned_ is that unless the _whole_ week is *one thing* and has "_continuity_" nobody will be "_on board_" with trying something new/challenging/fun. 
When in _reality_ learning how to be (_mentally_) _agile_ and _enthusiastically_ take _opportunities_ when they _arise_ is the _single_ most important "_skill_" people can learn in their "_careers_"... because sometimes those chances don't come around again...

> For anyone who _is_ still _interested_ in doing User Research (_the **single most valuable skill** in web app development for ensuring that we don't build the "**wrong thing**_!) ... I have now re-scheduled my Friday (_based on the **overwhelming consensus** that **F&C 9 don't want to "get out of the building**" tomorrow_) to be at http://www.mindwaveventures.com/ instead where the _team_ will be conducting user research with real people. Those people will be shown ***paper prototypes*** for an app that will be built following the [***Lean Methodology***]() and will be _used_ by *millions* of people. To reiterate **No React/Redux Required**; not had a *single* feature has been built for it yet. 
You are all _welcome_ to join us. Or _not_. Up to you.

## Love You All! ❤️

**Comment by iteles** [comment]
@jsms90 I have not followed the structure of this week, or even the plan for the coming days, but what I *can* say is that knowing how to speak to users and do user research/testing are in my experience ***far more valuable*** than spending that time learning *any* new technology (which you can do in your own time, from any location, alone or accompanied).

I am quite frankly *bored* of trying to get user research and testing into the curriculum over the last 2 years. 

For a decision on whether this should make it into the curriculum for FAC10, I would suggest that we also bring in the voice of experience of some of our alumni who have been there and done that 'in the real world' as clearly @nelsonic and I aren't having much success.  Very very happy to point to a few dwylers and alumni who have done so 👍 ✌️

**Comment by jsms90** [comment]
@iteles I don't think that is necessary:
> It is not that we do not see the validity of real-life user testing. Not at all. But rather, that it belongs within a context e.g. within week 10, or in this week before then using this research to build out the next feature.

In hindsight, this was 100% **not** the right medium for this discussion.

**Comment by nelsonic** [comment]
@jsms90 agreed. but it was _really_ useful/insightful that you "_took one for the team_" to communicate it! thank you sooooooooo much! seriously! thanks! ❤️  ✅  🎉

**Comment by bradreeder** [comment]
My understanding is that an arrangement was made in person for tomorrow and that this issue is resolved. Feel free to continue discussion on weeks 11-12 here #63 . Closed.

**Comment by nelsonic** [comment]
Thank you @bradreeder for _closing_ the issue so we can _all_ focus on what's _important_! ✅ 
Thank you @jsms90 for not being "_afraid_" to share the collective thoughts 💭 
_specifically_ that people _prefer_ to focus on learning moar coding skills 🤓 
_instead_ of following the advice of [Steve Blank](https://youtu.be/1RTcXwJuCaU), [Eric Ries](https://youtu.be/fEvKo90qBns) or [Ben Horowitz](https://twitter.com/nelsonic/status/655824314617450496) ... 😞 

> **Note**: I too have _focussed_ on **technical skills** in the past 
at the _expense_ of "***Get out of the Building***" ... 

[![focus-on-coding-skills](https://cloud.githubusercontent.com/assets/194400/21923696/765028d2-d96d-11e6-8488-56ebcb761a91.png)](https://twitter.com/nelsonic/status/321950687619584001)

> but I've since _realised_ through much _pain_ of wasted effort on go-nowhere apps
 that unless there is a user-testing-early-and-often ***culture*** projects developed by highly competent/experienced "_engineers_" flat out ***fail*** to get _any_ traction thus resulting in _vast_ wasted effort and disappointment!

![image](https://cloud.githubusercontent.com/assets/194400/21923660/43889a60-d96d-11e6-86bc-5a7ceef624c5.png)

While I _acknowledge_ that there are a _few_ people in the **F&C 9** Cohort who have **Social Science Interviewing Experience** and even have "_won awards_" (_which is fantastic/impressive/awesome BTW!! I would **love** to **learn with/from you**!!!_) I think those people should have _altruistically shared_ those skills to help _other_ members of the Cohort (_who do not have the experience_) "_get out of their comfort zone_" and "_learn from real users_" ... because once people are in the "Junior Dev" ("_marketplace_") working in a company that _doesn't_ do user-testing (_which is 90+%!!_) this will all be a _distant memory_ and it will be 2 years, 3 "_jobs_" and 6 projects before _most_ of you reap the benefits of _pre-product UX-research/testing_ ... 😢 

![image](https://cloud.githubusercontent.com/assets/194400/21923373/9abaf50a-d96b-11e6-9a68-b201982501d5.png)

Following our _lengthy_ discussion yesterday about the "_future of F&C_", I'm _resolute_ to ["_double-down_" my efforts to focus on user-testing](https://github.com/dwyl/learn-user-experience-testing/issues/1) and _commit_ to spending 20% of my time with end-users! 
Thank You _everyone_ for _reminding_ me _just_ how _vital_ user-testing is and how under-valued it is as a skill/technique for avoiding wasting time. ⏳ 


> **BTW**: _This_ is who you passed up a chance to meet and learn from today: https://www.linkedin.com/in/underwoodemily & https://www.linkedin.com/in/tendayiviki
By comparison to "Luxy" or Tendayi we (I) know _nothing_ about UX / User Testing 
and I'm _excited_ to "[_be a beginner_](https://en.wikipedia.org/wiki/Shoshin)" and learn _everything_ I can from them! 😍 

_Anyway_ ... Love you! ❤️  
Thanks again! 

[![image](https://cloud.githubusercontent.com/assets/194400/21922928/2c08cd82-d969-11e6-9273-cbd93dc657ab.png)](https://youtu.be/TiDoEFKOGbU)
