### ISSUE TITLE
Precourse Vocabulary (vocab, glossary, terms, keywords)

### ISSUE THREAD

**Issue by mantagen** [foundersandcoders/master-reference#644]
Relates to https://github.com/foundersandcoders/master-reference/issues/194

## Why

During FAC, mentors will use certain tech words and terms.

In London, these terms are sometimes explained on the fly and usually just absorbed in a fairly short period of time by those individuals who didn't know the terms before the course started.

In Nazareth and Gaza, it can be harder to absorb these terms on the fly, and some basic terms can be left unclear until much later in the course, with the effect of not understanding and hindering learning.

## What

Add a vocab list to the pre-course.
My current thinking is that this list could just be something that pre-course mentors are aware of and can use as a bit of a 'gauging' where the person is at.
If they don't know a word, maybe they understand the concept but didn't know if a certain term for it. This is still useful information to learn for the mentor.

**Notes**

I am by no means sold on this idea, and am aware that (at least in Gaza) we are increasing weighting on English language for the selection process, but I wanted to see what people thought about it.

It is also something that would be overcome by increasing learners inclination/confidence to ask when they don't understand.

Thoughts appreciated @RanaAlqrenawi @eliascodes @des-des @m4v15 @mattlub @Karyum 
- Do you feel like this is a problem?
- Do you have ideas around a solution?

**Comment by eliascodes** [comment]
@mantagen Just to be clear, is this about pre-course material or is it about pre-requisites? I think it's fine to expose them to terms that they will have to become familiar with. I'm less sure about making knowledge of those terms any part of the selection process; my feeling is that we should first assess how well a good general level of English correlates to level of learning on the course.

**Comment by mantagen** [comment]
@eliascodes yes good point, I've changed the title.
I think as I wrote it I formed the opinion you express above.
I also almost didn't even submit the issue because I couldn't think of a way of doing this that would be effective / helpful. Or necessary when we have altered selection process

**Comment by mantagen** [comment]
If no more discussion arises within the next few days I'll close to issue.

**Comment by des-des** [comment]
@mantagen yeah I am not convinced learning key terms before the course would be that easy, without the context that comes with the course, this may be a fairly daunting task.

**Comment by mantagen** [comment]
@des-des yeah the things I had mind were like "objects", "keys", "loop",
"iterate", "property", "method", "invoke", "call", "data types", etc etc
I guess what I'm wondering is if there could be a description of the level
we expect people to be at before the course. What understanding we expect
them to have already

**Comment by mantagen** [comment]
Closing due to lack of interest

**Comment by HilbertSpitzer** [comment]
Let me jump right in!
I realize that there's alot I don't know, so if I'm mistaken then please do correct me. It's better to be stupid for 5 minutes than to be stupid forever.
That said...

I think that the language barrier is a problem in FAC that does need attention. Possibly it's a problem that is more relevant to Nazareth and especially Gaza. But even native English Speakers can benefit from this.

Looking at what @des-des  said, I agree that even some of the simple terms can be difficult to properly define for someone who has just started programming, a word like 'object' can mean alot of things after all despite being a basic word. So are we going to oversimplify it or overwhelm the beginner with lots of new unfamiliar info? Because one of the problems with definitions is that they kinda depend on the person to know other definitions as well, which the beginner almost certainly doesn't know.

However. I also do strongly agree with @mantagen's point that at least some terms should be taught beforehand, and i think that it really helps out people to get acquainted with certain terms before they start the course. There are many simple terms that are easy enough to understand and remember quickly. I think that the first 2-3 weeks are stressful precisely because of such reasons. People being introduced to too many things all at once, including words.
Even knowing very basic words can help out with this, like hyphen, RGB, server, browser.
Believe it or not, some people didn't know what those words meant despite being easily capable of picking up what those words mean.

Many people finish this course but still end up not knowing what [stack](https://skillcrush.com/2013/01/10/the-stack/) means, considering we want them to be full stack developers, that's not ideal.
In Job interviews, people are bound to be asked to define things or explain the difference between one thing and another. People need to be better prepared for this.

Some people may feel too ashamed about admitting in class that they don't know some words and yet don't ask the lead mentor what he was talking for the sake of saving face.
We need a way to solve this.

I don't know the situation in Gaza. But it wouldn't surprise me if some don't know the differences between Technical English and everyday English.

Driver, Execution, Resolution, etc all have different meanings in Technical English. Maybe to you it sounds absurd that someone would confuse such simple terms, but it happens.

There already have been some signs that a "Strong English speaking and reading comprehension skills" could be a helpful skill to have
https://github.com/foundersandcoders/nazareth-programme/issues/200

I think that if we better support people who have trouble with english, then we'll definitely be able to get better results and benefit one and all. It doesn't even have to be a pre-course thing.
