### ISSUE TITLE
Should two hours of business development be repurposed as a time-slot for self-organising?

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/master-reference#645]
### Context

- A few London cohorts back, @sofer introduced a time slot for _business development_ into the FAC curriculum in order to engage current students in the running and development of the programme. In the beginning, students in London worked directly with @sofer and other alumni on tasks ranging from setting up schools workshops and inviting alumni in for talks. 
- When preparations began for the Nazareth programme, @sofer became less available in London. He suggested that _business development_ focus on tasks that could be accomplished without his hands-on support. Together we brainstormed what those tasks might be and how to provide students with enough direction to use their time productively.
- After experiencing business development firsthand, @jsms90 suggested that this time could be spent more productively if groups had more clearly defined remits, and someone in the organisation to whom they could turn for guidance. We've experimented with this relatively more structured format for FAC11 and FACN2, with mixed results.
- Given that Gaza Sky Geeks has programme staff capable of running and developing the programme, FAG2 has not allocated time in the schedule for _business development_.
- In both London and Nazareth, the business development time slot currently requires quite a bit of planning (to think through the assignments in advance) and hands-on support during the time block (from the course facilitator and/or mentors and "point people"). It has been suggested that further clarity around assignments and alumni support would improve the time slot, but I'm not sure this solution best meets student needs.
- Some, but not all students can manage the pressure of the course _and_ a commitment to a task that requires weekly work, such as organising an engagement with a school, posting on social media, or coordinating speaker spots.
- At the same time, some students are hungry for and excited about taking on a larger project, such as the FAC Library, and we should find a way to encourage this. 

### Suggestions

Different groups of people have different passions and interest. I suggest that we refocus on making space for people to organise themselves according to these interests and to take the lead on projects that are of value to their cohort's experience, if and when they are motivated to do so.

_I suggest that we:_

Use this time slot for students to self-organise into groups that meet the needs of their cohort or the organisation, which could include (but is not limited to):
- Researching ideas and contacting potential product owners for student projects (with guidance around what makes a good client and project for weeks 13-16)
- Peer-led review of previously covered material
- Forming study groups to work through material not covered in the course
- Volunteering to coordinate speaker slots 
- Responding to `our-site` PRs
- Forming groups to work on internal FAC projects (such as the FAC Library)
- Collect and organise photos and videos of the current cohort's activities

Students, not the course facilitator, would be responsible for organising this time. I would suggest that students establish a **structure for checking in at the beginning of the time slot each week,** possibly by **circling up** and sharing what each person/group is currently working on, so that people looking to work on something different or new will be able to sort out how to proceed. 

In the event that students want guidance from alumni, we would encourage them to raise issues and/or communicate on Gitter to share their requests. Alumni would also be welcome to raise issues regarding potential tasks/projects students might want to take on or work with them on.

**Comment by m4v15** [comment]
I like the idea in general - I think we have found it hard to get Biz Dev fully maximising it's potential in Nazareth for a lot of the reason's you've observed. Regarding your suggested activities:

> Researching ideas and contacting potential product owners for student projects (with guidance around what makes a good client and project for weeks 13-16)
 
I'm not sure how feasible this is - in the early weeks of FAC that is a very daunting task and I think getting good clients and PO's for weeks 13-16 is important enough that it should be one of the main roles of a CF/programme director. Although I do think students who are interested could definitely get involved - maybe if it's more an opportunity for the students to help the CF/programme director to do this, as opposed to putting it totally on the students (this maybe is what you mean in the first place!)

- All the other ideas I think are 👌 

- For both FACN1 and FACN2 the social media task group has been the one thing that has been consistently working throughout the course (as opposed to some of the other biz dev teams) so I would also add this as one of the suggested activities. Bear in mind tho that this could just be due to the students that are on the committee/task force and not inherent to the task force itself.

**Comment by rebeccaradding** [comment]
@m4v15 agreed, goal is not to put it on the students, but rather to provide students with enough context (i.e. what makes a good product owner/project) to mine their personal contacts for leads to then refer to the programme director/CF.

**Comment by mattlub** [comment]
@rebeccaradding it sounds good theoretically, but I wonder how it would actually pan out- I imagine in N2 that everyone would have ended up going over the material. But then again maybe that's just what the specific needs of their cohort may have been.

Also I imagine how it is pitched to the students at the start would greatly affect how it goes.

**Comment by rebeccaradding** [comment]
@mattlub people may also start out focusing on material, if that's what they feel they need, and shift their focus as they become more aware of what their cohort might need.

Do you have any further thoughts on how to pitch this time? Would it be useful to provide new students with examples of how previous FAC participants have taken on projects internal to their cohort (such as having @veredrec talk about coordinating speakers)?

**Comment by sofer** [comment]
I would put most of the emphasis on:

> Researching ideas and contacting potential product owners for student projects (with guidance around what makes a good client and project for weeks 13-16)

@m4v15 regarding the difficulty of finding product owners, we could build a resource library of potential contacts as well as advice on finding them and how to contact them.

**Comment by rebeccaradding** [comment]
@sofer I would suggest that we properly support students in engaging product owners, but not present this time as a time solely focused on procuring projects. In Nazareth (and Gaza, if this time is allocated), that may not be necessary, and in London, my guess is that encouraging, rather than mandating, will produce the most promising leads.

**Comment by jsms90** [comment]
## FAC11 report
My implementation of the Course Facilitator role during biz dev can be thought of as UX Research.

A Course Facilitator's notes be thought of in the same way as the note-taker role during user testing, where students are "users" of the London Programme.

Below is my research report & suggestions for future improvement.

### Notes
[Week 1 progress update](https://github.com/foundersandcoders/london-programme/issues/254#issuecomment-312900578)
[Week 2 progress update](https://github.com/foundersandcoders/london-programme/issues/254#issuecomment-314260781)

- The 2 bullet points of description provided to each team is not enough. Students need to know the history of what has happened in FAC prior to their arrival, what FAC's intended next steps are & what the students are/aren't allowed to decide without the approval of relevant stakeholders.

[Week 14 progress update](https://github.com/foundersandcoders/london-programme/issues/254#issuecomment-332812765)
> - Those without a point person at all generally floundered and produced far less output than those with a point person and/or clear remit
> - Teams with the most active biz dev point people ended up being given a fairly narrow set of pre-defined tasks to complete. All groups with an active biz dev point person have expressed frustration at various points about the lack of autonomy or the menial nature of the tasks.
> The other teams were formed around real-world needs within the organisation. They may not have had a formal "biz dev point person" but had regular contact with stakeholders in the organisation who could answer their questions. After discovering the needs of the business up front, these teams were able to operate with a relatively high degree of autonomy.

### Analysis / Impact summary
Negative impact:
- Little of biz dev time is actually being spent on addressing the core needs of the campus as a business. As such, many students do not feel particularly invested in the activity and treat it as their own free time. This varied attitude to biz dev time can frustrate those who take it more seriously & this rift **negatively impacts cohort cohesion.
- If the biz dev point person is the only one who understands the core needs of the business, they end up assigning very restricted tasks to the students. Without sufficient autonomy to act alone, students become bored & disengaged.
- At times of high stress in the curriculum, students become resentful of their time being wasted. Either attendance drops, or students choose to use biz dev for something else that is actually productive.

At best, time is not being used for business development within Founders and Coders. We cannot afford to waste this opportunity, in an organisation which lacks sufficient funds to pay its workers.

At worst, students get used to the idea that FAC doesn't know how to make the best use of their time and trust drops. **In a business model that is based on reciprocity and giving back, it is essential that we develop trust.**

Positive impact:
- The most passionate and/or engaged biz dev teams were those whose task groups were solving a real-world need for their cohort (i.e. Environment & Calendar Coordination) or within the wider FAC organisation (Library & Meetups). In fact, they were so motivated, that they were willing to spend more than the allotted 2 hours per week on their tasks.
- When a task group's remit was unclear, but students had enough interaction with alumni/other stakeholders (Library with @bradreeder & @jsms90, Outreach with @sofer), they were able to go beyond their original remit, define their own tasks & operate with greater autonomy.
- When students became aware of the real-world needs within the organisation, this resulted in some internal project pitches (during week 10) that revolved around solving FAC's needs.
- The team working on the FAC Application website had greater interaction with alumni/stakeholders in the organisation, gained insight into the needs of the business and are therefore more involved in the running of the organisation.
- Because the FAC Application website solves a real-world need, alumni have been contributing to the repo.

The task groups who were solving a real-world need within the wider organisation are the ones whose impact is likely to last beyond their cohort's graduation. These students also experienced greater interaction with other members of our community, which improves integration.

### Proposal
Week 16:
- Run How Might We session with all alumni who are active in the campus. Group themes & vote on which themes are most important to tackle.

Weeks 1-8 (internal focus):
- Show students result of brainstorming & talk them through the post-its i.e. the existing needs within the business
- Students divide themselves into pairs and choose a theme to tackle
- Students conduct research into FAC's needs as an organisation, such as:
  - field studies (e.g. going to external meetups, sitting in on scoping meetings that alumni have with clients, observations during FAC meetups)
  - user interviews (e.g. own cohort as 'users' of our curriculum, C4E attendees as 'users' of our application process, clients / hiring partners / funding partners as 'users' of our case studies)
  - stakeholder interviews (e.g. alumni & members of International)
  - analytics gathering / monitoring (e.g. collecting photos of current cohort, tracking meetup attendance & retention rates, tracking number of alumni employed post-FAC, financial reports and projections relating to grad projects)
- Students conduct competitor research & analysis

Weeks 10-13:
- No biz dev slots.

Weeks 14-16 (external focus):
- Self-development e.g. CV, portfolio website, LinkedIn profile - it is of direct benefit to FAC as a business for our graduates to be impressive to potential employers
- Sharing tips for tech tests / interviews
- Creating workshops based on material not covered in the course, which students have discovered through their internal or client projects.

**Comment by m4v15** [comment]
I think I have seen a lot of similar things to you Jen, although I would want to make one point - I think it is very hard as well to extract and analyse cause and effect, eg: 

>The most passionate and/or engaged biz dev teams were those whose task groups were solving a real-world need for their cohort

I'm a bit more of the opinion now that a selection bias leads to this becoming almost self-fulfilling: the students who want to get the most involved do the things that have the most impact, the students who aren't choose the vaguer tasks which allows them to do less. Or the tasks the more passionate students choose end up being more successful. 

We definitely want to to engage and make everyone want to give back, but there are always going to be more enthused community students and ones who are more in it for their personal development - we can't *make* people care.

I do really like the idea of the structure and the general idea of autonomy of telling the students 

*"Look, here are issues that have come up and we want to work on, let's have a discussion about what we want to do to help solve them"*. 

I would be wary of setting an exact way of how this would play out from there though, and feel like this should come from the students, with some facilitation. 

I think, at least in Nazareth, if the first few weeks of Biz Dev are some sort of handover from one cohort to the next (maybe in weeks 1 and 2 we could ask the recent grads to come in) so we can then help nuture it into the current cohort's responsibility would be really good and hopefully create a sense of direction.

I would love to hear some current student input on this as it has come up in nazareth a few times @veredrec @matthewdking @Wyrd00 @sajedazoabi @Heathercoraje

**Comment by m4v15** [comment]
Question - who's responsibility is it to ensure Biz Dev runs well/successfully? Should this be something the CF team decides before the cohort - or maybe something we should get the current cohort to think about how they feel it could have been done better.

**Comment by jsms90** [comment]
## Solution = integration
Only by integrating all generations within our community, can we ensure that students experience autonomy **and** FAC (the running of the curriculum and the business alike) reflects the will of every individual in the campus.

### Curriculum planning -> Biz dev
If we want students to be able to act autonomously, they need access to the campus' history. Otherwise, as we have seen with prior iterations of the curriculum, the updates reflect only the will of a single cohort. Eventually, alumni/stakeholders become frustrated and disengaged.

For curriculum planning, we have achieved this integration by:
1. providing active support during delivery (mentors)
1. documenting feedback during delivery (students, mentors & Course Facilitators)
1. involving Week Facilitators in the planning process (alumni)


#### Providing active support during delivery
We've been attempting this through [biz dev point people](). But such an active role throughout the curriculum is unrealistic for most alumni, due to a lack of time (not passion) _unless_ they are being paid by FAC to help run the campus i.e. Hiring Manager / Course Facilitator / International.

It would be ideal if we could add a biz dev handover to our [list of mentor expectations](https://github.com/foundersandcoders/master-reference/issues/365), to ensure a peer-led environment.

In practice, however, I'm not sure it's realistic (at least in London) unless we are able to provide opportunities which keep mentors in the space for the first couple of weeks. [This is similar to what I've said about **expecting** support from mentors in the 2nd half of the course](https://github.com/foundersandcoders/master-reference/issues/646#issuecomment-332859684).

#### Documenting feedback during delivery (students)
We've been attempting to do this via issues in `<city>-programme`, with mixed success. Those who have used issues most effectively have had a biz dev point person and/or a clear remit.

#### Documenting feedback during delivery (mentors)
As stated above, it's unrealistic to expect consistant involvement from mentors, without providing them with a way to stay in the space.

In the absence of in-person contact, we need to document this "handover" between cohorts.

During today's biz dev time, I asked students to get their issues/files within `london-programme` into a state that could be handed over to the next cohort.

They did one or more of the following, depending on what was appropriate for their group:
- update the existing markdown files that relate to that task group e.g. [environment.md](https://github.com/foundersandcoders/london-programme/tree/master/environment) (which details how to use the resources within the campus)
- create a markdown file with a progress report like [FAC9's environment task group](https://github.com/foundersandcoders/london-programme/blob/master/environment/fac9-update.md#fac9)
- create an "epic issue", so the next cohort could see one place with all the open issues relating to that topic & decide which things to pick up

#### Involving alumni in the planning process
See my suggestion above about the "How Might We" brainstorming session. Perhaps we could run this with FAC11 during week 16?

**Comment by rebeccaradding** [comment]
@m4v15 @shiryz @mantagen @eliascodes @des-des @jsms90 @sofer if possible, I suggest we discuss these ideas at today's (15:00 London time) standup, to get a sense of:
- How individual campuses envision making best use of this time
- What, if any, `master-reference` level guidance would be useful for individual campuses

**Comment by mantagen** [comment]
@ZooeyMiller @eliascodes I think you're input would be appreciated on this too, particularly wrt Gaza.

Currently the time is not allocated for Biz Dev at all, instead for course/curriculum work. One suggestion that came up in the last meeting was that it could be used as a kind of FAC community time (wider and local). Integration with the wider FAC community hasn't really happened until the Curriculum Planning, and many here still aren't on the founderscoders gitter room!

I think it would be worthwhile having them engaged from earlier on

**Comment by eliascodes** [comment]
@mantagen what does community time look like? What would they be doing?

**Comment by mantagen** [comment]
@eliascodes that's where your input would be appreciated. Or other extra-curricular ways for them to spend the time effectively.

An idea was for them to study power structures, since most of them here (likely) won't be familiar with the consensus based model, and i feel that without the wider network and english mother tongue, a lot of the peripheral (but still important) understanding of FAC does not disseminate.

Like I say, your suggestions would be welcome.

**Comment by sofer** [comment]
After today's meeting in London, there is a move that may be relevant to other campuses to [shift towards using this time for planning projects](https://github.com/foundersandcoders/london-programme/issues/477) in the second half of the programme. Assigning to me, @iteles and @mcelearr.

**Comment by sofer** [comment]
[This](https://github.com/foundersandcoders/london-programme/issues/491) is now likely to be happening in London.

**Comment by mantagen** [comment]
@saralk Thoughts on this for gaza?
