### ISSUE TITLE
Condense node girls workshop steps 1 - 5

### ISSUE THREAD

**Issue by dangerdak** [foundersandcoders/master-reference#659]
Make these steps shorter/easier/more explicit so that people can get to step 8 (8 - 10 are the most important ones).

https://github.com/node-girls/workshop-cms

**Comment by dangerdak** [comment]
@msmichellegar @minaorangina @heron2014 Hello, I'm from fac11 :) 

Your workshop is great already but we found that the first steps took too long for us to fit them well into our schedule - we're thinking about ways to condense them or help people get through them more quickly to make sure people can get to the end - just wondering if any of you have any tips or ideas? Thanks :+1:

**Comment by minaorangina** [comment]
Hey @dangerdak :)

So we use the CMS workshop when running our [Node Girls events](nodegirls.io).  The steps are quite in-depth because a wide range of people come to events - from people who work as front-end developers to people who have never touched the command line in their life.  

People at FAC are probably on the more comfortable end of the spectrum, though in the 2 years I was at FAC, I saw that's definitely not a guarantee.  There's a range of "comfort levels" on every cohort.

I have a couple of suggestions:

1.  Can you extend the time given to the workshop?  I know how difficult fitting everything into the curriculum can be, but the fundamentals of Node.js are pretty crucial to the rest of the course, so might need to be given priority.

2.  If that's not an option, you can create a tl;dr version of steps 1 - 5 in a single readme, with just the bits FACcers need to understand.  Then, link it to step 6 and people can continue from there. 

Given you've recently done the workshop on FAC11, you (and other people in FAC11/10 etc) know which bits can be skimmed over.

If option 2 is what you go for, please, please be careful not to cut out so much that some less-comfortable people on the cohort end up feeling stuck! We don't want any sad FACcers.

You could leave links to the full steps throughout the tl;dr readme, so that anyone who needs to can look at the full version for reference.  Then you get the best of both worlds :)

Hopefully that's helpful to you?

**Comment by minaorangina** [comment]
And I've just thought of an option 3:

During Node week, you could just tell people that if parts of steps 1 - 5 covers stuff they know already, they can skim-read.  And let them know that they should go through it more thoroughly from step 6. 

Sometimes these things are just a matter of managing expectations, and by giving people a heads-up, they can decide for themselves how to proceed. 

Of course, this means people will finish at different speeds, but that's natural for workshops - different people know different things.

**Comment by dangerdak** [comment]
@minaorangina thanks so much for your suggestions, you make some really good points.  I liked the sound of option 2 but after working through the workshop again I don't think there's much we could shorten without risking peoples understanding. I think we'll just have to make more time for it!
