### ISSUE TITLE
Better integration of UX / client-related topics into curriculum

### ISSUE THREAD

**Issue by emilyb7** [foundersandcoders/master-reference#66]
In light of the frustrations felt on both sides (students and mentors) this week surrounding UX, a quick proposal / suggestion for future improvement.

I think one of the main problems with the user testing session proposed for week 11, which didn't go ahead, is that we struggled to see the overall purpose of the session (beyond getting a bit of experience), because the situation was somewhat contrived. Approaching strangers to talk about our plans for an app that we have no intention of building is, at best, awkward. Similarly, I think some of us found it hard to enjoy working with "fake" clients in weeks 9 and 10 and therefore didn't get the most out of those weeks. And yes, I know we should be pushing ourselves and getting out of our comfort zone and do awkward things for a good reason!! But I still think that we can make this better.

In addition to that, I've found the fact that weeks 11 and 12 are run by DWYL but don't actually have that much to do with DWYL - besides the excellent resources - a bit confusing.

@nelsonic, @iteles and everyone else at Dwyl have so much valuable knowledge and experience that we could learn from but we get very little insight into what you do on a day to day basis and where things like UX fit into that.

So my suggestion is that we drop the "fake" at least some of the role play and pretence and that future cohorts get the opportunity to experience a bit of real-life client work by for instance joining Dwyl for part of a day, or sitting in on a meeting with a client, or observing some actual user testing sessions. Basically, I think it would be great if we could work together in a more hands-on way to provide us all with some context for what we're doing. This could maybe be optional for students.

I realise that there are most likely difficulties in terms of coordination, that DWYL may not have the resources and that we might be an unwanted interference. And probably other problems that I've not foreseen. But I just thought I'd put this idea out there... Beyond UX, personally I would relish the opportunity to find out more about what goes on next door to us every day!

**Comment by jsms90** [comment]
Personally, I _love_ @bradreeder 's suggestion https://github.com/foundersandcoders/master-reference/issues/14#issuecomment-270013472 that we distil the current 9-week curriculum into 8 weeks, then make weeks 9-10 a kind of "final project" in the form of a 2-week agile sprint :smile: Let's keep the best elements of our weeks 9-10, but make sure that there is enough build time to complete the sprint! That goes part way to making the whole thing feel more real.

As @emilyb7 says, one of the biggest learning points from our cohort's week 10 s-g-c was to remove the fake/role-play element. I think I remember rightly that the alternative suggestions were:
- students pitch their own project ideas
- build something for F&C (my personal preference, so that we retain [managing client interaction](https://github.com/foundersandcoders/master-reference/issues/14#issuecomment-272720167) as a hugely important learning objective from those weeks)

Another bit of our week 10 that was "faked" was the user testing. Our cohort was given the option of either interviewing each other and the F&C alumni, or getting out of the building and asking people on Roman Road. I'm sure that we all used the excuse of "time constraints" to justify staying in our comfort zones, preferring to spend time on building the prototypes and learning more CSS, rather than accosting strangers in coffee shops. But I actually think that a lot of us strongly agree with the _reasons why_ @nelsonic wanted to introduce user testing / research into week 11:
> once people are in the "Junior Dev" ("marketplace") working in a company that doesn't do user-testing (which is 90+%!!) this will all be a distant memory and it will be 2 years, 3 "jobs" and 6 projects before most of you reap the benefits of pre-product UX-research/testing
> I've since realised through much pain of wasted effort on go-nowhere apps
that unless there is a user-testing-early-and-often culture in your team/company,
projects developed by highly competent/experienced "engineers" flat out fail to get any traction thus resulting in vast wasted effort and disappointment! (Not a Nelson quote btw)

The vote wasn't unanimous and some people were very disappointed not to go to Google campus and have that learning experience. Either way, I _really_ don't think that it was about preferring to learn a new technology. As @emilyb7 says:
> we struggled to see the overall purpose of the session (beyond getting a bit of experience), because the situation was somewhat contrived

I suggest that we _require_ F&C10+ to get out of the building and do the week 10 user testing task with strangers. @Cleop shared her interview expertise (and her fiance's) with her group - me, @msachi & @njsfield, which we all then shared with the cohort during our presentation at the end of the week. We did see the value of having less a contrived group of users than just members of F&C, and tried to make it slightly more realistic by asking family and friends at home. However, that is still worlds away from actually getting out and talking to strangers! Personally, I have lots of sales experience, including door-to-door sales (a very dark time in my life - don't ask ;) ) but Cleo & Anish's help on how to conduct user testing interviews certainly made me feel much more comfortable about doing this outside F&C!! So let's give F&C10+ as much guidance as possible e.g. https://github.com/foundersandcoders/master-reference/tree/week-11-functional-porgramming-redux-todo-UX-testing-field-trip/coursebook/week-11 **& more!** I would be happy to work (maybe with Cleo?) on writing some even more fleshed out advice for future cohorts about conducting interviews.

I'm not sure whether visits to DWYL could be incorporated into this kind of 2 week sprint? I would be concerned about breaking up the flow and the sense of urgency in the sprint, particularly as the students would have to fit around DWYL's timetable with its clients. But perhaps these kind of work shadowing opportunities with DWYL could exist during the subsequent weeks, as they could be considered ["outside the curriculum"](https://github.com/foundersandcoders/master-reference/issues/14#issuecomment-272724173). I think that every hour in the curriuclum should be fighting for its place. But Emily is absolutely right - we are missing out on a huge opportunity right now, so if this is the best place to put it into the course, let's do it!

**Comment by iteles** [comment]
@eliascodes Was anything actually done about this?

**Comment by eliascodes** [comment]
@iteles sorry, I probably should have sought agreement first, but I was under the impression that weeks 10-16 now look considerably different from how they did during FAC9 when this issue was raised. FAC11 and FAC12 have approached and worked with real clients for the final project in 13-16 and I think the design week/build week structure in weeks 10-12 has been improved.

Happy to be corrected and re-open this if people think the original issue still stands.

**Comment by iteles** [comment]
I was also asking more out of curiosity as my involvement with the curriculum has dropped to zero in the last 6 months and I think this is an important issue. I'm sure @nogainbar and @harrygfox will have a better grasp of this than me and will reopen (or open a new issue) if they feel more work can be done 👍

**Comment by harrygfox** [comment]
I'm pretty sure @nogainbar and I resolved all of this with the 2 week projects following the design week @iteles @eliascodes 
The situation now is much more true to life: they design a product, test the design, learn from it and then build for 2 weeks.

**Comment by iteles** [comment]
Good to have it recorded here as the conclusion. Thanks @harrygfox @eliascodes
