### ISSUE TITLE
Status of "Pure Functions Easy Testing" workshop

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/master-reference#759]
At the moment, the version that has been used for the current cohorts (FAC12, N3 and G3) is a [forked version in the Founders and Coders organisation](https://github.com/foundersandcoders/pure-functions-easy-testing), however [the original one](https://github.com/Jwhiles/pure-functions-easy-testing) owned by @Jwhiles still exists. 

Are we planning to PR to @Jwhiles' repo? Or ask to move the original repo under the founderandcoders organisation? Or stay with using the forked version? 

Using a fork has its downsides as it means we can't have issues for the fork, which is a shame. We also don't have an assigned maintainer for the fork. I'm also unsure of how @Jwhiles feels about the fork?

My understanding is that the main change is the change from Qunit to tape for testing.

**Comment by eliascodes** [comment]
I've added issues to the fork.

**Comment by Jwhiles** [comment]
IDK why issues on forks are disabled by default. It's silly. 

I think that the FAC fork is the more up to date version so just run with that one?

**Comment by astroash** [comment]
@Jwhiles would you be happy to either:
- merge the fork into your master and transfer ownership to the FAC organisation
- us to duplicate the fork into a new repo under the FAC organisation

It would be fab if we can start bringing fac resources under these [new criteria](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/creation-of-resources.md)

_copied here because no one needs any more tabs open_
> When making a new workshop/morning challenge:
>1. Create a new repo within the `foundersandcoders` GitHub organisation
>1. Follow the repo naming convention - prepend the name with:
    - `ws-` for workshops
    - `mc-` for morning challenges
>1. Make a PR to the `master-reference`, editing the [resource index](./resource-index.md) to add a link to your repo
>1. Start your repo's `README.md` with a set of learning outcomes
>1. Ensure your `README.md` contains a link to the `CONTRIBUTING.md` in `master-reference`
