### ISSUE TITLE
Bring Week 13 forward

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#820]
We have been covering React in Week 13, but some of FAC12 have already been using React in their first project. Perhaps it would make sense to bring Week 13 forward to Week 11, i.e. straight after design week, so that anything learnt in the workshops can be applied straight after. Weeks 10-16 would then look like:
- ~~Week 10: Design thinking; Internal projects, design sprint~~ [amended]
- Week 10: Workshops (React or whatever the students and mentors are most interested in)
- Week 11: Design thinking; Internal projects, design sprint
- Weeks 12-13: Internal projects, Build sprint
- Weeks 14-16:  Client projects, design + build sprints

**Comment by claireinez** [comment]
I had been thinking about raising this same issue because some of FACN3 have also been using React for their first projects and I didn't realise it would be taught in week 13 anyway. I don't know if it makes sense to split design week off from the two-week build sprint though (@harrygfox any thoughts?).

I would suggest either moving React week to before the design sprint *or* suggesting that students don't use React for the first project as they will have the opportunity to learn it in a few weeks.

**Comment by harrygfox** [comment]
_What if we design a project that doesn't need react?_ Shoe-horning it in would be against the principles of design thinking. 
The situation we have in Nazareth right now is that half of the teams have used react in their projects and half have not, so having a react week *after* the projects would create a divide between those that want to move at a much faster pace than those that have never touched react before.
Therefore, I agree with @claireinez in that **it should happen before design week.** 
There is a misconception that design week is about learning a new/interesting/darling technology - I would anticipate everyone asking "so we're designing a react app?".

**Comment by m4v15** [comment]
I agree it seems to make more sense to happen before design week - although maybe could also be flexible to work around bank holidays etc? I know in London this time (and previously) they've only had 4 days for design week which is very inconvenient whereas React week is only actually 3 days of workshops so would be less affected by bank holidays.

**Comment by shannonjensen** [comment]
Personally, I think React week after design week would be better. I enjoyed design week as a break from coding workshops after 8 weeks straight. And a welcome jump finally into a longer project after 8 weeks of two day sprints. It is good to mix it up, and then the students will have their pending project in the back of their heads while they learn react and other middleware tech. It gives more time for ideas and plans to percolate. It doesn't force anyone to use react for their project (but let's be honest, is that so bad to encourage anyways? isn't it better job-market-wise for people to use react over handlebars? Or am i wrong in that assumption?) If anything, the way it is structured now encourages people to use react for their client projects, where it's far less desirable to go in with fixed ideas about tech (whereas the first project is purely a learning exercise so why not use react). We have some people on our cohort now disappointed they didn't use react on their first project bc it may not be called for by their clients needs...

**Comment by harrygfox** [comment]
@shannonjensen 
Thanks for your input, what you've said here:
> the students will have their pending project in the back of their heads while they learn react and other middleware tech. It gives more time for ideas and plans to percolate. It doesn't force anyone to use react for their project (but let's be honest, is that so bad to encourage anyways? isn't it better job-market-wise for people to use react over handlebars?

I think is a somewhat short-sighted view and I believe it would undermine the value of design week. I also believe it **would** effectively coerce students into using React for their build phase.

Choosing tech **and then** designing a product around the tech invariably shoehorns features into projects. The mantra I want to install in FAC students is that you must **build the right thing**. If the right thing requires React, then great, use React.

The value of the 3 weeks run _consecutively_ teaches immensely valuable skills: design thinking, scoping an MVP and how to work in a real-life working environment. That's already enough of a headache, enough lateral thinking, enough of a difference from everything that's come before for most students.

In my experience running design week for FACs 8-11 and for FACN3, the worst products (those which address and solve no problem) are those which were built **for their own sakes** - They were built because the students wanted to learn technology X or wanted portfolio piece Y. 
From my real-life working experience, I would also say that product-oriented developers, those that understand the value of designing something meaningful, are more valuable to their teams, and to startups _in general_, than code-oriented developers. I am of the school of thought that FAC should not produce code-monkeys aka cogs-in-the-machine.

Apologies for the long post (I really hate them myself) and for the code-monkey slur and I'm sorry if it comes across as condescending: it's not aimed at you personally, it's a long-festering gripe I have with the undervaluing of design.

**Comment by shannonjensen** [comment]
@harrygfox Thank you for the long and thoughtful reply. Of course we don't want projects built for their own sakes. And I agree with everything you said, I just felt like it might be useful to consider an alternative since everyone quickly coalesced around moving react week to week13.

**Comment by shannonjensen** [comment]
Not sure if this is the right issue to post this, but I also think all mentor prep should be moved to week13. I am quite annoyed that we are losing 2 full build days (more than 30% of build time) for our client projects to mentor prep and workshops. We only have 5.5 days of build time rather than the 7.5 we would have otherwise. Building a project for a client is a big step (especially for those teams using new technologies) and 5.5 build days over three weeks seems inadequate, especially when we told the client it was a two week build sprint.

**Comment by matthewdking** [comment]
Another point to consider that hasn't been mentioned yet is that this cohort had a two week reading week rather than the usual one week. This probably meant students were more likely to learn something new such as React in reading week. In future it may be less common for students to use React in the first project.

Also it would be good to hear from those students that did React in the first project and still did the workshops. 
- Did they find the workshops useful even though they had just done a project in React?

**Comment by mattlub** [comment]
what about:
- week 9 React
- week 10 reading week

**Comment by sofer** [comment]
I am no longer convinced that Week 13 should be moved forward. Using React once in 16 weeks is OK, but encouraging it to be used twice would be doing students a disservice. We should offer reading week study for those that are interested, but not including React.

**Comment by claireinez** [comment]
@sofer would you recommend that students don't use React in the first project or leave it as it currently is?

**Comment by isnotafunction** [comment]
@harrygfox 
> Choosing tech and then designing a product around the tech invariably shoehorns features into projects. The mantra I want to install in FAC students is that you must build the right thing.

Not sure if I should mention it here, anyhow, this is exactly the reason I feel pitching/choosing internal projects should not happen before the design week, but during or after. The frustration our team experienced during dw was mainly due to trying to find a *problem* for our solution(that we already agreed to build 2 weeks back), instead of the other way round.

**Comment by oliverjam** [comment]
Apologies for commenting after the issue was closed but I only just found it.

I'd broadly agree with the conclusions drawn: in my experience students "get" React more easily when they've at least tried to build a medium-complexity project beforehand. The problems React attempts to solve are less evident when you've only ever done 2-day FAC projects.

So it's better for students to have done a post-Reading Week project with the "FAC stack" of Express/Handlebars—I'd go so far as to warn students that they'll be covering React in Week 13 and should probably avoid using it for their first project.
