### ISSUE TITLE
Prerequisites: freecodecamp

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#858]
We probably should move over to freecodecamp's new curriculum.

https://beta.freecodecamp.org/

**Comment by iteles** [comment]
React? Node? D3? As pre-reqs? 
Is testing a part of the curriculum?

Won't this blanket resource just increase the gulf between those who have less time/full time jobs to apply and those you have nothing else to do or have a full 4 months+ to apply?

At which point will we hit the point where we get applicants that Founders & Coders is no longer useful for?

**Comment by eliascodes** [comment]
> React? Node? D3? As pre-reqs?

These things are all already part of the current FreeCodeCamp curriculum. We require a small subset of the basic sections of the curriculum as pre-reqs (HTML5 & CSS, Basic JavaScript, Object Oriented and Functional Programming, Basic Algorithm Scripting).

> At which point will we hit the point where we get applicants that Founders & Coders is no longer useful for?

I feel like we have been at that point for a while. One for the selection committee IMO. It might be an idea to also keep track of how many applicants have been declined because of being too advanced.

> Won't this blanket resource just increase the gulf between those who have less time/full time jobs to apply and those you have nothing else to do or have a full 4 months+ to apply?

Yes, but this is not a new problem, nor specific to the new FCC curriculum.

**Comment by iteles** [comment]
I think FCC is fantastic, it just seems a bit overkill for pre-reqs in its entirety - but it seems that we require only a subset of this which wasn't in the context for the issue :+1:

Thanks for clarifying @eliascodes 🎉

**Comment by ZooeyMiller** [comment]
I agree that we should swap to the FCC beta, though of course only specifying certain parts. 

Since it explicitly teaches ES6 as well, it could be worth reviewing the pre-node embargo on ES6 during the course.

**Comment by matjack1** [comment]
I've been trying beta.freecodecamp.org a number of times now as I would like to move to that too as soon as possible during our Italian Coding for everyone.

While I think that the material is far superior (and translated too!) I also think that the site is still very much "beta". The speed is sometimes a problem and the interface at times a bit clunky.

So while I like the material I'm not sure if it's mature enough for spending many hours on it. If you have good opinions about it I'll spend more time on it to get a deeper opinion.

**Comment by astroash** [comment]
Freecodecamps new curriculum is [now live](https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130). The sections that are part of our prerequisites still exist, but are ⭐️ **_significantly_** ⭐️ longer and more detailed. FrontEnd is no longer a certificate and has been broken up into Responsive Web Design Certification (300 hours), Javascript Algorithms And Data Structures Certification (300 hours) and Front End Libraries Certification (300 hours). 

Some of the additions I've spotted in our required sections:
Basic Js
- mutable array methods
- scope
- switch statements
- ternary operators

OOP
- this
- classes
- prototypes
- iifes

FP
- pure functions
- moar array methods
- introduction to currying and partial application

These are obvs great topics, but I think they may be too advanced without following the FCC curriculum in order. Below is their js curriculum with our prereqs highlighted:

**Basic JavaScript**
ES6
Regular Expressions
Debugging
Basic Data Structures
**Basic Algorithm Scripting**
**Object Oriented Programming**
**Functional Programming**
Intermediate Algorithm Scripting
JavaScript Algorithms and Data Structures Projects

I'm going to have a little play with these sections over the next few weeks to see how easy I think it is for new learners to dip in and out of. In the meantime I think it's worth talking to meetup attendees to see if they have been using the new FCC curriculum in the order we suggest, and how they are finding it.

**Comment by sofer** [comment]
A first uninformed suggestion to get the ball rolling:
- Basic HTML and HTML5
- Basic CSS
- Basic JavaScript
- A Minimum of 200 points, based on also completing any of the other topics that take your interest

But to be honest, it all looks great.

We do need to update the website and prereq-check asap.

**Comment by eliascodes** [comment]
I don't know what was previously in the OOP and FP modules, but looking at the current curriculum, I'd question their value as prerequisites (as opposed to, for example, pre-course material): I could be wrong, but I don't think we're seeing anyone come onto the program with any understanding of prototypical inheritance, mixins, or simple OO design patterns (nor, on the other side, side-effects, non-mutative methods, avoiding global variables, closures, etc).

I think applicants would be spending their time better if they replaced the OOP and FP modules with Basic Data Structures and ES6.

> A Minimum of 200 points, based on also completing any of the other topics that take your interest

I guess this is fine, but I think we should at least offer a prioritisation of topics as a guide for those who feel like they need it. The two modules mentioned above would be (IMO) top of the list.

**Comment by astroash** [comment]
I had a go at summarising LOs from the previous FCC topics, which I nabbed from [here](https://github.com/foundersandcoders/prereq-check/blob/master/model/freecodecamp-arrays.js):

HTML5 & CSS
- intro to common html elements
- inline styles vs class styles
- layout styling with css, such as positioning, margins and padding
- visual styling with css, such as colours, borders and backgrounds
- specificity in css

Basic JavaScript
- what is a `var`iable and how to declare one
- arithmetic operators
- working with strings & arrays & objects
- comparison operators
- conditional statements
- for loops
- intro to regex

Object Oriented and Functional Programming
- constructing objects with functions
- immutable array methods

Basic Algorithm Scripting
- using functions to manipulate strings, arrays and objects

And collecting previous suggestions of what grads wanted to be added to prereqs:
- #391 adding flexbox, semantic css and HTML 5 to prereqs
- [fac12 feedback](https://github.com/foundersandcoders/london-programme/blob/master/stop-go-continue/fac-12/curriculum-feedback-week-11.md#es6) / [#691](https://github.com/foundersandcoders/master-reference/issues/691#issuecomment-359189213) introduce es6

From this I was thinking that the following sections _could_ be a good basis for prereqs:
### Responsive Web Design Certification
Basic HTML & HTML5
Basic CSS
Responsive Web Design Principles (maybe?)
CSS Flexbox

### Javascript Algorithms And Data Structures Certification
Basic JavaScript
ES6
Basic Data Structures
Basic Algorithm Scripting

However, I'm aware that this may be asking for a lot more hours than previously, so wanted to sift through them first.

**Comment by sofer** [comment]
Useful feedback from FAC-14 ([via gitter](https://gitter.im/codingforeveryone/FAC14-Temporary)):

> in the JS section everything before intermediate algorithm scripting looks like it would be worthwhile - a lot of the new content would have eased the leap from FCC to Codewars

> I think it all looks fantastic but I wonder if it now might be more daunting for FAC applicants now - with front-end and algorithms now split out I think people might need to explore it in a more non-linear fashion than before, although the old curriculum basically introduced DOM manipulation as jQuery and a lot of Bootstrap which I personally found a little counterproductive for FAC so I don't think the 'old' curriculum was completely linear, either. I love that flexbox, grid and accessibility are all there (can't wait to go through them myself) but it feels like it now extends the path for people to get onto expressing themselves with their portfolio site which always struck me as perhaps the core ask of the pre-reqs. As for the JS I personally think people should get up through basic algorithm scripting and then get nudged straight to Codewars - getting comfortable on Codewars really feels like a massive 'a-ha!' moment - even though the OOP and FP modules obviously have fascinating benefits. To me a lot of the new curriculum overlaps with the pre-course material, so I think new newbies could potentially get a little overwhelmed and think they might need to know a lot more than they probably do.

> I think a lot of the new content would provide for great "suggested chapters" to help with the personal site build and for having more confidence getting on with codewars
The accessibility chapter doesn't look too long, though. It could be nice to add that in as a pre-req if so! I'll give it a go myself sometime soon.

**Comment by FarahZaqout** [comment]
You guys might wanna take my feedback with a grain of salt as I'm only speaking about my experience as a student who is yet to graduate :smile: , but here are my two cents:

Shifting to the new FCC curriculum would be great. It has a lot of different things that are very well done. Personally, based on my experience throughout the course, introducing the accessibility, responsiveness, and ES6 syntax in FCC will help the students a great deal, especially the new learners. As these things are critically important for a web developer but are only assigned a short amount of time during the course. Unfortunately, until this point, at week 14, many of us haven't a clue about the importance of accessibility, responsiveness and search engine optimization because of that.

Early knowledge of ES6 will make it possible to start using linters much earlier than week 6, as Matt Davis suggested, which is really helpful for getting used to standardized and clean code writing from the moment we jump into backend coding. Especially that we only actually started using them by week 8 this time, and many of us are still far from clean when it comes to how we write our code.

I feel like object oriented programming the way it's done in the new curriculum is going to be a great addition as it just slipped our minds in its entirety, largely because the course just felt intense that we forgot that there is even such a thing. Regex is also a great addition. I feel like most of us are not comfortable with using regex even at this point which is such a shame.

As someone coming from a non-IT background, I am certain that this will make the preparation process a little more daunting at first, especially if people have like one month only to prepare or so, but it will make both the transition to codewars and keeping up with the course a lot easier in many respects.

I think the new curriculum will facilitate better preparation of new students for the course, and allow them to get much more value from it. At least within the context of the Gaza program.

I hope this is relevant to the discussion.

**Comment by m4v15** [comment]
re: @astroash's recommendations, they are _very_ similar to what I said to an unsuccessful g5 applicant who asked how to improve - they have a long time to apply so I said a little more things:

  >Responsive Web Design Certification and the Javascript Algorithms and Data Structures Certification - focusing on these parts:
*Responsive Web Design*
Basic HTML and HTML5
Basic CSS
*Javascript*
Basic JavaScript
ES6
Regular Expressions
Debugging
Basic Data Structures
Basic Algorithm Scripting
Intermediate Algorithm Scripting

**Comment by yvonne-liu** [comment]
What about splitting it between the prerequisites and the pre-course materials? 

### Prerequisites:

**Responsive Web Design Certification:** 
Basic HTML and HTML5
Basic CSS

**Javascript Algorithms And Data Structures Certification:** 
Basic JavaScript
ES6
Basic Data Structures
Basic Algorithm Scripting

### Pre-course: 

**Responsive Web Design Certification:** 
Applied Accessibility
Responsive Web Design Principles
CSS Flexbox

**Javascript Algorithms And Data Structures Certification:** 
Object Oriented Programming
Functional Programming
Intermediate Algorithm Scripting

**Comment by ZooeyMiller** [comment]
I think @yvonne-liu 's suggestion seems good, this is without an intimate knowledge of the content of the sections on FCC though. 

I'm assuming this will still be in addition to codewars?

It does bring the bigger question of what the point of the the pre-req's are, what problem do they address? But that's probs not a discussion for here.

**Comment by oliverjam** [comment]
@yvonne-liu I really like that idea. It shouldn't increase the workload for applicants, and will probably give people who are accepted a more solid base to begin the course.

**Comment by ibraghada** [comment]
@yvonne-liu My only concern regarding your suggestion that in Gaza, we might not be able to allocate much time for pre-course which I don't think is enough to cover these topics? 

Can anyone estimate how many hours covering those topics as a pre-course would take?? 

_And also_ What are everyone's thoughts on doing more of Freecodecamp and not doing Codewars?

**Comment by astroash** [comment]
do we have a deadline of when we want to make this decision by for fac15 and facg7?

@ibraghada what's the time between students getting accepted on the course and starting in Gaza? I believe in London it's 2 months.

Also, annoyingly FCC have removed the time estimates from challenges, as I assume they didn't want to discourage people who were struggling. Below I've made a rough estimate based on each individual challenge being 10 minutes long.

**Responsive Web Design Certification**
Basic HTML & HTML5 - 27 challenges - **4.5 hours**
Basic CSS - 43 challenges - **7 hours**
Responsive Web Design Principles (maybe?) - 5 challenges - **1 hour**
CSS Flexbox - 17 challenges **3 hours**

**Javascript Algorithms And Data Structures Certification**
Basic JavaScript - 107 challenges **18 hours**
ES6 - 27 challenges **4.5 hours**
Basic Data Structures - 21 challenges - **3.5 hours**
Basic Algorithm Scripting - 17 challenges - **3 hours**

_the following I've estimated at 15 minutes each challenge as they're more advanced concepts_

Object Oriented Programming - 27 challenges - **6.75 hours**
Functional Programming - 24 challenges - **6 hours**
Intermediate Algorithm Scripting - 22 challenges - **5.5 hours**
___
@yvonne-liu I like the idea of having sections assigned to precourse 😊. IMO I think it would be good to have _Responsive Web Design Principles_, _CSS Flexbox_ in prereqs as many applicants but a lot of effort into their sites, and it will give them a good grounding for doing this well.

I also wonder whether it's a bit counter productive asking students to do _Object Oriented Programming_. FAC's curriculum teaches functional programming, and I think it may be off topic for students to be learning about classes and prototypal inheritance when this isn't something used until react week. The few challenges in this section on scope are great, but maybe we can point students to another resource to learn about this.

**Comment by ibraghada** [comment]
@astroash 

> do we have a deadline of when we want to make this decision by for fac15 and facg6?

Applications for G6 will be open in a week - that's why we need to decide on this _very_ soon. 

> @ibraghada what's the time between students getting accepted on the course and starting in Gaza? I believe in London it's 2 months.

for G6 it's 2 weeks presumably Sep 9 - Sep 20 then we make final decisions and the course officially starts in later in October (_exact dates may change but the time frame is still the same_) 

Thanks for the time estimates - Do we know how many points these sections covered are?  coz we currently ask people to have a certain sum of points while covering certain topics. I guess now we need to be more specific..  

Also is CodeWars still valid? (I hope someone would help me figure out this one) 
do you think if they cover some of the projects (may be 2) in FCC JavaScript Algorithms and Data Structures section in addition to other previous ones that would be enough? 

>  also wonder whether it's a bit counter productive asking students to do Object Oriented Programming. FAC's curriculum teaches functional programming, and I think it may be off topic for students to be learning about classes and prototypal inheritance when this isn't something used until react week. The few challenges in this section on scope are great, but maybe we can point students to another resource to learn about this.

I quite agree to `this` one as the students won't need it until later on the course, I was planning to ask G5 to go through these challenges before React week accompanied with some resources to read from during Eid break.

**Comment by sofer** [comment]
To summarise contributions from above, it looks like the new prerequisites are:

**Responsive Web Design Certification:** 
Basic HTML and HTML5
Basic CSS
Responsive Web Design Principles
CSS Flexbox 

**Javascript Algorithms And Data Structures Certification:** 
Basic JavaScript
ES6
Basic Data Structures
Basic Algorithm Scripting

A Minimum of 200 points, based on also completing any of the other topics that take your interest.

And @ibraghada Codewars is still valid here in London.

**Comment by MMortaga** [comment]
> **Responsive Web Design Certification:**
> Basic HTML and HTML5
> Basic CSS
> Responsive Web Design Principles
> CSS Flexbox
> 
> **Javascript Algorithms And Data Structures Certification:**
> Basic JavaScript
> ES6
> Basic Data Structures
> Basic Algorithm Scripting
> 
> A Minimum of 200 points, based on also completing any of the other topics that take your interest.

I know this thread is like 7 months old now but according to my calculations completing these challenges gives you a total of 261 points. As for Gaza and the West Bank, many applicants are being told to reach 200 points (sometimes 250) then move on to codewars, however this doesn't look right as in both cases they're going to skip `Basic Algorithm Scripting` which is the first block in understanding how algorithms work in JS.
In my opinion, freecodecamp has stopped displaying points in the top-right corner on their website and we should stop considering them as well. Taking a look on the public profile and making sure the applicant has completed the required sections makes more sense because obviously there's no point of looking at the score itself when someone can complete challenges from any section (e.g bootstrap) and still gain points.

**Comment by eliascodes** [comment]
@sofer is there anything keeping this issue from being closed?

**Comment by zurda** [comment]
Agree with @eliascodes, I think this is resolved cc: @sofer
