### ISSUE TITLE
Week 9: Reading week

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#87]
I want to formally propose that Week 9 be considered reading week (and that we take a two-week reading fortnight over Christmas). See also https://github.com/foundersandcoders/london-programme/issues/135

**Comment by nelsonic** [comment]
@sofer this has worked well in the past so gets my vote. ✅ 
Are we going to give people _suggestions_ for what they _could_ read...? 🤔

**Comment by rebeccaradding** [comment]
@sofer do we want to consider _not breaking_ in Nazareth and stopping after 12 weeks so that international students can travel back to London during the 13th week without getting "behind?"

**Comment by iteles** [comment]
@sofer I think we need a clear directive on if the weeks *after* reading week are to be 'optional' or 'more lenient'.

We absolutely *need* a break by this point in the course, but what I've found is that there is a considerable dip in commitment to the course when people come back (partly also due to a less concrete organisation/availability of tutors in the final weeks).
