### ISSUE TITLE
React week is not in Master Reference yet

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/master-reference#878]
There's https://github.com/foundersandcoders/react-week and then there's https://github.com/foundersandcoders/london-programme/blob/master/weeks-10-16/week-13.md

It would be good to get React week all in one place and in master reference.

**Comment by morkeltry** [comment]
Thanks for linking to those. I only came across them as I was searching for the non-core weeks and eventually couldn't find them, so came here to make an issue about it!

I'd propose that, since it's an open-source curriculum, that all non-core weeks be easily accessible within the master-reference/coursebook structure. Even if it's a separate folder with an unordered list of optional or previous weeks. (I'm thinking Elm week specifically here, as well as FAC13's React week)

This would mean that if there is a serious move towards teaching something more optional, eg. Redux, that is a natural progression from the curriculum, then folks who want to mentor that or make content for it will duplicate less labour.

**Comment by astroash** [comment]
[There's a resource index here](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/resource-index.md), with a list of all workshops that have been created by alumni for students.

**Comment by zurda** [comment]
Can I help with a pr for this one? Happy to help if there's an action item. I personally looked for react week, so this issue rings true to me. More than happy to help prevent confusion for future students ❣️

**Comment by sofer** [comment]
@zurda thank you for the nudge 👍. In the light of recent conversations with maintainers, we are likely to move away from the aspiration of putting all learning resources into master-reference. Closing now.
