### ISSUE TITLE
Plan for feedback day

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/master-reference#9]
leaving for @bradreeder to fill out

**Comment by bradreeder** [comment]
I'm going to spend tomorrow on this. So far this is the rough outline:

* Presentation on master reference and course facilitator role: responsibilities, problems we're trying to solve, our proposed solution.
* Q/A on this -- in particular I want to work out how much time they need prepare their weeks, and what is a fair balance to them of their creative freedom and more infastructure.
* Get each person to come up with areas for improvement to stick up on the wall. 
* Followed by S-G-C discussion where we organise their improvements into high, middle, and low priority columns based upon level of agreement in the group.
* Introduce our version of the curriculum with its rationale.
* Contrast it with their improvements and adjust it so that it resolves as many of their high and middle priority issues as is reasonable.
* List the available roles (inc pre-course, gitbook editor, etc) and let the group assign themselves to responsibilities.

**Comment by bradreeder** [comment]
@des-des @iteles @nelsonic I have a feeling this will take us to 4, but as long as you're present for the main part in the morning it should be fine? Let me know if you have any issues with this outline, working on it this evening and tomorrow.

**Comment by des-des** [comment]
Feedback day done and was good!
