### ISSUE TITLE
Week -2 : Research Topics 

### ISSUE THREAD

**Issue by aterna01** [foundersandcoders/master-reference#957]
Research Topics for Week 2 are : 
1) Unit vs integration testing
2)Technical spikes
3)DOM manipulation
4)Test coverage
https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-2

We think Technical Spikes is too small for research topics. We are happy to explain it to students. Maybe that topic should be something else? Let's say Jest?

Relates #933

**Comment by astroash** [comment]
I really like @martingaston's suggestion in https://github.com/foundersandcoders/master-reference/issues/956#issuecomment-467608681.

Further suggestions of async-esque research topics:

- first-class functions
- call stack
- async function and blocking code

**Comment by zurda** [comment]
This is great, thanks everyone! 

Does the list below address the topics we want to cover? (I turned it into questions for consistency :) Thanks for the list @astroash !)

- What are **first class functions**, and **higher order functions**? 
- What is the **call stack**? 
- What are **async functions** and **blocking code**? 
- Give an example of a **callback function** and explain what happens when it is executed

**Comment by astroash** [comment]
Sounds like a great list. I would have a go at googling the questions and see if you can find the correct answers to replicate what students will do 🙂

**Comment by zurda** [comment]
I believe this was merged and can be closed
